# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protobufaweme_v2_feed_responseAdapter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import douyin_video_struct_pb2 as douyin__video__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+Protobufaweme_v2_feed_responseAdapter.proto\x1a\x19\x64ouyin_video_struct.proto\"\xb9\x06\n%Protobufaweme_v2_feed_responseAdapter\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x12\n\nmin_cursor\x18\x02 \x01(\x03\x12\x12\n\nmax_cursor\x18\x03 \x01(\x03\x12\x10\n\x08has_more\x18\x04 \x01(\x05\x12\x38\n\naweme_list\x18\x05 \x03(\x0b\x32$.douyin.ProtobufAwemeStructV2Adapter\x12\x0b\n\x03rid\x18\x06 \x01(\t\x12\x12\n\nhome_model\x18\x07 \x01(\x05\x12\x15\n\rrefresh_clear\x18\x08 \x01(\x05\x12\x33\n\x05\x65xtra\x18\t \x01(\x0b\x32$.douyin.ProtobufExtraStructV2Adapter\x12\x34\n\x06log_pb\x18\n \x01(\x0b\x32$.douyin.ProtobufLogPbStructV2Adapter\x12\x11\n\tDebugInfo\x18\x0b \x01(\t\x12\x36\n\nguide_word\x18\x0c \x01(\x0b\x32\".douyin.ProtobufGuideWordV2Adapter\x12\x39\n\x0bpreload_ads\x18\r \x03(\x0b\x32$.douyin.ProtobufAwemeStructV2Adapter\x12\x12\n\nstatus_msg\x18\x0e \x01(\t\x12\x12\n\nblock_code\x18\x0f \x01(\x05\x12<\n\x0epreload_awemes\x18\x10 \x03(\x0b\x32$.douyin.ProtobufAwemeStructV2Adapter\x12\x16\n\x0e\x65nable_re_rank\x18\x11 \x01(\x08\x12 \n\x18\x64isable_adjust_for_cache\x18\x12 \x01(\x08\x12\x13\n\x0bpitaya_type\x18\x13 \x01(\x05\x12\x17\n\x0fpitaya_features\x18\x14 \x01(\t\x12\x1a\n\x12\x65nable_splash_show\x18\x15 \x01(\x08\x12\"\n\x1a\x65nable_client_ads_strategy\x18\x16 \x01(\x08\x12\x1d\n\x15rec_follow_unread_cnt\x18\x17 \x01(\x05\x12\x1d\n\x15sati_param_for_pitaya\x18\x18 \x01(\t\x12\x12\n\nextra_info\x18\x19 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobufaweme_v2_feed_responseAdapter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOBUFAWEME_V2_FEED_RESPONSEADAPTER._serialized_start=75
  _PROTOBUFAWEME_V2_FEED_RESPONSEADAPTER._serialized_end=900
# @@protoc_insertion_point(module_scope)
