package com.bytedance.android.live.liveinteract.api.fulllink;

import com.bytedance.android.live.core.monitor.LiveTracingMonitor;
import com.bytedance.covode.number.Covode;
import com.bytedance.hotfix.PatchProxy;
import com.bytedance.hotfix.PatchProxyResult;
import com.bytedance.hotfix.base.ChangeQuickRedirect;

/* loaded from: classes3.dex */
public enum LinkMonitorData {
    StartInit("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_init_v2", true, true, false),
    Init("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "init_v2", true, true, false),
    StartInviteAudience("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_invite", true, true, false),
    InviteAudience("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "invite", true, true, false),
    StartReply("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_reply", true, true, false),
    Reply("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "reply", true, true, false),
    StartJoinChannel("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_join_channel", true, true, false),
    JoinChannel("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "join_channel", true, true, false),
    StartPermit("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_permit", true, true, false),
    Permit("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "permit", true, true, false),
    StartApply("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_apply", true, true, false),
    Apply("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "apply", true, true, false),
    StartUpdateLinkType("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_update_link_type", true, true, false),
    UpdateLinkType("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "update_link_type", true, true, false),
    StartSendSignaling("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_send_signaling", true, true, false),
    SendSignaling("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "send_signaling", true, true, false),
    StartSilence("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_silence", true, true, false),
    Silence("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "silence", true, true, false),
    StartUnSilence("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_unsilence", true, true, false),
    UnSilence("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "unsilence", true, true, false),
    StartKickOut("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_kick_out", true, true, false),
    KickOut("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "kick_out", true, true, false),
    StartLeave("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_leave", true, true, false),
    Leave("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "leave", true, true, false),
    StartCheckLinkers("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_check_linkers", true, false, false),
    CheckLinkers("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "check_linkers", true, false, false),
    StartListV2("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_list_v2", true, true, false),
    ListV2("ttlive_interact_link_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "list_v2", true, true, false),
    InviteMessage("ttlive_interact_link_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "invite_audience", true, true, false),
    PermitMessage("ttlive_interact_link_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "permit", true, true, false),
    ReplyMessage("ttlive_interact_link_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "reply", true, true, false),
    WaitingListMessage("ttlive_interact_link_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "waiting_list_changed", true, true, false),
    AdminFirstInviteMessage("ttlive_interact_link_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "admin_first_invite", true, true, false),
    CheckLinkPermission("ttlive_interact_link_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "check_link_permission", true, true, false),
    CreateLiveClient("ttlive_interact_link_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_live_client", true, true, false),
    InviteLinkSuccess("ttlive_interact_link_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "invite_link_success", true, true, false),
    ApplyLinkSuccess("ttlive_interact_link_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "apply_link_success", true, true, false),
    ReplyLinkSuccess("ttlive_interact_link_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "reply_link_success", true, true, false),
    StartRtc("ttlive_interact_link_sdk_api_call", LiveTracingMonitor.EventType.SDK_INTERFACE_CALL, "start_rtc", true, true, false),
    StartForwardRoom("ttlive_interact_link_sdk_api_call", LiveTracingMonitor.EventType.SDK_INTERFACE_CALL, "start_forward_room", true, true, false),
    LiveCoreVideoCaptureStarted("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "livecore_video_capture_started", true, true, false),
    LiveCoreVideoCaptureFirstFrame("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "livecore_video_capture_first_frame", true, true, false),
    LiveCoreVideoCaptureFailed("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "livecore_video_capture_failed", true, true, false),
    LiveCoreAudioCaptureStarted("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "livecore_audio_capture_started", true, true, false),
    LiveCoreAudioCaptureFailed("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "livecore_audio_capture_failed", true, true, false),
    RTCUserJoined("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_user_joined", true, true, false),
    RTCUserLeaved("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_user_leaved", true, true, false),
    RTCStartSuccess("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_start_success", true, true, false),
    RTCStartFailed("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_start_failed", true, true, false),
    RTCFirstVideoFrame("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_first_remote_video_frame", true, true, false),
    RTCFirstAudioFrame("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_first_remote_audio_frame", true, true, false),
    RTCFirstVideoFrameRender("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_first_remote_video_frame_render", true, true, false),
    RTCError("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_error", true, true, false),
    RTCForwardRoomSuccess("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_forward_room_success", true, true, false),
    RTCForwardRoomFailed("ttlive_interact_link_sdk_callback", LiveTracingMonitor.EventType.SDK_CALLBACK, "rtc_forward_room_failed", true, true, false),
    OpenChatRoomActionMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "open_chat_room_action", true, false, true, 16),
    AnchorPreCheckActionMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "precheck_before_open_chat_room", true, false, true, 16),
    InteractListApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/interact_list/", true, false, true, 16),
    TurnOnMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "turn_on_msg", true, false, true, 16),
    LinkUIReadyMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "link_ui_ready", true, true, true),
    LinkPermissionCheckMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "check_for_link", true, false, true, 16),
    InviteApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/invite/", true, false, true, 16),
    ReceiveInviteMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "invite_msg", true, false, true, 16),
    ReplyApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/reply/", true, false, true, 16),
    ReceiveReplyMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "reply_msg", true, false, true, 16),
    ApplyApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/apply/", true, false, true, 16),
    PermitApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/permit/", true, false, true, 16),
    ReceivePermitMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "permit_msg", true, false, true, 16),
    JoinChannelApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/join_channel/", true, false, true, 16),
    KickOutApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/kick_out/", true, false, true, 16),
    GuestDisconnectActionMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "guest_disconnect", true, false, true, 16),
    FinishApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/finish/", true, false, true, 16),
    SwitchSceneApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/switch_scene/", true, false, true, 16),
    ReceiveSwitchSceneMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "switch_scene_msg", true, false, true, 16),
    SwitchSceneActionMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "switch_ui_layout", true, false, true, 16),
    UpdateLinkTypeApplyApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/update_link_type/apply/", true, false, true, 16),
    ReceiveUpdateLinkTypeApplyMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "update_link_type_apply_msg", true, false, true, 16),
    UpdateLinkTypeReplyApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/update_link_type/reply/", true, false, true, 16),
    ReceiveUpdateLinkTypeReplyMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "update_link_type_reply_msg", true, false, true, 16),
    SendSignalingApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/send_signaling/", true, false, true, 16),
    ListEmojisApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/list_emojis/", true, false, true, 16),
    SendEmojiApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/send_emoji/", true, false, true, 16),
    UpdatePositionApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/update_position/", true, false, true, 16),
    LockPositionApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/lock_position/", true, false, true, 16),
    SetPositionAttributeApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/set_position_attribute/", true, false, true, 16),
    ReceivePositionAttrMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "position_attribute_msg", true, false, true, 16),
    EnlargeInviteApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/enlarge_guest/invite/", true, false, true, 16),
    ReceiveEnlargeInviteMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "enlarge_guest_invite_msg", true, false, true, 16),
    EnlargeReplyApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/enlarge_guest/reply/", true, false, true, 16),
    ReceiveEnlargeReplyMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "enlarge_guest_reply_msg", true, false, true, 16),
    SelfDisciplineConfigApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/self_discipline_config/", true, false, true, 16),
    ReceiveSelfDisciplineMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "self_discipline_msg", true, false, true, 16),
    FastMatchActionMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "fast_match_action", true, false, true, 16),
    FastMatchApiMonitorData("ttlive_chat_room_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "/linkmic_audience/fast_match/", true, false, true, 16),
    FastMatchJumpMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "fast_match_jump", true, false, true, 16),
    ReceiveBigEventMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "big_event_msg", true, false, true, 16),
    WRDSForMsgMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "get_user_list_from_wrds", true, false, true, 16),
    WRDSForApiMonitorData("ttlive_chat_room_business_logic", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "get_user_list_from_wrds", true, false, true, 16),
    BannerMsgMonitorData("ttlive_chat_room_im_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "banner_msg", true, false, true, 16),
    StartCreateTeamFight("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "start_create_team_fight", true, true, true),
    CreateTeamFightPreCheck("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_team_fight_pre_check", true, true, true),
    TeamFightLayoutReady("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "team_fight_layout_ready", true, true, true),
    CreateTeamFightRequest("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "create_teamfight", true, true, true),
    CreateTeamFightSuccess("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_team_fight_success", true, true, true),
    StartTeamFight("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_teamfight", true, true, true),
    FinishTeamFight("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "finish_teamfight", true, true, true),
    TeamFightInfo("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "teamfight_info", true, true, true),
    StartCreateGuestBattle("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "start_create_guest_battle", true, true, true),
    CreateGuestBattlePreCheck("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_guest_battle_pre_check", true, true, true),
    CreateGuestBattleRequest("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "open_guest_battle", true, true, true),
    CreateGuestBattleSuccess("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_guest_battle_success", true, true, true),
    PauseGuestBattleRequest("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "pause_guest_battle", true, true, true),
    ResumeGuestBattleRequest("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "resume_guest_battle", true, true, true),
    FinishGuestBattleRequest("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "finish_guest_battle", true, true, true),
    StartCreateRoomBattle("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "start_create_room_battle", true, true, true),
    CreateRoomBattlePreCheck("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_room_battle_pre_check", true, true, true),
    InviteCrossRoomLink("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "invite_cross_room_link", true, true, true),
    ReceiveCrossRoomInvite("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_cross_room_link_invite", true, true, true),
    ReplyCrossRoomLink("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "reply_cross_room_link", true, true, true),
    SelectGuest("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "select_guests", true, true, true),
    TimeOutFinish("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "room_battle_time_out_finish", true, true, true),
    ReceiveReply("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_cross_room_link_reply", true, true, true),
    CancelInvite("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "cancel_invite_cross_room_link", true, true, true),
    ReceiveRoomBattleStart("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_room_battle_start", true, true, true),
    LayoutReady("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "room_battle_layout_ready", true, true, true),
    CreateRoomBattleSuccess("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "create_room_battle_success", true, true, true),
    RoomBattleFinished("ttlive_multi_revenue_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "room_battle_finished", true, true, true),
    InviteRoomBattleAgain("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "invite_room_battle", true, true, true),
    ReceiveInviteAgain("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_profit_room_battle_invite", true, true, true),
    ReplyRoomBattleAgain("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "reply_room_battle", true, true, true),
    ReceiveReplyAgain("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_profit_room_battle_reply", true, true, true),
    CreateRoomBattle("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "create_room_battle", true, true, true),
    SilenceOtherRoom("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "silence_other_room", true, true, true),
    ReceiveCrossRoomSilence("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_cross_room_update_message", true, true, true),
    FinishRoomBattle("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "finish_room_battle", true, true, true),
    ReceiveRoomBattleFinished("ttlive_multi_revenue_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "receive_room_battle_finish", true, true, true),
    FetchInviteList("ttlive_multi_revenue_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "invite_cross_room_link_list", true, true, true),
    ApiUpdateSingerState("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "update_singer_state", false, false, false, 56),
    ApiKtvListActivityStatus("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "ktv_list_activity_status", false, false, false, 56),
    ApiAddSongStatusForRebroadcast("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "add_song_status_for_rebroadcast", false, false, false, 56),
    ApiGetAnchorAudioBg("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_anchor_audio_bg", false, false, false, 56),
    ApiGetUserFollowRelation("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_user_follow_relation", false, false, false, 56),
    ApiStartSing("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_sing", false, false, false, 56),
    ApiFinishSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "finish_song", false, false, false, 56),
    ApiGetLinkmicGroupUser("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_linkmic_group_user", false, false, false, 56),
    ApiGetAudienceSettings("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_audience_settings", false, false, false, 56),
    ApiGetGroupInfo("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_group_info", false, false, false, 56),
    ApiGroupInvite("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "group_invite", false, false, false, 56),
    ApiCreateShortvideo("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "create_shortvideo", false, false, false, 56),
    ApiGetAtmosphereResource("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_atmosphere_resource", false, false, false, 56),
    ApiGetUserSongContributorRank("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_user_song_contributor_rank", false, false, false, 56),
    ApiGetUserWeeklyHotRankPos("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_user_weekly_hot_rank_pos", false, false, false, 56),
    ApiFetchPreviewSongs("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "fetch_preview_songs", false, false, false, 56),
    ApiSingingChallengeRankNotice("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "singing_challenge_rank_notice", false, false, false, 56),
    ApiGetSingingHotResult("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_singing_hot_result", false, false, false, 56),
    ApiAddSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "add_song", false, false, false, 56),
    ApiGetOrderedSongList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_ordered_song_list", false, false, false, 56),
    ApiPinSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "pin_song", false, false, false, 56),
    ApiRemoveSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "remove_song", false, false, false, 56),
    ApiPausePlayMusic("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "pause_play_music", false, false, false, 56),
    ApiGetArtistSongList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_artist_song_list", false, false, false, 56),
    ApiGetArtistList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_artist_list", false, false, false, 56),
    ApiGetAudienceRecommendList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_audience_recommend_list", false, false, false, 56),
    ApiGetInteractiveOrderedSongList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_interactive_ordered_song_list", false, false, false, 56),
    ApiCheckOrderedSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "check_ordered_song", false, false, false, 56),
    ApiGetRecommendList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_recommend_list", false, false, false, 56),
    ApiSearchSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "search_song", false, false, false, 56),
    ApiGetHotWords("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_hot_words", false, false, false, 56),
    ApiGetSearchSug("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_search_sug", false, false, false, 56),
    ApiChooseSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "choose_song", false, false, false, 56),
    ApiAddFavorite("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "add_favorite", false, false, false, 56),
    ApiDelFavorite("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "del_favorite", false, false, false, 56),
    ApiGetTuningInfo("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_tuning_info", false, false, false, 56),
    ApiSwitchKtvMode("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "switch_ktv_mode", false, false, false, 56),
    ApiGetAnchorRecommendList("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_anchor_recommend_list", false, false, false, 56),
    ApiGetPlaylistDetail("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_playlist_detail", false, false, false, 56),
    ApiInteractivePinSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "interactive_pin_song", false, false, false, 56),
    ApiInteractiveRemoveSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "interactive_remove_song", false, false, false, 56),
    ApiInteractiveAddSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "interactive_add_song", false, false, false, 56),
    ApiGetInteractiveSettingDetail("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_interactive_setting_detail", false, false, false, 56),
    ApiSetInteractiveFreeOrderSong("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "set_interactive_free_order_song", false, false, false, 56),
    ApiGetSingingChallengeOption("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_singing_challenge_option", false, false, false, 56),
    ApiSingingChallengeConfigChangedNotice("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "singing_challenge_config_changed_notice", false, false, false, 56),
    ApiStartSingingChallengeNotice("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "start_singing_challenge_notice", false, false, false, 56),
    ApiGetSingingChallengeStatus("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_singing_challenge_status", false, false, false, 56),
    ApiGetPriorSongGiftConfig("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "get_prior_song_gift_config", false, false, false, 56),
    ApiUpdatePriorSongGiftConfig("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "update_prior_song_gift_config", false, false, false, 56),
    ApiPriorSongGiftBoard("ttlive_ktv_server_api_call", LiveTracingMonitor.EventType.SERVER_API_CALL, "prior_song_gift_board", false, false, false, 56),
    MsgLinkmicAudienceKtvMessage("ttlive_ktv_server_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "linkmic_audience_ktv_message", false, false, false, 56),
    MsgKtvPlaymodeStartMessage("ttlive_ktv_server_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "ktv_playmode_start_message", false, false, false, 56),
    MsgKtvMessage("ttlive_ktv_server_message_received", LiveTracingMonitor.EventType.MESSAGE_RECEIVED, "ktv_message", false, false, false, 56),
    BusinessLyricsParseStatusSuccess("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "lyrics_parse_status_success", false, false, false, 56),
    BusinessLyricsParseStatusFail("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "lyrics_parse_status_fail", false, false, false, 56),
    BusinessMusicStartSing("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "start_sing", false, false, false, 56),
    BusinessMusicFinishSing("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "finish_sing", false, false, false, 56),
    BusinessMusicDownloadStatusSuccess("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "music_download_status_success", false, false, false, 56),
    BusinessMusicDownloadStatusFail("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "music_download_status_fail", false, false, false, 56),
    BusinessMusicInfoStatus("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "music_info_status", false, false, false, 56),
    BusinessMidiStatus("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "midi_status", false, false, false, 56),
    BusinessKtvRoomLiveStreamStatus("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "ktv_room_live_stream_status", false, false, false, 56),
    BusinessPlayMusicSetBgmMusic("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "play_music_set_bgm_music", false, false, false, 56),
    BusinessPlayMusicPlayFailed("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "play_music_play_failed", false, false, false, 56),
    BusinessPlayerStopCalled("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "player_stop_called", false, false, false, 56),
    BusinessLyricsRender("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "lyrics_render", false, false, false, 56),
    BusinessSeiFail("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "sei_fail", false, false, false, 56),
    BusinessChooseSongPath("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "choose_song_path", false, false, false, 56),
    BusinessAudioFilterManagerNull("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "audio_filter_manager_null", false, false, false, 56),
    BusinessSetBgmFailed("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "set_bgm_failed", false, false, false, 56),
    BusinessDurationHugeGap("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "duration_huge_gap", false, false, false, 56),
    BusinessAVPlayerError("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "AVPlayer_error", false, false, false, 56),
    BusinessFirstFrameTime("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "first_frame_time", false, false, false, 56),
    BusinessEchoSdkInitSuccess("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "echo_sdk_init_success", false, false, false, 56),
    BusinessEchoSdkInit("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "echo_sdk_init", false, false, false, 56),
    BusinessEchoSdkOpenSuccess("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "echo_sdk_open_success", false, false, false, 56),
    BusinessEchoSdkOpen("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "echo_sdk_open", false, false, false, 56),
    BusinessSeiUnusualFrequency("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "sei_unusual_frequency", false, false, false, 56),
    BusinessSeiReceiveFrequency("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "sei_receive_frequency", false, false, false, 56),
    BusinessSeiStateInvalid("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "state_invalid", false, false, false, 56),
    BusinessLyricsDownloadSuccess("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "lyrics_download_success", false, false, false, 56),
    BusinessLyricsDownloadFail("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "lyrics_download_fail", false, false, false, 56),
    BusinessLyricsShowInvalid("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "lyrics_show_invalid", false, false, false, 56),
    BusinessCutMusicPath("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "cut_music_path", false, false, false, 56),
    BusinessOpenPlayMode("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "open_play_mode", false, false, false, 56),
    BusinessClosePlayMode("ttlive_ktv_bussiness_api_call", LiveTracingMonitor.EventType.BUSSINESS_API_CALL, "close_play_mode", false, false, false, 56);
    
    public static ChangeQuickRedirect changeQuickRedirect;
    public final LiveTracingMonitor.EventType eventTypeKey;
    public final String eventTypeValue;
    public final boolean needLinkCommonParams;
    public final boolean needRoomCommonParams;
    public final boolean needTalkRoomCommonParams;
    public final String serviceName;

    public static LinkMonitorData valueOf(String str) {
        PatchProxyResult proxy = PatchProxy.proxy(new Object[]{str}, null, changeQuickRedirect, true, 2);
        return (LinkMonitorData) (proxy.isSupported ? proxy.result : Enum.valueOf(LinkMonitorData.class, str));
    }

    /* renamed from: values  reason: to resolve conflict with enum method */
    public static LinkMonitorData[] valuesCustom() {
        PatchProxyResult proxy = PatchProxy.proxy(new Object[0], null, changeQuickRedirect, true, 1);
        return (LinkMonitorData[]) (proxy.isSupported ? proxy.result : values().clone());
    }

    static {
        Covode.recordClassIndex(25168);
    }

    LinkMonitorData(String str, LiveTracingMonitor.EventType eventType, String str2, boolean z, boolean z2, boolean z3) {
        this.serviceName = str;
        this.eventTypeKey = eventType;
        this.eventTypeValue = str2;
        this.needRoomCommonParams = z;
        this.needLinkCommonParams = z2;
        this.needTalkRoomCommonParams = z3;
    }

    /* synthetic */ LinkMonitorData(String str, LiveTracingMonitor.EventType eventType, String str2, boolean z, boolean z2, boolean z3, int i) {
        this(str, eventType, str2, (i & 8) != 0 ? true : z, false, (i & 32) != 0 ? false : z3);
    }
}
