
const parser = require("@babel/parser");
const traverse = require("@babel/traverse").default;
const types = require("@babel/types");
const { count } = require("console");
const generator = require("@babel/generator").default;
const fs = require("fs");
// 需要解码的文件1位置
let encode_file = "decode_vm_0.js"
// 解码后的文件1位置
let decode_file = "decode_vm_1.js"
// 读取需要解码的js文件, 注意文件编码为utf-8格式
let jscode = fs.readFileSync(encode_file, { encoding: "utf-8" });
// 将js代码修转成AST语法树
let ast = parser.parse(jscode);

var _$N4 =  [
    "call",
    "slice",
    "prototype",
    "type",
    "href",
    "floor",
    "string",
    "tylctrlaz}",
    "concat",
    "createElement",
    "readyState",
    "$_fr",
    "button",
    "removeChild",
    "safari",
    "$_fpn1",
    "clientData",
    "localStorage",
    "stringify",
    "onsuccess",
    "location",
    "getElementById",
    "submit",
    "hidden",
    "setAttribute",
    "http:",
    "open",
    "HTMLFormElement",
    "target",
    "style",
    "documentElement",
    "round",
    "apply",
    "hostname",
    "hasOwnProperty",
    "$_f1",
    "onreadystatechange",
    "FSSBB",
    "innerHTML",
    "setTimeout",
    "cookie",
    "addEventListener",
    "$_JQnh",
    "clearInterval",
    "visibility",
    "send",
    "charCodeAt",
    "protocol",
    "userAgent",
    "host",
    "$_f0",
    "getElementsByTagName",
    "EkcP",
    "load",
    "https:",
    "ceil",
    "pathname",
    "data",
    "toString",
    "document",
    "$_fh0",
    "$_vvCI",
    "port",
    "appVersion",
    "splice",
    "MicroMessenger",
    "number",
    "search",
    "indexedDB",
    "getTime",
    "replace",
    "transaction",
    "match",
    "indexOf",
    "keydown",
    "keyCode",
    "name",
    "$_cDro",
    "Math",
    "Request",
    "script",
    "appendChild",
    "___ts___",
    "removeEventListener",
    "origin",
    "fonts",
    "getAttribute",
    "ActiveXObject",
    "result",
    "$b_callHandler",
    "input",
    "timeStamp",
    "canvas",
    "setInterval",
    "body",
    "XMLHttpRequest",
    "function",
    "getContext",
    "fromCharCode",
    "split",
    "isFinite",
    "chrome",
    "decodeURIComponent",
    "nDhzt|Gz~vUDhzt|Gz~v",
    "Object.InjectedScript.evaluate",
    "jbscheme://",
    "GetAllResponseHeaders",
    "Keyboard",
    "Msxml2.XMLHTTP",
    "width",
    "forEach",
    "precision",
    "fontList",
    "bpa_aqhcfd+paannjrgdke",
    "/T7AyTrxoWxGd",
    "getClientDataInCookie",
    "dumpAll",
    "[native code]",
    "]><i></i><![endif]-->",
    "utf-8",
    "FSSBA",
    "offsetX",
    "charging",
    "vertexPosArray",
    "{8iep<mhisH8iep<mhisBxqC [gxmzi> )srxvsp BMLGfmxC",
    "test",
    "x>,@li.a{I|j~li",
    "clientInformation",
    "onerror",
    "webkitRTCPeerConnection",
    "shenjian",
    "mozItems",
    "INSERT OR REPLACE INTO EkcP_t (name, value) VALUES(?, ?)",
    "onbeforeunload",
    "serverData",
    "tagName",
    "$b_onBridgeReady",
    "createBuffer",
    "x@liA65vn6zn_>72:>._",
    "b;naidbs hc<\"aa71ji\" bk~rrhc<\"bkrhc92/4/e708,87a4,00be,aa71,//~~//acbd/a\" vhcsg<\"/ow\" gdhfgs<\"/ow\"=;.naidbs=",
    "GetResponseHeader",
    "onupgradeneeded",
    "ckqFgbbcl",
    "status",
    "enable=true",
    "DispatchEvent",
    "PerformanceObserver",
    "touchend",
    "touches",
    "standalone",
    "HIGH_FLOAT",
    "setClientData",
    "responseText",
    "Msxml2.XMLHTTP.4.0",
    "parentElement",
    "ht\\lW\\Tgxmbo| zh{|\\]\\lWv",
    "charAt",
    "alpha",
    "CREATE TABLE IF NOT EXISTS EkcP_t (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name))",
    "Microsoft.XMLHTTP",
    "cookieEnabled",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj.7zXBaSnu0TC6gy_4Ze5d{}|~ !#$%()*+,-;=?@[]^",
    "webstore",
    "fM~zgKgzt~m",
    "iz{nay{eglagf",
    "@debugger",
    "bindBuffer",
    "qfwcwpwzwdiqvo|us",
    "screenY",
    "(evaluating 'null[0]')",
    "__anchor__",
    "mouseOver",
    "Gamepad",
    "Msxml2.XMLHTTP.5.0",
    "bb82kj",
    "createShader",
    "loaded",
    "x__:=9__1884_78=2/2.;",
    "none",
    "TRIANGLE_STRIP",
    "rzb2arqr{cvnyb",
    " height=6 width=1 type=application/x-shockwave-flash src=",
    "ARSession,AudioTrackList,BeforeInstallPromptEvent.prototype.KEYUP,BlobDownloadCallback,CDATASection.prototype.remove,CSSCharsetRule,CSSPrimitiveValue.CSS_VH,CanvasRenderingContext2D.prototype.webkitGetImageDataHD,ClickData,CloseEvent.prototype.initCloseEvent,Components.interfaces.ICometMarksExtension,DeviceOrientationEvent,Function.prototype.bind,GetPerfTests,HTMLDocument.prototype.createTouchList,HTMLFormElement.prototype.requestAutocomplete,HTMLFrameSetElement.prototype.hasPointerCapture,HTMLFrameSetElement.prototype.webkitRequestFullScreen,Intl,MTT_WKSetTextSizeIndex,MediaController,MediaEncryptedEvent,Notification,Object.prototype.__defineSetter__,Object.seal,Object.setPrototypeOf,OffscreenCanvasRenderingContext2D,Path2D.prototype.addPath,PaymentResponse,PerformancePaintTiming,PresentationConnectionCloseEvent,ReaderModeArticlePage,SVGGraphicsElement.prototype.mozRequestPointerLock,SVGPatternElement.SVG_UNIT_TYPE_OBJECTBOUNDINGBOX,ScreenOrientation,SogouLoginUtils,SourceBuffer,SourceBuffer.prototype.changeType,SpeechSynthesisUtterance,TextTrackList.prototype.getTrackById,UCWebExt,WebKitFlags,_WXJS,__$_qihoo360_$__,__firefox__,__ksabCssCount,__opera,__sogou_secure_input,_double11_,chrome,chrome.app.InstallState,chrome.csi,console,defaultStatus,document.body.onmouseenter,document.body.onpage,document.body.style.backgroundBlendMode,document.body.style.lineBreak,document.body.style.minWidth,document.body.style.msTextSizeAdjust,document.body.style.textAlignLast,document.body.x-ms-acceleratorkey,document.defaultCharset,document.documentElement.onresize,document.fileCreatedDate,document.msCapsLockWarningOff,document.onmousemove,document.onselectionchange,document.scrollingElement.style.fontVariantNumeric,document.selection,document.selection.typeDetail,external,external.AddFavorite,external.IsSearchProviderInstalled,flyflow_wallpaper_js,getMatchedCSSRules,greentea,isNodeWhitespace,jesion,onerror,onmessage,onoperadetachedviewchange,openDatabase,password_manager_enabled,performance,showModalDialog,taobrowser_Event,weatherBridge,webkitAudioContext.prototype.close,webkitRequestFileSystem",
    "t~{t_szzvpoMxzg.ytxlatzy@al}aAtxpMxzg6yopepo1/Mxzg?p|bp~a.ytxlatzy3}lxp",
    "Msxml2.XMLHTTP.3.0",
    "getSources",
    "post",
    "mouseUp",
    "v>n8xk1ruu1x{v?xxuK>xpx~8|n",
    "FileReader",
    "msIndexedDB",
    "method",
    "readwrite",
    "bvdacqhudq",
    "parse",
    "t:zg.{{pl}lynp",
    "$_vJTp",
    "lineno",
    "data:",
    "charset",
    "rgba(240,110,53,0.4)",
    "Number",
    "DeviceMotionEvent",
    "mouseup",
    "Please enable cookie in your browser before you continue.",
    "mousedown",
    "windows-1252",
    "sessionStorage",
    "hzxeeIaxgmhfY_iaxgmhf",
    "onicecandidate",
    "content",
    "mimeTypes",
    "OPEN",
    "unicode",
    "null",
    "LOW_FLOAT",
    "n~bm;zuuva",
    "mGzcu}ksjw:~sgzVGzcu}ksjw:~sgz",
    "0000",
    "performance",
    "clientX",
    "useProgram",
    "beta",
    "touchmove",
    "sA{s{c",
    "h__fmm<k|xm|?kxf|Yfmm<nflmhfCL",
    "fillStyle",
    "cellular",
    "onload",
    "include",
    "linkProgram",
    "DeviceOrientationEvent",
    "parseInt",
    "jbscheme://queue_has_message",
    "toDataURL",
    "SEND",
    "escape",
    "addBehavior",
    "acceleration",
    "callback",
    "~snpdyE5fbm3mbzfs *I Zpouspm",
    "STATIC_DRAW",
    "Msxml2.XMLHTTP.6.0",
    "; expires=",
    "close",
    "getSupportedExtensions",
    "experimental-webgl",
    "getAllResponseHeaders",
    "#f82",
    "fillRect",
    "openDatabase",
    "meta",
    "eval",
    "$_YWTU",
    "y}khjxo|kxIk|gr{gzk",
    "<EMBED id=",
    "; Secure",
    "mouseMove",
    "toUpperCase",
    "([0-9]{1,3}(\\.[0-9]{1,3}){3}| (([0-9a-f]{1,4}:){7,7}[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,7}:|([0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}|([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}|([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}|([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:((:[0-9a-f]{1,4}){1,6})|:((:[0-9a-f]{1,4}){1,7}|:)|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])) )",
    "createOffer",
    "unescape",
    "nEvr}C}rlveUEvr}C}rlveOg~P 4tgzivK 6bageb} OZYTszgP",
    "{[gvs6*,H6*,",
    "{ettpmgexmsrI|Gwlsgo{eziGjpewl",
    "base",
    "dispatchEvent",
    "setRequestHeader",
    "z__iwn{jw_j{fqzfyjG__|jgiwn{jw_j{fqzfyjG__xjqjsnzr_j{fqzfyjG__k}iwn{jw_j{fqzfyjG__iwn{jw_zs|wfuujiG__|jgiwn{jw_zs|wfuujiG__xjqjsnzr_zs|wfuujiG__k}iwn{jw_zs|wfuujiG__|jgiwn{jw_xhwnuy_kzshG__|jgiwn{jw_xhwnuy_ks",
    "offsetWidth",
    "DOMParser",
    "TEMPORARY",
    "filename",
    "attrVertex",
    "Infinity",
    "languages",
    "responseBody",
    "exec",
    "accelerationIncludingGravity",
    "18px 'Arial'",
    "AddEventListener",
    "Z8XHJJY.bmF0aXZlRmlVyUHJ()",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "Msxml2.ServerXMLHTTP",
    "\\\\",
    "substring",
    "getResponseHeader",
    "toLowerCase",
    "clientY",
    "webgl",
    "value",
    "enumerateDevices",
    "uniformOffset",
    "mouseover",
    "; path=/",
    "screenX",
    "mousemove",
    "func",
    "createProgram",
    "use strict",
    "wifi",
    "bluetooth",
    "object",
    "LOW_INT",
    "hash",
    "itemSize",
    "setItem",
    "g__q}z|lcp}l_}pyfoyn}",
    "getUniformLocation",
    "g|lcp}l[}pyfoyn}",
    "acos",
    "RemoveEventListener",
    "webkitIndexedDB",
    "$bmF0aXZlRmlVyUHJ",
    "save",
    "msCrypto",
    "POST",
    "wimax",
    " host ",
    "detachEvent",
    "arity",
    "Microsoft.XMLHTTP.1.0",
    "g|lcp}l",
    "screen",
    "getAttribLocation",
    "trim",
    "rangeMin",
    "PerformanceObserverEntryList",
    "|ks_lghqwlilhu",
    "candidate",
    "Msxml.XMLHTTP",
    "hLdri|[=|m|zmbhg",
    "getParameter",
    "chargingTime",
    "s__ru~qr{f__N_ru~qr{f_@qmpq~;{pq",
    "}ygdmkvxkukdknkv{ejcpig",
    "mouseOut",
    "PointerEvent",
    "Msxml2.ServerXMLHTTP.4.0",
    "setServerData",
    "OverrideMimeType",
    "Msxml2.ServerXMLHTTP.3.0",
    "mouseDown",
    "description",
    "xul{zwhyrlyI__uzI__uz*wwluk=la{Ilv@li+yv~zly",
    "a=candidate:",
    "uwyfbs}slsvs~emrkxqo",
    "android",
    "responseXML",
    "}__ygdftkxgt_uetkrv_hp",
    "mediaDevices",
    "|^\\$@dF}]gf_",
    "showModalDialog",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "scroll",
    "ethernet",
    "$_fb",
    "webkitRequestFileSystem",
    "\u0000",
    "i{pal>mddkyj{{f",
    "credentials",
    "q ?@BS",
    "[object Array]",
    "(near '... null[0]...')",
    "MediaStreamTrack",
    "error",
    "rows",
    "keyDown",
    "http://",
    "children",
    "z:>*yqI:>*yq",
    "message",
    " srflx ",
    "Open",
    "/:user_fonts",
    "f__|mR~{[__b>mR~{",
    "font",
    "orientation",
    "MEDIUM_INT",
    "Function",
    "HIGH_INT",
    "unload",
    "deviceId",
    "action",
    "HTMLAnchorElement",
    "lgbdvmWGxtaEatnxg <[ 8dcigdaWZ",
    "Count",
    "zxjqjsnzrHj{fqzfyj",
    "gamma",
    "FRAGMENT_SHADER",
    "b~ooRb~mBkhbj+~ooRb~mEnbtrNts+~ooRb~mJdxCnvm+~ooRb~mJdxTo",
    "GetOriginalUrl",
    "vdFm",
    "response",
    "createObjectStore",
    "offsetUniform",
    "toGMTString",
    "getTimezoneOffset",
    "$b_platform",
    "?CS=",
    "keyUp",
    "captureStackTrace",
    "undefined",
    "enabledPlugin",
    "parentNode",
    "Send",
    "height",
    "Z8XHj",
    "lastIndexOf",
    "Msxml2.ServerXMLHTTP.6.0",
    "javascript:",
    "mozConnection",
    "dblclick",
    "Mouse",
    "getExtension",
    "lLBEatnxgWD8M",
    "RegExp",
    "mozRTCPeerConnection",
    "GetVariable",
    "attachShader",
    "QTP_EPE_HOOK",
    "SELECT value FROM EkcP_t WHERE name=?",
    "display",
    "webkitPersistentStorage",
    "alert",
    "FLOAT",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj-7zXBaSnu0TC6gy_4Ze5d~!@$%^&*()+=<>.?/:;{}[]| ",
    "GetNextReqID",
    "stack",
    "y.g|k1iut2g|g1tzkxlgikHpkyout",
    "JSON",
    "$_ts",
    "setTime",
    "ARRAY_BUFFER",
    "z7+-I7ik*ywq",
    "plugins",
    "getServerDataInCookie",
    "position",
    "fontFamily",
    "iframe",
    "colorDepth",
    "attachEvent",
    "return a[b](",
    "b_Rdkdmhtl_HCD_Qdbnqcdq+_rdkdmhtl+b~kkRdkdmhtl",
    "setLocalDescription",
    "}ugngpkwo",
    "objectStoreNames",
    "then",
    "q46@vszfsdwqo+Dwpsdo| =oqvw|s E|w+3}}zxojj+Fsbro|o+8szfsdwqo >ses <D @b} WY Dvw|+dov}{o+<7 C{obd_8 dscd Bsuezob+49>@b}Qzwuvd+8szfsdwqo <D XW <wuvd 5hds|rsr+8szfs=_9|rwo+C53B}p}d}<wuvd 2}zr+?B =}vo|di E|wq}rs Bsuezob+4b}wr Co|c Dvow+;o||oro Co|uo{ =>+443 Eqvs|+qz}qyVTUZ_fURU+Co{ce|u;o||oroBsuezob+=9 <1>D9>7 2}zr+Co{ce|uCo|c>e{W< <wuvd+fsbro|o+8szfsdwqo>sesDvw|+C536ozzpoqy+Co{ce|u5{}xw+Dszeue Co|uo{ =>+3obb}wc 7}dvwq C3+6zi{s <wuvd B}p}d} <wuvd+C}=1Q4wuwd <wuvd+C}=3 Co|c Bsuezob+8IHwIeo|:+ccd+co{ce|uQco|cQ|e{XD+u{_{s|u{s|u+<}vwd ;o||oro+dw{sc |sg b}{o|+co{ce|uQco|cQ|e{X<+csbwtQ{}|}c~oqs+Co{ce|uCo|c>e{QWD Dvw|+3}z}b?CE9QHDvw|+4b}wr >ocyv Cvwtd 1zd+Co{ce|uDszeueBsuezob+2s|uozw ?DC+=9 <o|Dw|u_72 ?edcwrs IC+6J=wo}Ge_72U(TWT+vszfsQ|sesQbsuezob+CCD =srwe{+3}ebwsb >sg+;v{sb =}|rezywbw 2}zr+8szfsdwqo <D VW Ezdbo <wuvd 5hds|rsr+8szfsdwqo <D VY Ezdbo <wuvd+B}p}d} =srwe{+4b}wr Co|c 2}zr+u}eri+co|cQcsbwtQq}|rs|csrQzwuvd+C6w|rsb+|}d}Qco|cQqxyQ{srwe{+{wew+=B}qyi @B3 2}zr+1|rb}wr3z}qy Bsuezob+Co{ce|uCo|c>e{QX< <wuvd+co|cQcsbwtQdvw|+1o@o|uIosb+qoceoz+2> =}vo|di?D 2}zr+hQccd+>}d}Co|c=io|{obJoguiw+8szfsdwqo <D WW Dvw| 5hds|rsr+1cvzsiCqbw~d=D 1zd+>}d} Co|c 4sfo|ouobw E9+B}p}d} 3}|rs|csr 2}zr+B}p}d} =srwe{ 9dozwq+{wewsh+>}d} Co|c 7eb{eyvw E9+CCD Fwsd|o{scs <wuvd+<7_?bwio+viq}ttss+hQccdQezdbozwuvd+468sw1G[Q1+6JJGH2D?D_E|wq}rs+4sfo|ouobw Co|uo{ => 2}zr+co|cQcsbwtQ{}|}c~oqs+@oroey 2}}y 2}zr+<7Q6JIw|u2w;owCveQCUYQFVRV+<7Q6JIw|u2w;owCveQCUYQFVRW+8szfsdwqo>ses<D @b} WY Dv+=wqb}c}td 8w{ozoio+Co{ce|uCo|c6ozzpoqy+CCD =srwe{ 9dozwq+1|rb}wr5{}xw+Co{ce|uCo|c>e{QWB+9D3 Cd}|s Csbwt+co|cQcsbwtQc{ozzqo~c+hQccdQ{srwe{+<7_Cw|vozscs+B}p}d} Dvw| 9dozwq+qs|debiQu}dvwq+3z}qy}~wo+<e{w|}ec_Co|c+6z}bwrwo| Cqbw~d 1zd+>}d} Co|c 7eb{eyvw 2}zr+<D8ICJ; 2}zr+7C_Dvow+Co{ce|u>s}>e{_WD_V+1bopwq+vo|cQco|cQ|}b{oz+<}vwd Dszeue+8IAw8swQYTC <wuvd+<w|rcsi t}b Co{ce|u+1B 3bicdozvsw 42+Co{ce|u Co|c =srwe{+co{ce|uQco|cQ|e{XY+vo|cQco|cQp}zr+<e{w|}ec_Cqbw~d+CCD 3}|rs|csr+Co{ce|u4sfo|ouobwBsuezob+1|xoz =ozoiozo{ =>+Co{ce|uDvowLdscdM+6J<o|Dw|u8swQ=Q72U(TWT+8spbsg ?DC+7CXY_1bopL1|rb}wr?CM+Co{ce|u Co|c <wuvd+3v}q} q}}yi+vszfsQ|sesQdvw|+@> =}vo|di?D =srwe{+<7Q6J;oD}|uQ=U)QFVRX+4b}wr Csbwt+Co{ce|uCw|vozoBsuezob+vszfsdwqo+<7Q6J;oD}|uQ=U)QFVRV+>}d} Co|c 4sfo|ouobw E9 2}zr+CCD <wuvd+46@5{}xw+gsodvsbt}|d|sg Bsuezob+B}p}d}>e{WB+49>@b}Q{srwe{+Co{ce|u Co|c >e{YY+CCD 8sofi 9dozwq+<7z}qyX Bsuezob_T(TY+7s}buwo+|}d}Qco|cQqxy+Dszeue Co|uo{ => 2}zr+=9E9 5H >}b{oz+8IAw8swQ[YC 2}zr+>}d}Co|c=io|{obJoguiw 2}zr+ie|}c~b}Qpzoqy+vszfsQ|sesQ|}b{oz+<e{w|}ec_Csbwt+D= =}vo|di?D >}b{oz+Co{ce|uCo|c>e{QW<f <wuvd+Co{ce|u Co|c >e{XY+C{obd7}dvwq =srwe{+us}buwo+qoceozQt}|dQdi~s+Co{ce|u Co|c 2}zr+c{ozzQqo~wdozc+=6w|o|qs @B3 2}zr+6J<o|Dw|u8sw_72U(TWT+Co{ce|u1b{s|wo|+B}p}d} 2}zr+qs|debiQu}dvwqQp}zr+hQccdQvsofi+CCD <wuvd 9dozwq+Dvob<}|+hQccdQzwuvd+4w|p}z Bsuezob+Co{ce|u2s|uozwBsuezob+;> =}vo|di?DC{ozz =srwe{+vi~ebs+Co{ce|uDo{wzBsuezob+=ozoiozo{ Co|uo{ =>+>}d} Co|c ;o||oro E9+vszfsQ|ses+8szfsdwqo <D YY B}{o|+>}d} Co|c ;o||oro 2}zr+Co|~io+Co{ce|u@e|xopwBsuezob+co{ce|uQco|cQ|e{X<f+<7_;o||oro+Co{ce|u Co|c Bsuezob+JoguiwQ?|s+4b}wr Csbwt 2}zr 9dozwq+6J;1D:G+q}ebwsb |sg+Co{ce|u5{}xwBsuezob+=9E9 5H 2}zr+1|rb}wr 5{}xw+>}d} >ocyv 1bopwq E9+<34 3}{+6edebo =srwe{ 2D+Fwf}Qshdboqd+2o|uzo Co|uo{ => 2}zr+vo|cQco|cQbsuezob+C>e{QWB+C>e{QWD+vo|cQco|c+CCD Ezdbo <wuvd+B}p}d} Bsuezob+B}p}d} <wuvd+8o|e{o|+|sgzuu}dvwq+468sw1GYQ1+vo|cQco|cQzwuvd+@zods 7}dvwq+C>e{QW<+8szfsdwqo <D XY <wuvd+=io|{ob Co|uo{ Joguiw 2}zr+zuQco|cQcsbwtQzwuvd+=9E9 5H <wuvd+B}p}d} Dvw|+C}=1 2}zr+@oroey+Co{ce|u Co|c+C~oqw}ec_C{ozz3o~+co|cQcsbwt+4F =}vo|di?D =srwe{+Cdopzs_Czo~+{}|oq}+6zi{sQ<wuvd+tjjicQr}c~i+Cqbss|Co|c+qz}qyVTUZ+B}p}d} 3}|rs|csr 2}zr 9dozwq+1bwoz+;> =}vo|di =srwe{+=}d}io<=obe GW {}|}+8o|rcsd 3}|rs|csr+B}p}d} 9dozwq+8D3 8o|r+CCD Ezdbo <wuvd 9dozwq+CCD Fwsd|o{scs B}{o|+>}d} >ocyv 1bopwq E9 2}zr+qv|tjhvQ{srwe{+C>e{3}|rQWD+qs|debiQu}dvwqQbsuezob+rstoezd_b}p}d}Qzwuvd+>}d} Co|c =io|{ob+=io|{ob Co|uo{ =>+1~~zs 3}z}b 5{}xw+gsodvsbt}|dBsu+Co{ce|u=ozoiozo{Bsuezob+obwoz+4b}wr Csbwt 2}zr+3@}W @B3 2}zr+=9 <1>D9>7+Co{ce|u;}bso|QBsuezob+dscdXY Bsuezob+c~wbwd_dw{s+4sfo|ouobw Co|uo{ =>+Cqbss|Csbwt+B}p}d}+qebcwfsQt}|dQdi~s+CD8swdw_fwf}+qv|tjhv+Co{ce|u 3z}qy6}|d W1+B}p}d} 3}|rs|csr Bsuezob+co{ce|uQ|s}Q|e{WB+7: =}vo|di?D =srwe{+3vezv} >ses <}qy+b}p}d}Q|e{W<+vszfsQ|sesQezdbo<wuvdshds|rsr+Co{ce|u?bwioBsuezob+Co{ce|uCo|c>e{QX<f <wuvd+=Iw|u8sw_U(TWT_3VQ2}zr+46@Cvo}>fGYQ72+B}p}d} 2zoqy+vszfsQ|sesQezdbozwuvd+u{_hwvsw+<7z}qyX <wuvd_T(TY+7exobodw Co|uo{ =>+=ozoiozo{ Co|uo{ => 2}zr+b}p}d}Q|e{WB+CDHwvsw_fwf}+6JJve|Ieo|_72U(TWT+|}d}Qco|cQqxyQzwuvd+q}z}b}c+>}d} Co|c 7eb{eyvw+>}d} Co|c Ci{p}zc+B}p}d} <wuvd 9dozwq+<}vwd Do{wz+qebcwfs+rstoezd_b}p}d}+2vocvwdo3}{~zshCo|c 2}zr+<7_>e{psb_B}p}d} Dvw|+{}|}c~oqsrQgwdv}edQcsbwtc+8szfsdwqo <D WY Dvw|+co{ce|uQco|cQ|e{W<F+49>@b}+:}{}zvobw+co|cQcsbwtQzwuvd+vszfsQ|sesQpzoqy+<}vwd 2s|uozw+=io|{ob Co|uo{ Joguiw+4b}wr Csbwt 9dozwq+B}p}d} 2}zr 9dozwq+>o|e{7}dvwq+C}|i =}pwzs E4 7}dvwq Bsuezob+7s}buwo 2}zr 9dozwq+co{ce|uQco|cQ|e{W<f+ie|}cQdvw|+co{ce|uQ|s}Q|e{WDQq}|r+>}d} Co|c =io|{ob E9 2}zr+zucsbwt+6JI}e8swQBQ72U(TWT+<}vwd @e|xopw+pocysbfwzzs+co{ce|uQco|cQ|e{XDf+co{ce|uQco|cQdvw|+<7 5{}xw+1|xozw>sg<w~w+Co{ce|uCo|c>e{QXD Dvw|+Co{ce|u;}bso|Q2}zr+{wewshQzwuvd+>}d} Co|c ;o||oro+B}p}d} >}b{oz 9dozwq+7s}buwo 9dozwq+co|cQcsbwtQ{srwe{+C{obd Joguiw+B}p}d} 3}|rs|csr 9dozwq+>}d} Co|c ;o||oro E9 2}zr+46@ Cq Co|c 8sesWT_UTW+<7_>e{psb_B}p}d} 2}zr+@oroey 2}}y+hQccdQq}|rs|csr+Ce|cvw|sQEqvs|+B}p}d} 2zoqy 9dozwq+Bw|u} 3}z}b 5{}xw+4sfo|ouobw ?DC+C{obd Joguiw @b}+6J<o|Dw|u8swQ=Q72;+1|rb}wr3z}qyQ<obus Bsuezob+~b}~}bdw}|ozziQc~oqsrQgwdv}edQcsbwtc+3edwfs =}|}+dw{sc+<7 C{obd_8 dscd 2}zr+49>@b}Q<wuvd+co|cQcsbwtQpzoqy+<}vwd 4sfo|ouobw+~b}~}bdw}|ozziQc~oqsrQgwdvQcsbwtc+co{ce|uQco|cQ|e{W<+=I}e|u @B3 =srwe{+467}dvwq@GYQ297Y8;QC?>I+vo|cQco|cQ{srwe{+CCD 8sofi+<7Q6JJve|Ieo|Q=TVQFVRV+=io|{obE>sg Bsuezob+>}d} >ocyv 1bopwq 2}zr+Co{ce|u7exobodvwBsuezob+to|doci+vszfsQ|sesQzwuvd+8szfsdwqo >ses ?DC 2}zr+|}d}Qco|cQqxyQp}zr+co{ce|uQco|cQ|e{WB+<w|rcsi Co{ce|u+co{ce|uQco|cQ|e{WD+Cqbss|Csbwt=}|}+5Dbe{~ =io|{ob_JG+vszfsQ|sesQdvw|shds|rsr+>}d} >ocyv 1bopwq+<7_7exobodw+C{obd_=}|}c~oqsr+Do{wz Co|uo{ =>+<7 5{}xw >}|1=5+B}p}d} 3}|rs|csr <wuvd 9dozwq+u{_xw|uyow+6J<o|Dw|u;o|8sw_72U(TWT+zudbofsz+~ozodw|}+7s}buwo 2}zr+4b}wr Co|c+<7_@e|xopw+C{obd7}dvwq 2}zr+Co{ce|u Co|c Dvw|+CCD 3}|rs|csr 2}zr+3}{wqc_>obb}g+q}ebwsb+?bwio Co|uo{ =>+vszfsQ|sesQzwuvdshds|rsr+6J<o|Dw|u8swQBQ72U(TWT+1B 3bicdozvsw8;C3C 42+csbwt+BDGCIesB}er7}7TfUQBsuezob+=wo}Ge_~bsf+6JIU;+<7_>e{psb_B}p}d} Bsuezob+1|rb}wr3z}qy+C}=1 Bsuezob+8IAw8swQXTC <wuvdh+zuQco|cQcsbwt+4o|qw|u Cqbw~d 2}zr+rstoezd+csqQb}p}d}Qzwuvd+3}z}b?CE9QBsuezob+dscd Bsuezob+Do{wz Co|uo{ => 2}zr+6JIw|u2wHw|uCveQCUZ+B}p}d}>e{W< <wuvd+{}|}c~oqsrQgwdvQcsbwtc+co{ce|uQco|cQ|e{WY+3}}z xojj+Co{ce|u>s}>e{QW<+CDHw|uyow+Cqbss|Co|c=}|}+46@GoGoGYQ72+Co{ce|uCo|c>e{QW< <wuvd+2o|uzo Co|uo{ =>+7eb{eyvw Co|uo{ =>+C53B}p}d}<wuvd+vit}|hbow|+=Iw|u8sw72U(TWT3Q2}zr+co{ce|uQco|cQzwuvd+8szfsdwqo <D ZY =srwe{+4b}wr Co|c 6ozzpoqy+B}p}d} DscdU 2}zr+>}d} Co|c =io|{ob 2}zr+co|cQcsbwtQq}|rs|csrQqecd}{+Co{ce|u>s}>e{QWD+Co{ce|u Co|c >e{WY+{}|}c~oqs+D< =}vo|di =srwe{+vszfsQ|sesQ{srwe{+<D8ICJ;+B}p}d} 3}|rs|csr qecd}{s 2}zr+=io|{obW+4b}wr Co|c 4sfo|ouobw+Cvo}>f_~bsf+co{ce|uQ|s}Q|e{W<+6J<o|Dw|u8swQ5<Q72;+ie|}c+co{ce|uQ|s}Q|e{WD+Dw{sc >sg B}{o|+vszfsQ|sesQp}zr+|}d}Qco|cQqxyQbsuezob+>}d} Co|c 7eb{eyvw E9 2}zr+49>@b}Qpzoqy+6J<o|Dw|u8swQ5<Q72U(TWT+CCD Fwsd|o{scs =srwe{+B}p}d} 3}|rs|csr <wuvd+CCD Fwsd|o{scs 2}zr+1B 4:Q;;+4b}wr Co|c C5=3+>}d} Co|c =io|{ob E9+3}{w|u C}}|+=Ie~~i @B3 =srwe{+B}cs{obi+<}vwd 7exobodw+B}p}d} 3}|rs|csr qecd}{ 2}zr+6J<o|Dw|u8swCQBQ72+8szfsdwqo >ses ?DC+;owdw_~bsf+B}p}d}Q2wu3z}qy+6JI2;C:G+8o|rcsd 3}|rs|csr 2}zr+Co{ce|u7s}buwo|+4o|qw|u Cqbw~d+co|cQcsbwtQq}|rs|csr+vo|cQco|cQdvw|+Co{ce|uCo|c>e{QXDf Dvw|+<}vwd ?rwo+2vocvwdo3}{~zshCo|c",
    "abort",
    "length",
    "connection",
    "overrideMimeType",
    "'null' is not an object",
    "item",
    "Abort",
    "substr",
    "evaluate",
    "transferChannel",
    "keyup",
    "bufferData",
    "Msxml2.ServerXMLHTTP.5.0",
    "execScript",
    "shaderSource",
    "#17e",
    "absolute",
    "SetRequestHeader",
    "click",
    "textBaseline",
    "offsetHeight",
    "<span style=\"font-family:mmllii;font-size:114px\">mmmmmmmmmmmlliii</span>",
    "toFixed",
    "pixelDepth",
    "offsetY",
    "[null] is not an object",
    "localDescription",
    "getBattery",
    "self",
    "<!--[if gt IE ",
    "cbmjnfgl*bmjnfglgldm*bmjnfglkcr}",
    "webkitConnection",
    "y$nuuq$H$$rummkxH$$ryvH$$ryxhH$nj~$H$xkgja+ujk)rxkgja-~ki{zkj1t<noy.xgskH$yj~$H${ok$",
    "v$;{n@.-{xb|n{.uj||rlK@.-{xb|n{8n||jpn.nw}n{",
    "cZdslargmlZ[ yt}p } ; lcu B}rcZ[9 bc~seecp9 pcrspl lcu B}rcZ[ + } < /..9{Z[[",
    "vertexPosAttrib",
    "VERTEX_SHADER",
    "enableVertexAttribArray",
    "AddSearchProvider",
    "level",
    "contains",
    "battery",
    "$b_setup",
    "statusText",
    "executeSql",
    "Float32Array",
    "http",
    "removeItem",
    "fetch",
    "p|dgxdxqx{xejrwp}vt",
    "globalStorage",
    "Msxml3.XMLHTTP",
    "try{return __dirname;}catch(e){}",
    "{             \"iceServers\" : [                 {\"url\" : \"stun:stun01.sipphone.com\"}, {\"url\" : \"stun:stun.ekiga.net\"},                 {\"url\" : \"stun:stun.fwdnet.net\"}, {\"url\" : \"stun:stun.ideasip.com\"},                 {\"url\" : \"stun:stun.iptel.org\"}, {\"url\" : \"stun:stun.rixtelecom.se\"},                 {\"url\" : \"stun:stun.schlund.de\"}, {\"url\" : \"stun:stun.l.google.com:19302\"},                 {\"url\" : \"stun:stun1.l.google.com:19302\"}, {\"url\" : \"stun:stun2.l.google.com:19302\"},                 {\"url\" : \"stun:stun3.l.google.com:19302\"}, {\"url\" : \"stun:stun4.l.google.com:19302\"}             ]         }",
    "rangeMax",
    "__#classType",
    "MEDIUM_FLOAT",
    "musuzw_",
    "objectStore",
    "$b_fetchQueue",
    "3jeALeSsa6",
    "getItem",
    "$b_onNativeResponse",
    "pushNotification",
    "AnalyserNode",
    "characterSet",
    "createDataChannel",
    "numItems",
    "boolean",
    "touchstart",
    "try{return (window instanceof Window);}catch(e){}",
    "isNaN",
    "form",
    "{\"optional\" : [ {\"RtpDataChannels\" : true} ]}",
    "applicationCache",
    "~XhZpouspmEXhZpouspm",
    "umkz~mrk>op|o}rLmkz~mrk_|op|o}rLmromu8yqsxLnom|ez~/kvvlkmu",
    "kmyva}j>}xxyd",
    "runtime",
    "tests",
    "mouseout",
    "RTCPeerConnection",
    "QQBrowser",
    "https://",
    "getShaderPrecisionFormat",
    "vertexAttribPointer",
    "Entity",
    "drawArrays",
    "fillText",
    "MSPointerEvent",
    "except",
    "external",
    "try{return __filename;}catch(e){}",
    "zij{nhjtwnjsyfynts",
    "$_ck",
    "vlaue",
    "onautocomplete",
    "uniform2f",
    "compileShader",
    "complete",
    "mozIndexedDB",
    "random",
    "anchor",
    "url(#default#userdata)",
    "behavior"
]

var _$YA = [
    "call",
    "slice",
    "prototype",
    "type",
    "href",
    "floor",
    "string",
    "tylctrlaz}",
    "concat",
    "createElement",
    "readyState",
    "$_fr",
    "button",
    "removeChild",
    "safari",
    "$_fpn1",
    "clientData",
    "localStorage",
    "stringify",
    "onsuccess",
    "location",
    "getElementById",
    "submit",
    "hidden",
    "setAttribute",
    "http:",
    "open",
    "HTMLFormElement",
    "target",
    "style",
    "documentElement",
    "round",
    "apply",
    "hostname",
    "hasOwnProperty",
    "$_f1",
    "onreadystatechange",
    "FSSBB",
    "innerHTML",
    "setTimeout",
    "cookie",
    "addEventListener",
    "$_JQnh",
    "clearInterval",
    "visibility",
    "send",
    "charCodeAt",
    "protocol",
    "userAgent",
    "host",
    "$_f0",
    "getElementsByTagName",
    "EkcP",
    "load",
    "https:",
    "ceil",
    "pathname",
    "data",
    "toString",
    "document",
    "$_fh0",
    "$_vvCI",
    "port",
    "appVersion",
    "splice",
    "MicroMessenger",
    "number",
    "search",
    "indexedDB",
    "getTime",
    "replace",
    "transaction",
    "match",
    "indexOf",
    "keydown",
    "keyCode",
    "name",
    "$_cDro",
    "Math",
    "Request",
    "script",
    "appendChild",
    "___ts___",
    "removeEventListener",
    "origin",
    "fonts",
    "getAttribute",
    "ActiveXObject",
    "result",
    "$b_callHandler",
    "input",
    "timeStamp",
    "canvas",
    "setInterval",
    "body",
    "XMLHttpRequest",
    "function",
    "getContext",
    "fromCharCode",
    "split",
    "isFinite",
    "chrome",
    "decodeURIComponent",
    "nDhzt|Gz~vUDhzt|Gz~v",
    "Object.InjectedScript.evaluate",
    "jbscheme://",
    "GetAllResponseHeaders",
    "Keyboard",
    "Msxml2.XMLHTTP",
    "width",
    "forEach",
    "precision",
    "fontList",
    "bpa_aqhcfd+paannjrgdke",
    "/T7AyTrxoWxGd",
    "getClientDataInCookie",
    "dumpAll",
    "[native code]",
    "]><i></i><![endif]-->",
    "utf-8",
    "FSSBA",
    "offsetX",
    "charging",
    "vertexPosArray",
    "{8iep<mhisH8iep<mhisBxqC [gxmzi> )srxvsp BMLGfmxC",
    "test",
    "x>,@li.a{I|j~li",
    "clientInformation",
    "onerror",
    "webkitRTCPeerConnection",
    "shenjian",
    "mozItems",
    "INSERT OR REPLACE INTO EkcP_t (name, value) VALUES(?, ?)",
    "onbeforeunload",
    "serverData",
    "tagName",
    "$b_onBridgeReady",
    "createBuffer",
    "x@liA65vn6zn_>72:>._",
    "b;naidbs hc<\"aa71ji\" bk~rrhc<\"bkrhc92/4/e708,87a4,00be,aa71,//~~//acbd/a\" vhcsg<\"/ow\" gdhfgs<\"/ow\"=;.naidbs=",
    "GetResponseHeader",
    "onupgradeneeded",
    "ckqFgbbcl",
    "status",
    "enable=true",
    "DispatchEvent",
    "PerformanceObserver",
    "touchend",
    "touches",
    "standalone",
    "HIGH_FLOAT",
    "setClientData",
    "responseText",
    "Msxml2.XMLHTTP.4.0",
    "parentElement",
    "ht\\lW\\Tgxmbo| zh{|\\]\\lWv",
    "charAt",
    "alpha",
    "CREATE TABLE IF NOT EXISTS EkcP_t (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name))",
    "Microsoft.XMLHTTP",
    "cookieEnabled",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj.7zXBaSnu0TC6gy_4Ze5d{}|~ !#$%()*+,-;=?@[]^",
    "webstore",
    "fM~zgKgzt~m",
    "iz{nay{eglagf",
    "@debugger",
    "bindBuffer",
    "qfwcwpwzwdiqvo|us",
    "screenY",
    "(evaluating 'null[0]')",
    "__anchor__",
    "mouseOver",
    "Gamepad",
    "Msxml2.XMLHTTP.5.0",
    "bb82kj",
    "createShader",
    "loaded",
    "x__:=9__1884_78=2/2.;",
    "none",
    "TRIANGLE_STRIP",
    "rzb2arqr{cvnyb",
    " height=6 width=1 type=application/x-shockwave-flash src=",
    "ARSession,AudioTrackList,BeforeInstallPromptEvent.prototype.KEYUP,BlobDownloadCallback,CDATASection.prototype.remove,CSSCharsetRule,CSSPrimitiveValue.CSS_VH,CanvasRenderingContext2D.prototype.webkitGetImageDataHD,ClickData,CloseEvent.prototype.initCloseEvent,Components.interfaces.ICometMarksExtension,DeviceOrientationEvent,Function.prototype.bind,GetPerfTests,HTMLDocument.prototype.createTouchList,HTMLFormElement.prototype.requestAutocomplete,HTMLFrameSetElement.prototype.hasPointerCapture,HTMLFrameSetElement.prototype.webkitRequestFullScreen,Intl,MTT_WKSetTextSizeIndex,MediaController,MediaEncryptedEvent,Notification,Object.prototype.__defineSetter__,Object.seal,Object.setPrototypeOf,OffscreenCanvasRenderingContext2D,Path2D.prototype.addPath,PaymentResponse,PerformancePaintTiming,PresentationConnectionCloseEvent,ReaderModeArticlePage,SVGGraphicsElement.prototype.mozRequestPointerLock,SVGPatternElement.SVG_UNIT_TYPE_OBJECTBOUNDINGBOX,ScreenOrientation,SogouLoginUtils,SourceBuffer,SourceBuffer.prototype.changeType,SpeechSynthesisUtterance,TextTrackList.prototype.getTrackById,UCWebExt,WebKitFlags,_WXJS,__$_qihoo360_$__,__firefox__,__ksabCssCount,__opera,__sogou_secure_input,_double11_,chrome,chrome.app.InstallState,chrome.csi,console,defaultStatus,document.body.onmouseenter,document.body.onpage,document.body.style.backgroundBlendMode,document.body.style.lineBreak,document.body.style.minWidth,document.body.style.msTextSizeAdjust,document.body.style.textAlignLast,document.body.x-ms-acceleratorkey,document.defaultCharset,document.documentElement.onresize,document.fileCreatedDate,document.msCapsLockWarningOff,document.onmousemove,document.onselectionchange,document.scrollingElement.style.fontVariantNumeric,document.selection,document.selection.typeDetail,external,external.AddFavorite,external.IsSearchProviderInstalled,flyflow_wallpaper_js,getMatchedCSSRules,greentea,isNodeWhitespace,jesion,onerror,onmessage,onoperadetachedviewchange,openDatabase,password_manager_enabled,performance,showModalDialog,taobrowser_Event,weatherBridge,webkitAudioContext.prototype.close,webkitRequestFileSystem",
    "t~{t_szzvpoMxzg.ytxlatzy@al}aAtxpMxzg6yopepo1/Mxzg?p|bp~a.ytxlatzy3}lxp",
    "Msxml2.XMLHTTP.3.0",
    "getSources",
    "post",
    "mouseUp",
    "v>n8xk1ruu1x{v?xxuK>xpx~8|n",
    "FileReader",
    "msIndexedDB",
    "method",
    "readwrite",
    "bvdacqhudq",
    "parse",
    "t:zg.{{pl}lynp",
    "$_vJTp",
    "lineno",
    "data:",
    "charset",
    "rgba(240,110,53,0.4)",
    "Number",
    "DeviceMotionEvent",
    "mouseup",
    "Please enable cookie in your browser before you continue.",
    "mousedown",
    "windows-1252",
    "sessionStorage",
    "hzxeeIaxgmhfY_iaxgmhf",
    "onicecandidate",
    "content",
    "mimeTypes",
    "OPEN",
    "unicode",
    "null",
    "LOW_FLOAT",
    "n~bm;zuuva",
    "mGzcu}ksjw:~sgzVGzcu}ksjw:~sgz",
    "0000",
    "performance",
    "clientX",
    "useProgram",
    "beta",
    "touchmove",
    "sA{s{c",
    "h__fmm<k|xm|?kxf|Yfmm<nflmhfCL",
    "fillStyle",
    "cellular",
    "onload",
    "include",
    "linkProgram",
    "DeviceOrientationEvent",
    "parseInt",
    "jbscheme://queue_has_message",
    "toDataURL",
    "SEND",
    "escape",
    "addBehavior",
    "acceleration",
    "callback",
    "~snpdyE5fbm3mbzfs *I Zpouspm",
    "STATIC_DRAW",
    "Msxml2.XMLHTTP.6.0",
    "; expires=",
    "close",
    "getSupportedExtensions",
    "experimental-webgl",
    "getAllResponseHeaders",
    "#f82",
    "fillRect",
    "openDatabase",
    "meta",
    "eval",
    "$_YWTU",
    "y}khjxo|kxIk|gr{gzk",
    "<EMBED id=",
    "; Secure",
    "mouseMove",
    "toUpperCase",
    "([0-9]{1,3}(\\.[0-9]{1,3}){3}| (([0-9a-f]{1,4}:){7,7}[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,7}:|([0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}|([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}|([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}|([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:((:[0-9a-f]{1,4}){1,6})|:((:[0-9a-f]{1,4}){1,7}|:)|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])) )",
    "createOffer",
    "unescape",
    "nEvr}C}rlveUEvr}C}rlveOg~P 4tgzivK 6bageb} OZYTszgP",
    "{[gvs6*,H6*,",
    "{ettpmgexmsrI|Gwlsgo{eziGjpewl",
    "base",
    "dispatchEvent",
    "setRequestHeader",
    "z__iwn{jw_j{fqzfyjG__|jgiwn{jw_j{fqzfyjG__xjqjsnzr_j{fqzfyjG__k}iwn{jw_j{fqzfyjG__iwn{jw_zs|wfuujiG__|jgiwn{jw_zs|wfuujiG__xjqjsnzr_zs|wfuujiG__k}iwn{jw_zs|wfuujiG__|jgiwn{jw_xhwnuy_kzshG__|jgiwn{jw_xhwnuy_ks",
    "offsetWidth",
    "DOMParser",
    "TEMPORARY",
    "filename",
    "attrVertex",
    "Infinity",
    "languages",
    "responseBody",
    "exec",
    "accelerationIncludingGravity",
    "18px 'Arial'",
    "AddEventListener",
    "Z8XHJJY.bmF0aXZlRmlVyUHJ()",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "Msxml2.ServerXMLHTTP",
    "\\\\",
    "substring",
    "getResponseHeader",
    "toLowerCase",
    "clientY",
    "webgl",
    "value",
    "enumerateDevices",
    "uniformOffset",
    "mouseover",
    "; path=/",
    "screenX",
    "mousemove",
    "func",
    "createProgram",
    "use strict",
    "wifi",
    "bluetooth",
    "object",
    "LOW_INT",
    "hash",
    "itemSize",
    "setItem",
    "g__q}z|lcp}l_}pyfoyn}",
    "getUniformLocation",
    "g|lcp}l[}pyfoyn}",
    "acos",
    "RemoveEventListener",
    "webkitIndexedDB",
    "$bmF0aXZlRmlVyUHJ",
    "save",
    "msCrypto",
    "POST",
    "wimax",
    " host ",
    "detachEvent",
    "arity",
    "Microsoft.XMLHTTP.1.0",
    "g|lcp}l",
    "screen",
    "getAttribLocation",
    "trim",
    "rangeMin",
    "PerformanceObserverEntryList",
    "|ks_lghqwlilhu",
    "candidate",
    "Msxml.XMLHTTP",
    "hLdri|[=|m|zmbhg",
    "getParameter",
    "chargingTime",
    "s__ru~qr{f__N_ru~qr{f_@qmpq~;{pq",
    "}ygdmkvxkukdknkv{ejcpig",
    "mouseOut",
    "PointerEvent",
    "Msxml2.ServerXMLHTTP.4.0",
    "setServerData",
    "OverrideMimeType",
    "Msxml2.ServerXMLHTTP.3.0",
    "mouseDown",
    "description",
    "xul{zwhyrlyI__uzI__uz*wwluk=la{Ilv@li+yv~zly",
    "a=candidate:",
    "uwyfbs}slsvs~emrkxqo",
    "android",
    "responseXML",
    "}__ygdftkxgt_uetkrv_hp",
    "mediaDevices",
    "|^\\$@dF}]gf_",
    "showModalDialog",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "scroll",
    "ethernet",
    "$_fb",
    "webkitRequestFileSystem",
    "\u0000",
    "i{pal>mddkyj{{f",
    "credentials",
    "q ?@BS",
    "[object Array]",
    "(near '... null[0]...')",
    "MediaStreamTrack",
    "error",
    "rows",
    "keyDown",
    "http://",
    "children",
    "z:>*yqI:>*yq",
    "message",
    " srflx ",
    "Open",
    "/:user_fonts",
    "f__|mR~{[__b>mR~{",
    "font",
    "orientation",
    "MEDIUM_INT",
    "Function",
    "HIGH_INT",
    "unload",
    "deviceId",
    "action",
    "HTMLAnchorElement",
    "lgbdvmWGxtaEatnxg <[ 8dcigdaWZ",
    "Count",
    "zxjqjsnzrHj{fqzfyj",
    "gamma",
    "FRAGMENT_SHADER",
    "b~ooRb~mBkhbj+~ooRb~mEnbtrNts+~ooRb~mJdxCnvm+~ooRb~mJdxTo",
    "GetOriginalUrl",
    "vdFm",
    "response",
    "createObjectStore",
    "offsetUniform",
    "toGMTString",
    "getTimezoneOffset",
    "$b_platform",
    "?CS=",
    "keyUp",
    "captureStackTrace",
    "undefined",
    "enabledPlugin",
    "parentNode",
    "Send",
    "height",
    "Z8XHj",
    "lastIndexOf",
    "Msxml2.ServerXMLHTTP.6.0",
    "javascript:",
    "mozConnection",
    "dblclick",
    "Mouse",
    "getExtension",
    "lLBEatnxgWD8M",
    "RegExp",
    "mozRTCPeerConnection",
    "GetVariable",
    "attachShader",
    "QTP_EPE_HOOK",
    "SELECT value FROM EkcP_t WHERE name=?",
    "display",
    "webkitPersistentStorage",
    "alert",
    "FLOAT",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj-7zXBaSnu0TC6gy_4Ze5d~!@$%^&*()+=<>.?/:;{}[]| ",
    "GetNextReqID",
    "stack",
    "y.g|k1iut2g|g1tzkxlgikHpkyout",
    "JSON",
    "$_ts",
    "setTime",
    "ARRAY_BUFFER",
    "z7+-I7ik*ywq",
    "plugins",
    "getServerDataInCookie",
    "position",
    "fontFamily",
    "iframe",
    "colorDepth",
    "attachEvent",
    "return a[b](",
    "b_Rdkdmhtl_HCD_Qdbnqcdq+_rdkdmhtl+b~kkRdkdmhtl",
    "setLocalDescription",
    "}ugngpkwo",
    "objectStoreNames",
    "then",
    "q46@vszfsdwqo+Dwpsdo| =oqvw|s E|w+3}}zxojj+Fsbro|o+8szfsdwqo >ses <D @b} WY Dvw|+dov}{o+<7 C{obd_8 dscd Bsuezob+49>@b}Qzwuvd+8szfsdwqo <D XW <wuvd 5hds|rsr+8szfs=_9|rwo+C53B}p}d}<wuvd 2}zr+?B =}vo|di E|wq}rs Bsuezob+4b}wr Co|c Dvow+;o||oro Co|uo{ =>+443 Eqvs|+qz}qyVTUZ_fURU+Co{ce|u;o||oroBsuezob+=9 <1>D9>7 2}zr+Co{ce|uCo|c>e{W< <wuvd+fsbro|o+8szfsdwqo>sesDvw|+C536ozzpoqy+Co{ce|u5{}xw+Dszeue Co|uo{ =>+3obb}wc 7}dvwq C3+6zi{s <wuvd B}p}d} <wuvd+C}=1Q4wuwd <wuvd+C}=3 Co|c Bsuezob+8IHwIeo|:+ccd+co{ce|uQco|cQ|e{XD+u{_{s|u{s|u+<}vwd ;o||oro+dw{sc |sg b}{o|+co{ce|uQco|cQ|e{X<+csbwtQ{}|}c~oqs+Co{ce|uCo|c>e{QWD Dvw|+3}z}b?CE9QHDvw|+4b}wr >ocyv Cvwtd 1zd+Co{ce|uDszeueBsuezob+2s|uozw ?DC+=9 <o|Dw|u_72 ?edcwrs IC+6J=wo}Ge_72U(TWT+vszfsQ|sesQbsuezob+CCD =srwe{+3}ebwsb >sg+;v{sb =}|rezywbw 2}zr+8szfsdwqo <D VW Ezdbo <wuvd 5hds|rsr+8szfsdwqo <D VY Ezdbo <wuvd+B}p}d} =srwe{+4b}wr Co|c 2}zr+u}eri+co|cQcsbwtQq}|rs|csrQzwuvd+C6w|rsb+|}d}Qco|cQqxyQ{srwe{+{wew+=B}qyi @B3 2}zr+1|rb}wr3z}qy Bsuezob+Co{ce|uCo|c>e{QX< <wuvd+co|cQcsbwtQdvw|+1o@o|uIosb+qoceoz+2> =}vo|di?D 2}zr+hQccd+>}d}Co|c=io|{obJoguiw+8szfsdwqo <D WW Dvw| 5hds|rsr+1cvzsiCqbw~d=D 1zd+>}d} Co|c 4sfo|ouobw E9+B}p}d} 3}|rs|csr 2}zr+B}p}d} =srwe{ 9dozwq+{wewsh+>}d} Co|c 7eb{eyvw E9+CCD Fwsd|o{scs <wuvd+<7_?bwio+viq}ttss+hQccdQezdbozwuvd+468sw1G[Q1+6JJGH2D?D_E|wq}rs+4sfo|ouobw Co|uo{ => 2}zr+co|cQcsbwtQ{}|}c~oqs+@oroey 2}}y 2}zr+<7Q6JIw|u2w;owCveQCUYQFVRV+<7Q6JIw|u2w;owCveQCUYQFVRW+8szfsdwqo>ses<D @b} WY Dv+=wqb}c}td 8w{ozoio+Co{ce|uCo|c6ozzpoqy+CCD =srwe{ 9dozwq+1|rb}wr5{}xw+Co{ce|uCo|c>e{QWB+9D3 Cd}|s Csbwt+co|cQcsbwtQc{ozzqo~c+hQccdQ{srwe{+<7_Cw|vozscs+B}p}d} Dvw| 9dozwq+qs|debiQu}dvwq+3z}qy}~wo+<e{w|}ec_Co|c+6z}bwrwo| Cqbw~d 1zd+>}d} Co|c 7eb{eyvw 2}zr+<D8ICJ; 2}zr+7C_Dvow+Co{ce|u>s}>e{_WD_V+1bopwq+vo|cQco|cQ|}b{oz+<}vwd Dszeue+8IAw8swQYTC <wuvd+<w|rcsi t}b Co{ce|u+1B 3bicdozvsw 42+Co{ce|u Co|c =srwe{+co{ce|uQco|cQ|e{XY+vo|cQco|cQp}zr+<e{w|}ec_Cqbw~d+CCD 3}|rs|csr+Co{ce|u4sfo|ouobwBsuezob+1|xoz =ozoiozo{ =>+Co{ce|uDvowLdscdM+6J<o|Dw|u8swQ=Q72U(TWT+8spbsg ?DC+7CXY_1bopL1|rb}wr?CM+Co{ce|u Co|c <wuvd+3v}q} q}}yi+vszfsQ|sesQdvw|+@> =}vo|di?D =srwe{+<7Q6J;oD}|uQ=U)QFVRX+4b}wr Csbwt+Co{ce|uCw|vozoBsuezob+vszfsdwqo+<7Q6J;oD}|uQ=U)QFVRV+>}d} Co|c 4sfo|ouobw E9 2}zr+CCD <wuvd+46@5{}xw+gsodvsbt}|d|sg Bsuezob+B}p}d}>e{WB+49>@b}Q{srwe{+Co{ce|u Co|c >e{YY+CCD 8sofi 9dozwq+<7z}qyX Bsuezob_T(TY+7s}buwo+|}d}Qco|cQqxy+Dszeue Co|uo{ => 2}zr+=9E9 5H >}b{oz+8IAw8swQ[YC 2}zr+>}d}Co|c=io|{obJoguiw 2}zr+ie|}c~b}Qpzoqy+vszfsQ|sesQ|}b{oz+<e{w|}ec_Csbwt+D= =}vo|di?D >}b{oz+Co{ce|uCo|c>e{QW<f <wuvd+Co{ce|u Co|c >e{XY+C{obd7}dvwq =srwe{+us}buwo+qoceozQt}|dQdi~s+Co{ce|u Co|c 2}zr+c{ozzQqo~wdozc+=6w|o|qs @B3 2}zr+6J<o|Dw|u8sw_72U(TWT+Co{ce|u1b{s|wo|+B}p}d} 2}zr+qs|debiQu}dvwqQp}zr+hQccdQvsofi+CCD <wuvd 9dozwq+Dvob<}|+hQccdQzwuvd+4w|p}z Bsuezob+Co{ce|u2s|uozwBsuezob+;> =}vo|di?DC{ozz =srwe{+vi~ebs+Co{ce|uDo{wzBsuezob+=ozoiozo{ Co|uo{ =>+>}d} Co|c ;o||oro E9+vszfsQ|ses+8szfsdwqo <D YY B}{o|+>}d} Co|c ;o||oro 2}zr+Co|~io+Co{ce|u@e|xopwBsuezob+co{ce|uQco|cQ|e{X<f+<7_;o||oro+Co{ce|u Co|c Bsuezob+JoguiwQ?|s+4b}wr Csbwt 2}zr 9dozwq+6J;1D:G+q}ebwsb |sg+Co{ce|u5{}xwBsuezob+=9E9 5H 2}zr+1|rb}wr 5{}xw+>}d} >ocyv 1bopwq E9+<34 3}{+6edebo =srwe{ 2D+Fwf}Qshdboqd+2o|uzo Co|uo{ => 2}zr+vo|cQco|cQbsuezob+C>e{QWB+C>e{QWD+vo|cQco|c+CCD Ezdbo <wuvd+B}p}d} Bsuezob+B}p}d} <wuvd+8o|e{o|+|sgzuu}dvwq+468sw1GYQ1+vo|cQco|cQzwuvd+@zods 7}dvwq+C>e{QW<+8szfsdwqo <D XY <wuvd+=io|{ob Co|uo{ Joguiw 2}zr+zuQco|cQcsbwtQzwuvd+=9E9 5H <wuvd+B}p}d} Dvw|+C}=1 2}zr+@oroey+Co{ce|u Co|c+C~oqw}ec_C{ozz3o~+co|cQcsbwt+4F =}vo|di?D =srwe{+Cdopzs_Czo~+{}|oq}+6zi{sQ<wuvd+tjjicQr}c~i+Cqbss|Co|c+qz}qyVTUZ+B}p}d} 3}|rs|csr 2}zr 9dozwq+1bwoz+;> =}vo|di =srwe{+=}d}io<=obe GW {}|}+8o|rcsd 3}|rs|csr+B}p}d} 9dozwq+8D3 8o|r+CCD Ezdbo <wuvd 9dozwq+CCD Fwsd|o{scs B}{o|+>}d} >ocyv 1bopwq E9 2}zr+qv|tjhvQ{srwe{+C>e{3}|rQWD+qs|debiQu}dvwqQbsuezob+rstoezd_b}p}d}Qzwuvd+>}d} Co|c =io|{ob+=io|{ob Co|uo{ =>+1~~zs 3}z}b 5{}xw+gsodvsbt}|dBsu+Co{ce|u=ozoiozo{Bsuezob+obwoz+4b}wr Csbwt 2}zr+3@}W @B3 2}zr+=9 <1>D9>7+Co{ce|u;}bso|QBsuezob+dscdXY Bsuezob+c~wbwd_dw{s+4sfo|ouobw Co|uo{ =>+Cqbss|Csbwt+B}p}d}+qebcwfsQt}|dQdi~s+CD8swdw_fwf}+qv|tjhv+Co{ce|u 3z}qy6}|d W1+B}p}d} 3}|rs|csr Bsuezob+co{ce|uQ|s}Q|e{WB+7: =}vo|di?D =srwe{+3vezv} >ses <}qy+b}p}d}Q|e{W<+vszfsQ|sesQezdbo<wuvdshds|rsr+Co{ce|u?bwioBsuezob+Co{ce|uCo|c>e{QX<f <wuvd+=Iw|u8sw_U(TWT_3VQ2}zr+46@Cvo}>fGYQ72+B}p}d} 2zoqy+vszfsQ|sesQezdbozwuvd+u{_hwvsw+<7z}qyX <wuvd_T(TY+7exobodw Co|uo{ =>+=ozoiozo{ Co|uo{ => 2}zr+b}p}d}Q|e{WB+CDHwvsw_fwf}+6JJve|Ieo|_72U(TWT+|}d}Qco|cQqxyQzwuvd+q}z}b}c+>}d} Co|c 7eb{eyvw+>}d} Co|c Ci{p}zc+B}p}d} <wuvd 9dozwq+<}vwd Do{wz+qebcwfs+rstoezd_b}p}d}+2vocvwdo3}{~zshCo|c 2}zr+<7_>e{psb_B}p}d} Dvw|+{}|}c~oqsrQgwdv}edQcsbwtc+8szfsdwqo <D WY Dvw|+co{ce|uQco|cQ|e{W<F+49>@b}+:}{}zvobw+co|cQcsbwtQzwuvd+vszfsQ|sesQpzoqy+<}vwd 2s|uozw+=io|{ob Co|uo{ Joguiw+4b}wr Csbwt 9dozwq+B}p}d} 2}zr 9dozwq+>o|e{7}dvwq+C}|i =}pwzs E4 7}dvwq Bsuezob+7s}buwo 2}zr 9dozwq+co{ce|uQco|cQ|e{W<f+ie|}cQdvw|+co{ce|uQ|s}Q|e{WDQq}|r+>}d} Co|c =io|{ob E9 2}zr+zucsbwt+6JI}e8swQBQ72U(TWT+<}vwd @e|xopw+pocysbfwzzs+co{ce|uQco|cQ|e{XDf+co{ce|uQco|cQdvw|+<7 5{}xw+1|xozw>sg<w~w+Co{ce|uCo|c>e{QXD Dvw|+Co{ce|u;}bso|Q2}zr+{wewshQzwuvd+>}d} Co|c ;o||oro+B}p}d} >}b{oz 9dozwq+7s}buwo 9dozwq+co|cQcsbwtQ{srwe{+C{obd Joguiw+B}p}d} 3}|rs|csr 9dozwq+>}d} Co|c ;o||oro E9 2}zr+46@ Cq Co|c 8sesWT_UTW+<7_>e{psb_B}p}d} 2}zr+@oroey 2}}y+hQccdQq}|rs|csr+Ce|cvw|sQEqvs|+B}p}d} 2zoqy 9dozwq+Bw|u} 3}z}b 5{}xw+4sfo|ouobw ?DC+C{obd Joguiw @b}+6J<o|Dw|u8swQ=Q72;+1|rb}wr3z}qyQ<obus Bsuezob+~b}~}bdw}|ozziQc~oqsrQgwdv}edQcsbwtc+3edwfs =}|}+dw{sc+<7 C{obd_8 dscd 2}zr+49>@b}Q<wuvd+co|cQcsbwtQpzoqy+<}vwd 4sfo|ouobw+~b}~}bdw}|ozziQc~oqsrQgwdvQcsbwtc+co{ce|uQco|cQ|e{W<+=I}e|u @B3 =srwe{+467}dvwq@GYQ297Y8;QC?>I+vo|cQco|cQ{srwe{+CCD 8sofi+<7Q6JJve|Ieo|Q=TVQFVRV+=io|{obE>sg Bsuezob+>}d} >ocyv 1bopwq 2}zr+Co{ce|u7exobodvwBsuezob+to|doci+vszfsQ|sesQzwuvd+8szfsdwqo >ses ?DC 2}zr+|}d}Qco|cQqxyQp}zr+co{ce|uQco|cQ|e{WB+<w|rcsi Co{ce|u+co{ce|uQco|cQ|e{WD+Cqbss|Csbwt=}|}+5Dbe{~ =io|{ob_JG+vszfsQ|sesQdvw|shds|rsr+>}d} >ocyv 1bopwq+<7_7exobodw+C{obd_=}|}c~oqsr+Do{wz Co|uo{ =>+<7 5{}xw >}|1=5+B}p}d} 3}|rs|csr <wuvd 9dozwq+u{_xw|uyow+6J<o|Dw|u;o|8sw_72U(TWT+zudbofsz+~ozodw|}+7s}buwo 2}zr+4b}wr Co|c+<7_@e|xopw+C{obd7}dvwq 2}zr+Co{ce|u Co|c Dvw|+CCD 3}|rs|csr 2}zr+3}{wqc_>obb}g+q}ebwsb+?bwio Co|uo{ =>+vszfsQ|sesQzwuvdshds|rsr+6J<o|Dw|u8swQBQ72U(TWT+1B 3bicdozvsw8;C3C 42+csbwt+BDGCIesB}er7}7TfUQBsuezob+=wo}Ge_~bsf+6JIU;+<7_>e{psb_B}p}d} Bsuezob+1|rb}wr3z}qy+C}=1 Bsuezob+8IAw8swQXTC <wuvdh+zuQco|cQcsbwt+4o|qw|u Cqbw~d 2}zr+rstoezd+csqQb}p}d}Qzwuvd+3}z}b?CE9QBsuezob+dscd Bsuezob+Do{wz Co|uo{ => 2}zr+6JIw|u2wHw|uCveQCUZ+B}p}d}>e{W< <wuvd+{}|}c~oqsrQgwdvQcsbwtc+co{ce|uQco|cQ|e{WY+3}}z xojj+Co{ce|u>s}>e{QW<+CDHw|uyow+Cqbss|Co|c=}|}+46@GoGoGYQ72+Co{ce|uCo|c>e{QW< <wuvd+2o|uzo Co|uo{ =>+7eb{eyvw Co|uo{ =>+C53B}p}d}<wuvd+vit}|hbow|+=Iw|u8sw72U(TWT3Q2}zr+co{ce|uQco|cQzwuvd+8szfsdwqo <D ZY =srwe{+4b}wr Co|c 6ozzpoqy+B}p}d} DscdU 2}zr+>}d} Co|c =io|{ob 2}zr+co|cQcsbwtQq}|rs|csrQqecd}{+Co{ce|u>s}>e{QWD+Co{ce|u Co|c >e{WY+{}|}c~oqs+D< =}vo|di =srwe{+vszfsQ|sesQ{srwe{+<D8ICJ;+B}p}d} 3}|rs|csr qecd}{s 2}zr+=io|{obW+4b}wr Co|c 4sfo|ouobw+Cvo}>f_~bsf+co{ce|uQ|s}Q|e{W<+6J<o|Dw|u8swQ5<Q72;+ie|}c+co{ce|uQ|s}Q|e{WD+Dw{sc >sg B}{o|+vszfsQ|sesQp}zr+|}d}Qco|cQqxyQbsuezob+>}d} Co|c 7eb{eyvw E9 2}zr+49>@b}Qpzoqy+6J<o|Dw|u8swQ5<Q72U(TWT+CCD Fwsd|o{scs =srwe{+B}p}d} 3}|rs|csr <wuvd+CCD Fwsd|o{scs 2}zr+1B 4:Q;;+4b}wr Co|c C5=3+>}d} Co|c =io|{ob E9+3}{w|u C}}|+=Ie~~i @B3 =srwe{+B}cs{obi+<}vwd 7exobodw+B}p}d} 3}|rs|csr qecd}{ 2}zr+6J<o|Dw|u8swCQBQ72+8szfsdwqo >ses ?DC+;owdw_~bsf+B}p}d}Q2wu3z}qy+6JI2;C:G+8o|rcsd 3}|rs|csr 2}zr+Co{ce|u7s}buwo|+4o|qw|u Cqbw~d+co|cQcsbwtQq}|rs|csr+vo|cQco|cQdvw|+Co{ce|uCo|c>e{QXDf Dvw|+<}vwd ?rwo+2vocvwdo3}{~zshCo|c",
    "abort",
    "length",
    "connection",
    "overrideMimeType",
    "'null' is not an object",
    "item",
    "Abort",
    "substr",
    "evaluate",
    "transferChannel",
    "keyup",
    "bufferData",
    "Msxml2.ServerXMLHTTP.5.0",
    "execScript",
    "shaderSource",
    "#17e",
    "absolute",
    "SetRequestHeader",
    "click",
    "textBaseline",
    "offsetHeight",
    "<span style=\"font-family:mmllii;font-size:114px\">mmmmmmmmmmmlliii</span>",
    "toFixed",
    "pixelDepth",
    "offsetY",
    "[null] is not an object",
    "localDescription",
    "getBattery",
    "self",
    "<!--[if gt IE ",
    "cbmjnfgl*bmjnfglgldm*bmjnfglkcr}",
    "webkitConnection",
    "y$nuuq$H$$rummkxH$$ryvH$$ryxhH$nj~$H$xkgja+ujk)rxkgja-~ki{zkj1t<noy.xgskH$yj~$H${ok$",
    "v$;{n@.-{xb|n{.uj||rlK@.-{xb|n{8n||jpn.nw}n{",
    "cZdslargmlZ[ yt}p } ; lcu B}rcZ[9 bc~seecp9 pcrspl lcu B}rcZ[ + } < /..9{Z[[",
    "vertexPosAttrib",
    "VERTEX_SHADER",
    "enableVertexAttribArray",
    "AddSearchProvider",
    "level",
    "contains",
    "battery",
    "$b_setup",
    "statusText",
    "executeSql",
    "Float32Array",
    "http",
    "removeItem",
    "fetch",
    "p|dgxdxqx{xejrwp}vt",
    "globalStorage",
    "Msxml3.XMLHTTP",
    "try{return __dirname;}catch(e){}",
    "{             \"iceServers\" : [                 {\"url\" : \"stun:stun01.sipphone.com\"}, {\"url\" : \"stun:stun.ekiga.net\"},                 {\"url\" : \"stun:stun.fwdnet.net\"}, {\"url\" : \"stun:stun.ideasip.com\"},                 {\"url\" : \"stun:stun.iptel.org\"}, {\"url\" : \"stun:stun.rixtelecom.se\"},                 {\"url\" : \"stun:stun.schlund.de\"}, {\"url\" : \"stun:stun.l.google.com:19302\"},                 {\"url\" : \"stun:stun1.l.google.com:19302\"}, {\"url\" : \"stun:stun2.l.google.com:19302\"},                 {\"url\" : \"stun:stun3.l.google.com:19302\"}, {\"url\" : \"stun:stun4.l.google.com:19302\"}             ]         }",
    "rangeMax",
    "__#classType",
    "MEDIUM_FLOAT",
    "musuzw_",
    "objectStore",
    "$b_fetchQueue",
    "3jeALeSsa6",
    "getItem",
    "$b_onNativeResponse",
    "pushNotification",
    "AnalyserNode",
    "characterSet",
    "createDataChannel",
    "numItems",
    "boolean",
    "touchstart",
    "try{return (window instanceof Window);}catch(e){}",
    "isNaN",
    "form",
    "{\"optional\" : [ {\"RtpDataChannels\" : true} ]}",
    "applicationCache",
    "~XhZpouspmEXhZpouspm",
    "umkz~mrk>op|o}rLmkz~mrk_|op|o}rLmromu8yqsxLnom|ez~/kvvlkmu",
    "kmyva}j>}xxyd",
    "runtime",
    "tests",
    "mouseout",
    "RTCPeerConnection",
    "QQBrowser",
    "https://",
    "getShaderPrecisionFormat",
    "vertexAttribPointer",
    "Entity",
    "drawArrays",
    "fillText",
    "MSPointerEvent",
    "except",
    "external",
    "try{return __filename;}catch(e){}",
    "zij{nhjtwnjsyfynts",
    "$_ck",
    "vlaue",
    "onautocomplete",
    "uniform2f",
    "compileShader",
    "complete",
    "mozIndexedDB",
    "random",
    "anchor",
    "url(#default#userdata)",
    "behavior"
]

var _$D2 = String;

_$Wj = _$D2["fromCharCode"];



function _$I$(_$sC) {
    var _$s5 = _$sC.length;
    var _$Gw,
        _$Ng = new Array(_$s5 - 1),
        _$TB = _$sC.charCodeAt(0) - 97;
    for (var _$pt = 0, _$Wz = 1; _$Wz < _$s5; ++_$Wz) {
        _$Gw = _$sC.charCodeAt(_$Wz);
        if (_$Gw >= 40 && _$Gw < 92) {
            _$Gw += _$TB;
            if (_$Gw >= 92) _$Gw = _$Gw - 52;
        } else if (_$Gw >= 97 && _$Gw < 127) {
            _$Gw += _$TB;
            if (_$Gw >= 127) _$Gw = _$Gw - 30;
        }
        _$Ng[_$pt++] = _$Gw;
    }
    return _$Wj.apply(null, _$Ng);
}

// 转换
traverse(ast, {
    MemberExpression(path) {
        if (
            path.node.object &&
            path.node.object.name &&
            path.node.object.name == "_$YA"
        ) {
            path.replaceInline(types.valueToNode(_$YA[path.node.property.value]))
        } else if (
            path.node.object &&
            path.node.object.name &&
            path.node.object.name == "_$N4"
        ) {
            path.replaceInline(types.valueToNode(_$N4[path.node.property.value]))
        } else {}
    },
    CallExpression(path){
        if (
            path.node.callee &&
            path.node.callee.name &&
            path.node.callee.name == "_$I$" &&
            path.node.arguments &&
            path.node.arguments.length == 1 &&
            path.node.arguments[0].value

        ) {
            console.log(path.node.arguments[0].value)
            path.replaceInline(types.valueToNode(_$I$(path.node.arguments[0].value)))
        }
    }

})


let { code } = generator(ast, opts = { jsescOption: { "minimal": true } });
// 将js代码保存到文件
fs.writeFile(decode_file, code, (err) => { });
