
const parser = require("@babel/parser");
const traverse = require("@babel/traverse").default;
const types = require("@babel/types");
const { count } = require("console");
const generator = require("@babel/generator").default;
const fs = require("fs");
// 需要解码的文件1位置
let encode_file = "vm.js"
// 解码后的文件1位置
let decode_file = "decode_vm.js"
// 读取需要解码的js文件, 注意文件编码为utf-8格式
let jscode = fs.readFileSync(encode_file, { encoding: "utf-8" });
// 将js代码修转成AST语法树
let ast = parser.parse(jscode);


var _$QL =  [
    "href",
    "string",
    "=",
    "setAttribute",
    "?",
    "call",
    "prototype",
    "getAttribute",
    "type",
    "slice",
    "(",
    "submit",
    "search",
    "load",
    "floor",
    "1",
    "innerHTML",
    "https:",
    "protocol",
    "target",
    "onclick",
    "concat",
    "EkcP",
    "ej{rec{pkn",
    "|",
    "responseType",
    "localStorage",
    "replace",
    "toString",
    "status",
    "input",
    "form",
    "hidden",
    "pathname",
    "body",
    ".",
    "split",
    "userAgent",
    "onload",
    "addEventListener",
    "nodeType",
    ">",
    "style",
    "keyCode",
    "a",
    "onreadystatechange",
    "XMLHttpRequest",
    "location",
    "\"",
    "onerror",
    "action",
    "{",
    "eval",
    "charCodeAt",
    "#",
    "port",
    "appendChild",
    "script",
    "tagName",
    "getElementById",
    "removeEventListener",
    "test",
    "-",
    "readyState",
    "+=",
    "getElementsByTagName",
    "method",
    ",",
    "undefined",
    "responseText",
    ")",
    "indexOf",
    "function",
    ":",
    "clientData",
    "value",
    "onsubmit",
    "parentNode",
    "removeChild",
    "EventTarget",
    "src",
    "button",
    "&",
    "object",
    "apply",
    "name",
    ";",
    "splice",
    "event",
    "open",
    "g",
    "div",
    "cookie",
    "]",
    "/",
    "setInterval",
    "createElement",
    "ActiveXObject",
    "}",
    "showModalDialog",
    "HTMLAnchorElement",
    "\\r?\\n",
    "/:user_fonts",
    "; Secure",
    "uC9<vkeo|N;/D",
    "charset",
    "createDataChannel",
    "$b_platform",
    "q__{dd3bsods6bo{sP{dd3e{cd}{:C",
    "Object.InjectedScript.evaluate",
    "DeviceOrientationEvent",
    "loadXML",
    "lHL8iaWHL8ia",
    "Float32Array",
    "mozItems",
    "getResponseHeader",
    "screenX",
    "f__}mdq~m_~qzgpzo~[__r~{}mdq~m_~qzgpzo~[__n~g~idph_~qzgpzo~[__as}mdq~m_~qzgpzo~[__}mdq~m_pirmzkk~}[__r~{}mdq~m_pirmzkk~}[__n~g~idph_pirmzkk~}[__as}mdq~m_pirmzkk~}[__r~{}mdq~m_n|mdko_api|[__r~{}mdq~m_n|mdko_ai",
    "credentials",
    "visibility",
    "_",
    "dblclick",
    "onicecandidate",
    "Msxml2.XMLHTTP",
    "Msxml2.XMLHTTP.4.0",
    "ckqFgbbcl",
    "HIGH_INT",
    "TK_NUMBER",
    "FRAGMENT_SHADER",
    "_ts_",
    "Only one variable declaration allowed in for..in loop",
    "<span lang=\"zh\" style=\"font-family:mmllii;font-size:114px\">mmmmmmmmmmmlliii</span>",
    "clientY",
    "product",
    "i__o{xzjan{j_{nwdmwl{",
    "0000",
    "createBuffer",
    "u__ps|opyd__L_ps|opyd_>okno|9yno",
    "lineNumber",
    "msIndexedDB",
    "doNotTrack",
    "timeout",
    "fP>R~{@so[p|r~{",
    "response",
    "message",
    "import",
    "webstore",
    "]><i></i><![endif]-->",
    "getShaderPrecisionFormat",
    "boolean",
    "u}ovoxsaw",
    "sAt{owemdq4xmatPAt{owemdq4xmat",
    "m5bvfc{v (\\VOXU[]VS P;HpGApG7<QU",
    "0",
    "matches",
    "onbeforeunload",
    "disabled",
    "fractionalSecondDigits",
    "$b_fetchQueue",
    "j=vmz@xfeAvmv@ekzi{vxzWazj~fe",
    "OverrideMimeType",
    "getContext",
    "javascript\" r='m'>",
    "Submit",
    "TK_NAME",
    "compileShader",
    "debugger",
    "GetResponseHeader",
    "rangeMin",
    "wifi",
    "head",
    "toGMTString",
    "raz|pgQArny?ynhra 6U 2|{ca|y",
    "createShader",
    "loaded",
    "base",
    "3jeALeSsa6",
    "serverData",
    "_.LEAK_ALL",
    "PerformanceObserverEntryList",
    "mousedown",
    "T",
    "returnValue",
    "^((?:[\\da-f]{1,4}(?::|)){0,8})(::)?((?:[\\da-f]{1,4}(?::|)){0,8})$",
    "withCredentials",
    "sm||xuombu{zQfOat{owemdqOrxmat",
    "void",
    "absolute",
    "JavaException",
    "replaceState",
    "document",
    "shift",
    "d^\\$X|*w]a~_",
    "__anchor__",
    "i__yjO{xX__};jO{x",
    "\\b[^>]*>([\\s\\S]*?)<\\/",
    "false",
    "toDataURL",
    "enableVertexAttribArray",
    "Unterminated multiline comment",
    "DeviceMotionEvent",
    "﻿",
    "$_vvCI",
    "unicode",
    "textarea",
    "cloneNode",
    "enabledPlugin",
    "Unenclosed string.",
    "r#!#c #rrrErfcic9cbc%c&o;o|ExE3EQx?x{tqtktitAtVtvtNhPh9W[Jmi^i{HIHjH/A~prpopxpg1E1BsgVDVEV8V4YqY K9K%R{FBF.F|M3MQMPMNMaM^M*M>M{M]QOQ2Q)Q.Q|wswYwMw%w*8l8D8U8I8f8O828_8Z8@8*8=I5I^I<GEGtGAGYGRGdG!fWfpfYfUfRfQfBfSfTf~PuP_PZP5P~P]P OEOtOi9r9E9t9W9i999b9B9S9T2L2B2S2u2T2=2>bkb%b)b?vovhvPv9v7vSv6LRL(L NmN{N]N jmjojxjsjKjbjj->-}-]7G7Z7dXcX7X;X|BkBDBUBRB8BjB)aYaGa+a/S/S]n~n&u5u^000C0y0Z0@0&0)0<TMTwTGTOT$T^T(T=T:T[T CcCAC1C+C<C?C;64gEgUgLyOya~7~B~C~!!r!o!:@i@F@Q@I@X@d@.$D$Y$f$O$2$T%H^O&f&j&;*:(V(()W)H)s)I)(+o+J+&=k>~.Y.v.z?W?N/a/{:9:b:S:}{2[n]F#r]#rq9rqvrq7rqBrq}rq|rrkrrDrrJrrYrrurrCrcprcsrcRrcIrcfrcOrcNrczrcarcurcgrcerc)rc?rc:rc{rkqrl4rldrDkrDWrD1rDKrDOrDbrDLrDnrDTrDgrD5rD@r2nrborbxrb6rbyrb(rb+rb]rvqrLhrLvrL<rL|rNurN.rjhrjYrjMrjwrjOrj2rj-rjzrjurjTrj4rjerj$rj^rj=rj>rj{rS6rS4rS*rn$rn+rn<rn.ru.ru/ru{r0qr0Lr07rTarT@rCqrCyrC(mHVmQMmwCmG6mG4mG+mf1mfSmf0mf~mf:mPAmO6mOdmO@m9?mbAmbKmb3mbFmbQmbImbfmb6mb[mvBmv5mLKmNVmNBmN_mN/m- m7vm7dm7!m7$m7+ElVEoCEoyEEFEEGExaEx|EtlEtpEtYEtwEtbEtLEt0EtCEt_Et%Eh]EWIEA2EAgEp8EpfEp]E1bE1SEs>Es:Es{EYvEY<EKWEKsEK7EKgEU6EU4EU~EU$EU(EU=EU/EU{EU[",
    "final",
    "__#classType",
    "unshift",
    "lineNumber,columnNumber,fileName,line,column,description",
    "stopPropagation",
    "beta",
    "iframe",
    "fillRect",
    "//",
    "utf-8",
    "(^\\s*)|(\\s*$)",
    "return a[b](",
    "getItem",
    "chrome",
    "audio",
    "contextmenu",
    "DateTimeFormat",
    "LOW_FLOAT",
    "var getAttribute=function(name){return cur_ele.getAttribute(name);};",
    "acceleration",
    "originalTarget",
    "toUpperCase",
    "area",
    "jbscheme://queue_has_message",
    "bb82kj",
    "j8|:fekifcY8|:fekifc",
    "RegExp",
    "plugins",
    "maxTouchPoints",
    "^\\s+|\\s+$",
    "Intl",
    "%",
    "f JKM*",
    "Send",
    "__onload__",
    "(evaluating 'null[0]')",
    "getExtension",
    "fromCharCode",
    "oldConfirm",
    "mvf{jwf",
    "$_YWTU",
    "getRandomValues",
    "document-fragment",
    "|__695__-440_349.+.*7",
    "keyup",
    "https:\\\\",
    "Microsoft.XMLHTTP",
    "Unexpected token ",
    "wkitt:piv|wuJ_xpiv|wu",
    "none",
    "GetAllResponseHeaders",
    ">>>=",
    "HIGH_FLOAT",
    "detachEvent",
    "parse",
    "handler",
    "mouseup",
    "c",
    "; expires=",
    " srflx ",
    "content-type",
    "text",
    "Msxml2.ServerXMLHTTP.4.0",
    "getSupportedExtensions",
    "lastIndexOf",
    "ELECTRON_BROWSER_WINDOW_CLOSE",
    "webkitRequestFileSystem",
    "y__}khjxo|kx_yixovz_lt",
    "round",
    "clearInterval",
    "AudioTrackList,defaultStatus,Object.setPrototypeOf,taobrowser_Event,webkitRequestFileSystem,onoperadetachedviewchange,Path2D.prototype.addPath,SourceBuffer.prototype.changeType,weatherBridge,chrome.csi,password_manager_enabled,document.body.x-ms-acceleratorkey,external.AddFavorite,SogouLoginUtils,SourceBuffer,showModalDialog,document.selection.typeDetail,SVGPatternElement.SVG_UNIT_TYPE_OBJECTBOUNDINGBOX,document.onselectionchange,document.body.style.backgroundBlendMode,document.documentElement.onresize,CanvasRenderingContext2D.prototype.webkitGetImageDataHD,UCWebExt,CDATASection.prototype.remove,BlobDownloadCallback,_WXJS,document.msCapsLockWarningOff,CSSCharsetRule,document.scrollingElement.style.fontVariantNumeric,Function.prototype.bind,chrome.app.InstallState,isNodeWhitespace,Object.seal,document.defaultCharset,__firefox__,onmessage,__sogou_secure_input,CloseEvent.prototype.initCloseEvent,getMatchedCSSRules,Notification,HTMLFrameSetElement.prototype.hasPointerCapture,document.body.onmouseenter,OffscreenCanvasRenderingContext2D,chrome,Object.prototype.__defineSetter__,document.fileCreatedDate,webkitAudioContext.prototype.close,GetPerfTests,MediaController,external.IsSearchProviderInstalled,TextTrackList.prototype.getTrackById,document.selection,document.body.style.lineBreak,document.body.style.textAlignLast,ScreenOrientation,document.body.style.minWidth,SpeechSynthesisUtterance,onerror,WebKitFlags,ReaderModeArticlePage,__opera,PerformancePaintTiming,performance,document.body.style.msTextSizeAdjust,document.body.onpage,SVGGraphicsElement.prototype.mozRequestPointerLock,ClickData,MediaEncryptedEvent,__$_qihoo360_$__,document.onmousemove,BeforeInstallPromptEvent.prototype.KEYUP,HTMLFrameSetElement.prototype.webkitRequestFullScreen,external",
    "getAttribLocation",
    "P",
    "multipart/form-data",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "w-zw{{aits",
    "timeStamp",
    "QQBrowser",
    "height",
    "history",
    "<",
    "removeAttribute",
    "interface",
    "webkitPersistentStorage",
    "transient",
    "bgsound",
    "HTMLObjectElement",
    "switch",
    "assign",
    "f|z|c~_",
    "nodeName",
    "options",
    "nextSibling",
    "reset",
    "crypto",
    "'null' is not an object",
    "msDoNotTrack",
    "alpha",
    "use strict",
    "HTMLFormElement",
    "!",
    "TEMPORARY",
    "kcil}i}v}b}jow|ud{y",
    "uniform2f",
    "e$LnaQ?>nksoan?h{ooe}(Q?>nksoanIaoo{ca?ajpan",
    "shaderSource",
    "implements",
    "FLOAT",
    "<!--",
    "Msxml3.XMLHTTP",
    "addBehavior",
    "audio/ogg; codecs=\"vorbis\"|audio/wav; codecs=\"1\"|audio/mpeg;|audio/x-m4a;audio/aac;",
    "webgl",
    "setServerData",
    "with",
    "localDescription",
    "SELECT value FROM EkcP_t WHERE name=?",
    "click",
    "objectStore",
    "canPlayType",
    "fillStyle",
    "hostname",
    "resolvedOptions",
    "image",
    "number",
    "JSON",
    "\\b((submit)|(open)|(location)|(cookie)|(onsubmit)|(action)|(href)|(search)|(src)|(setAttribute)|(getAttribute))\\b",
    "behavior",
    "captchaRefresh,captcha_refresh,checkLogin,decryptCallback",
    "getBattery",
    "setTimeout",
    "position",
    "numItems",
    "hash",
    "clientX",
    "insertBefore",
    "Msxml2.XMLHTTP.6.0",
    "globalStorage",
    "decodeURIComponent",
    "dumpAll",
    "isNaN",
    "javascript: void(0);",
    "11.678",
    "Element",
    "locale",
    "toFixed",
    "x}pzpipsp{bjohunl",
    "bluetooth",
    "^href|pathname|search|host|hostname|port|hash|protocol$",
    "offsetTop",
    "$b_setup",
    "drawArrays",
    "display",
    "FileReader",
    "parseError",
    "Ajax response body is not encrypted - ",
    "layerY",
    "accelerationIncludingGravity",
    "()=>b",
    "wvm|{xizsmzJ__v{J__v{+xxmvl>mb|JmwAmj,zwa{mz",
    "(this);",
    "STATIC_DRAW",
    "mzd_{vwbh{x{wf",
    "mozIndexedDB",
    "acos",
    "select-",
    "width",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj-7zXBaSnu0TC6gy_4Ze5d~!@$%^&*()+=<>.?/:;{}[]| ",
    "createEvent",
    "rows",
    "layerX",
    "useProgram",
    "windows-1252",
    "version",
    "LOW_INT",
    "url(#default#userdata)",
    "package",
    "AnalyserNode",
    "char",
    "escape",
    "null",
    "de|jjboeb|ayal~rjbkq*~e|opbq)e|jjboeb|ayal~rjbkq*roi*obplisbo)e|jjboeb|aybibjbkq*ifpqbkfkd*bsbkqp*pqlo|db*molm)e|jjboeb|ayil~|qflk*to|mmbo",
    "complete",
    "\\\\",
    "vertexPosAttrib",
    "[",
    "HTMLEmbedElement",
    "prop",
    "v>xpx~",
    "native",
    "application/xml",
    "calendar",
    "text/html",
    "platform",
    "CREATE TABLE IF NOT EXISTS EkcP_t (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name))",
    "var cur_ele = this;",
    "onloadend",
    "origin",
    "=true",
    "\\r\\n?|[\\u2028\\u2029]",
    "source",
    "createProgram",
    "sy{hduaunuxubgotmzsq",
    "18px 'Arial'",
    "(color-gamut",
    "Msxml2.ServerXMLHTTP.3.0",
    "clear",
    "rR#r:ckcEE9Ebx[x]tWt1HP171zs_s+s=s{s}VhVQKhK.K?K}FuF&MiMHM7MzM?QrQ1QGQfQ0QTQ{Q}www8wGwfwOw9w)8%8^8?IxIRIFI(I)G1GsGwGZGeG:ftfGfffOf2fbfjf-f|O1OzOXOTOC9y2r2k2lbobjb-vXL+L=N~N!N$N&N*N)N<jhjJjAjpj3jRjOj7j@j$-JX!BtBiBHB6a<0%T{%u%g&}?6?g#2#rrHrrprrsrcMrlQrljrm}rDqrDirDwrDIrDfrD*roOro9rNer-=rShrSWrS!rS@rZuczXcXGmiamG[mG]m9;m9{mS@D]UEtMEtZEt5EtdEt!Et@",
    "h%axff|ka|x{%Y%m|lm<x}|<hk|%Y%m|lm<x}|=kbo|k%Y%m|lm<x}|B}kxf|=kbo|k%Y%m|lm<x}|:nmhfxmbhg%",
    "; path=/",
    "description",
    "referrer",
    "/T7AyTrxoWxGd",
    "#f82",
    "unexpected number ending.",
    "xwalk",
    "http://",
    "clientInformation",
    "uniformOffset",
    "$_nd",
    "evaluate",
    "bufferData",
    "QTP_EPE_HOOK",
    "orientation",
    "Msxml2.XMLHTTP.3.0",
    "offsetLeft",
    "~",
    "TouchEvent",
    "webkitConnection",
    "$b_onNativeResponse",
    "j <y|Z",
    "catch",
    "linkProgram",
    "Response-Type",
    "getClientDataInCookie",
    "Abort",
    "close",
    "HTMLGenericElement",
    "datas-ts",
    "http-equiv",
    "attachShader",
    "w{mtmvq}uKm~it}i|m",
    "1.234",
    "byte",
    "$_fr",
    "WebSocket",
    "https://",
    "const",
    "pushState",
    "android",
    "t@tx5pt(@tx@by(;@tx@by(3lyr@zyr(8ltAt(3lyr@zyr4/STRS(8ltAt4/STRS(:tn}z~zqa Fl5pt(5t}lrtyz @ly~ 4/(@A5ptat 9trsa(@A5ptat(@A8ltat(@A@zyr(@A3lyr~zyr(9t@b(FzbFbly(@AEtspt(@AGszyr~zyr(3G@sbAt(3GFlzat(@A0ltfby(@A5b{z(@A9tat(@AEtyrvlt(@AEtydpt(",
    "hardwareConcurrency",
    "checkbox",
    "touches",
    "a=candidate:",
    "<div>IE8</div>",
    "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj.7zXBaSnu0TC6gy_4Ze5d{}|~ !#$%()*+,-;=?@[]^",
    "refresh",
    "public",
    "Gamepad",
    "onprogress",
    "srgb|p3|rec2020|any",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "removeItem",
    "$_vJTp",
    "exec",
    "'",
    "onsuccess",
    "save",
    "cY#rDABASAnA0ATA61Xs<s>VwR;FnF$F%F MqM8MIMGQqQhQWQHQAQpQMQbQvQ^Q&Q*wvw7wzwnwuwZ8c8k8o8s8V8Y8.IqIrIcIlImIDIMIQI_I4IZGQG8GIGGGvGLG-G7GzGCG6G@G$fxf^f&f*f(f)f}PmOjO-O6OgO|O 9g9_949@9$9%9&9*9(9)9:9;2m2D222bbUbfb7bzb<b>v4v*LtLhL)jUjfjP-2-b-@-%-&-=-<7u7_74zfXzXXXuX_X4XZXeX5XdX~X BqBrBcB-B7BzBXBBBCBgB&6~$o$E$v$L%1%P%O%9%y&{(I(G(L(N(j+i+H=l=m=@=$=%=>=.=?=/=:<s>d.K.U.w.8.9.2.b?x?t?h?j?B?a?S?n?u:h:W:J:i{D{1{U#!#rkArkprk$rk%rk rmurn&rn*mf!mf.mf?mOAmOpmbUmbMmbGmbgmbymb_mb4mbZmvZmvemLvmjkmjlmj0m-hm-Wm-Jm-1m-sm-Vm7Xm7Bm7am7Sm7nm7um70m7Tm7@m7=m7<mzfmz]mXlmXmmXhmXWmXimS2mSbmSvmSLmSNmSjmS-mS7mSXmSBEtQEsAEspEKp",
    "goto",
    "SEND",
    "length",
    "super",
    "double",
    "80",
    "OBJECT",
    "r<|i0}}rnan{pr",
    "throw",
    "time",
    "typeof",
    "overrideMimeType",
    "b;naidbs hc<\"aa71ji\" bk~rrhc<\"bkrhc92/4/e708,87a4,00be,aa71,//~~//acbd/a\" vhcsg<\"/ow\" gdhfgs<\"/ow\"=;.naidbs=",
    "frames",
    "rangeMax",
    "http:",
    "sessionStorage",
    "bottom",
    "[;&]",
    "onautocomplete",
    "func",
    "preventDefault",
    "gkz_zlc|a}Zkzziiemb}f~",
    "srcElement",
    "then",
    "class",
    "screenY",
    "r7rnqyrbb2ua|zr",
    "anchor",
    "i$~ggc$X$$dg}}{jX$$dkhX$$dkjxX$~zp$X$j{wzq;gz{9dj{wzq=p{yml{zAfL~ak>jwe{X$kzp$X$ma{$",
    "}tqqvEjcoogtjgcfEujcfqyEwk",
    "toLowerCase",
    "captureStackTrace",
    "f$",
    "<EMBED id=",
    "parseInt",
    "getUniformLocation",
    "private",
    "canvas",
    "onupgradeneeded",
    "getSources",
    "text/javascript",
    "\\{(.+?)\\}",
    "GetOriginalUrl",
    "setTime",
    "ownerElement",
    "characterSet",
    "timeZone",
    "phtqscxgtcRtgp{fpet",
    "setItem",
    "Missing catch/finally blocks",
    "runtime",
    "getAllResponseHeaders",
    "#17e",
    "Msxml2.ServerXMLHTTP",
    "MediaStreamTrack",
    "touchmove",
    "gu\\mX\\Uhyncp} {i|}\\]\\mXw",
    "PerformanceObserver",
    "throws",
    "MEDIUM_INT",
    "ceil",
    "try{return __filename;}catch(e){}",
    "Unenclosed regular expression.",
    "tdpmvta5toopy",
    "5",
    "mousemove",
    "i<>H~{dn{layw3Lax{lwf Ewy~af{ Mfa3;ggdbwrr3N{jzwfw3@{dn{layw F{m{ DL Hjg +- L~af3lw~gew3D? Kewjl_@ l{kl J{}mdwj3<AFHjgYda}~l3@{dn{layw DL ,+ Da}~l =pl{fz{z3@{dn{E_Afzaw3K=;JgxglgDa}~l :gdz3GJ Eg~wflq Mfaygz{ J{}mdwj3<jgaz Kwfk L~wa3Cwffwzw Kwf}we EF3<<; My~{f3ydgyc*()._n)Z)3Kwekmf}CwffwzwJ{}mdwj3EA D9FLAF? :gdz3Kwekmf}KwfkFme+D Da}~l3n{jzwfw3@{dn{laywF{m{L~af3K=;>wddxwyc3Kwekmf}=egba3L{dm}m Kwf}we EF3;wjjgak ?gl~ay K;3>dqe{ Da}~l Jgxglg Da}~l3KgE9Y<a}al Da}~l3KgE; Kwfk J{}mdwj3@QPaQmwfB3kkl3kwekmf}YkwfkYfme,L3}e_e{f}e{f}3Dg~al Cwffwzw3lae{k f{o jgewf3kwekmf}YkwfkYfme,D3k{ja|Yegfgkhwy{3Kwekmf}KwfkFmeY+L L~af3;gdgjGKMAYPL~af3<jgaz Fwkc~ K~a|l 9dl3Kwekmf}L{dm}mJ{}mdwj3:{f}wda GLK3EA DwfLaf}_?: Gmlkaz{ QK3>REawgOm_?:)0(+(3~{dn{Yf{m{Yj{}mdwj3KKL E{zame3;gmja{j F{o3C~e{j Egfzmdcaja :gdz3@{dn{layw DL *+ Mdljw Da}~l =pl{fz{z3@{dn{layw DL *- Mdljw Da}~l3Jgxglg E{zame3<jgaz Kwfk :gdz3}gmzq3kwfkYk{ja|Yygfz{fk{zYda}~l3K>afz{j3fglgYkwfkYybcYe{zame3eama3EJgycq HJ; :gdz39fzjgaz;dgyc J{}mdwj3Kwekmf}KwfkFmeY,D Da}~l3kwfkYk{ja|Yl~af39wHwf}Qw{j3ywkmwd3:F Eg~wflqGL :gdz3pYkkl3FglgKwfkEqwfewjRwo}qa3@{dn{layw DL ++ L~af =pl{fz{z39k~d{qKyjahlEL 9dl3Fglg Kwfk <{nwfw}wja MA3Jgxglg ;gfz{fk{z :gdz3Jgxglg E{zame Alwday3eama{p3Fglg Kwfk ?mjemc~a MA3KKL Na{lfwe{k{ Da}~l3D?_Gjaqw3~qyg||{{3pYkklYmdljwda}~l3<>@{a9O/Y93>RROP:LGL_Mfaygz{3<{nwfw}wja Kwf}we EF :gdz3kwfkYk{ja|Yegfgkhwy{3Hwzwmc :ggc :gdz3D?Y>RQaf}:aCwaK~mYK)-YN*Z*3D?Y>RQaf}:aCwaK~mYK)-YN*Z+3@{dn{laywF{m{DL Hjg +- L~3Eayjgkg|l @aewdwqw3Kwekmf}Kwfk>wddxwyc3KKL E{zame Alwday39fzjgaz=egba3Kwekmf}KwfkFmeY+J3AL; Klgf{ K{ja|3kwfkYk{ja|Ykewddywhk3pYkklYe{zame3D?_Kaf~wd{k{3Jgxglg L~af Alwday3y{flmjqY}gl~ay3;dgycghaw3Dmeafgmk_Kwfk3>dgjazawf Kyjahl 9dl3Fglg Kwfk ?mjemc~a :gdz3DL@QKRC :gdz3?K_L~wa3Kwekmf}F{gFme_+L_*39jwxay3~wfkYkwfkYfgjewd3Dg~al L{dm}m3@QIa@{aY-(K Da}~l3Dafzk{q |gj Kwekmf}39J ;jqklwd~{a <:3Kwekmf} Kwfk E{zame3kwekmf}YkwfkYfme,-3~wfkYkwfkYxgdz3Dmeafgmk_Kyjahl3KKL ;gfz{fk{z3Kwekmf}<{nwfw}wjaJ{}mdwj39fbwd Ewdwqwdwe EF3Kwekmf}L~waTl{klU3>RDwfLaf}@{aYEY?:)0(+(3@{xj{o GLK3?K,-_9jwxT9fzjgazGKU3Kwekmf} Kwfk Da}~l3;~gyg yggcq3~{dn{Yf{m{Yl~af3HF Eg~wflqGL E{zame3D?Y>RCwLgf}YE)1YN*Z,3<jgaz K{ja|3Kwekmf}Kaf~wdwJ{}mdwj3~{dn{layw3D?Y>RCwLgf}YE)1YN*Z*3Fglg Kwfk <{nwfw}wja MA :gdz3KKL Da}~l3<>H=egba3o{wl~{j|gflf{o J{}mdwj3JgxglgFme+J3<AFHjgYe{zame3Kwekmf} Kwfk Fme--3KKL @{wnq Alwday3D?dgyc, J{}mdwj_(0(-3?{gj}aw3fglgYkwfkYybc3L{dm}m Kwf}we EF :gdz3EAMA =P Fgjewd3@QIa@{aY/-K :gdz3FglgKwfkEqwfewjRwo}qa :gdz3qmfgkhjgYxdwyc3~{dn{Yf{m{Yfgjewd3Dmeafgmk_K{ja|3LE Eg~wflqGL Fgjewd3Kwekmf}KwfkFmeY+Dn Da}~l3Kwekmf} Kwfk Fme,-3Kewjl?gl~ay E{zame3}{gj}aw3ywkmwdY|gflYlqh{3Kwekmf} Kwfk :gdz3kewddYywhalwdk3E>afwfy{ HJ; :gdz3>RDwfLaf}@{a_?:)0(+(3Kwekmf}9je{fawf3Jgxglg :gdz3y{flmjqY}gl~ayYxgdz3pYkklY~{wnq3KKL Da}~l Alwday3L~wjDgf3pYkklYda}~l3<afxgd J{}mdwj3Kwekmf}:{f}wdaJ{}mdwj3CF Eg~wflqGLKewdd E{zame3~qhmj{3Kwekmf}LweadJ{}mdwj3Ewdwqwdwe Kwf}we EF3Fglg Kwfk Cwffwzw MA3~{dn{Yf{m{3@{dn{layw DL -- Jgewf3Fglg Kwfk Cwffwzw :gdz3Kwfhqw3Kwekmf}HmfbwxaJ{}mdwj3kwekmf}YkwfkYfme,Dn3D?_Cwffwzw3Kwekmf} Kwfk J{}mdwj3Rwo}qaYGf{3<jgaz K{ja| :gdz Alwday3>RC9LBO3ygmja{j f{o3Kwekmf}=egbaJ{}mdwj3EAMA =P :gdz39fzjgaz =egba3Fglg Fwkc~ 9jwxay MA3D;< ;ge3>mlmjw E{zame :L3NangY{pljwyl3:wf}dw Kwf}we EF :gdz3~wfkYkwfkYj{}mdwj3KFmeY+J3KFmeY+L3~wfkYkwfk3KKL Mdljw Da}~l3Jgxglg J{}mdwj3Jgxglg Da}~l3@wfmewf3f{od}}gl~ay3<>@{a9O-Y93~wfkYkwfkYda}~l3Hdwl{ ?gl~ay3KFmeY+D3@{dn{layw DL ,- Da}~l3Eqwfewj Kwf}we Rwo}qa :gdz3d}YkwfkYk{ja|Yda}~l3EAMA =P Da}~l3Jgxglg L~af3KgE9 :gdz3Hwzwmc3Kwekmf} Kwfk3Khwyagmk_Kewdd;wh3kwfkYk{ja|3<N Eg~wflqGL E{zame3Klwxd{_Kdwh3egfwyg3>dqe{YDa}~l3|rrqkYzgkhq3Kyj{{fKwfk3ydgyc*().3Jgxglg ;gfz{fk{z :gdz Alwday39jawd3CF Eg~wflq E{zame3EglgqwDEwjm O+ egfg3@wfzk{l ;gfz{fk{z3Jgxglg Alwday3@L; @wfz3KKL Mdljw Da}~l Alwday3KKL Na{lfwe{k{ Jgewf3Fglg Fwkc~ 9jwxay MA :gdz3y~f|rp~Ye{zame3KFme;gfzY+L3y{flmjqY}gl~ayYj{}mdwj3z{|wmdl_jgxglgYda}~l3Fglg Kwfk Eqwfewj3Eqwfewj Kwf}we EF39hhd{ ;gdgj =egba3o{wl~{j|gflJ{}3Kwekmf}EwdwqwdweJ{}mdwj3wjawd3<jgaz K{ja| :gdz3;Hg+ HJ; :gdz3EA D9FLAF?3Kwekmf}Cgj{wfYJ{}mdwj3l{kl,- J{}mdwj3khajal_lae{3<{nwfw}wja Kwf}we EF3Kyj{{fK{ja|3Jgxglg3ymjkan{Y|gflYlqh{3KL@{ala_nang3y~f|rp~3Kwekmf} ;dgyc>gfl +93Jgxglg ;gfz{fk{z J{}mdwj3kwekmf}Yf{gYfme+J3?B Eg~wflqGL E{zame3;~md~g F{m{ Dgyc3jgxglgYfme+D3~{dn{Yf{m{YmdljwDa}~l{pl{fz{z3Kwekmf}GjaqwJ{}mdwj3Kwekmf}KwfkFmeY,Dn Da}~l3EQaf}@{a_)0(+(_;*Y:gdz3<>HK~wgFnO-Y?:3Jgxglg :dwyc3~{dn{Yf{m{Ymdljwda}~l3}e_pa~{a3D?dgyc, Da}~l_(0(-3?mbwjwla Kwf}we EF3Ewdwqwdwe Kwf}we EF :gdz3jgxglgYfme+J3KLPa~{a_nang3>RR~mfQmwf_?:)0(+(3fglgYkwfkYybcYda}~l3ygdgjgk3Fglg Kwfk ?mjemc~a3Fglg Kwfk Kqexgdk3Jgxglg Da}~l Alwday3Dg~al Lwead3ymjkan{3z{|wmdl_jgxglg3:~wk~alw;gehd{pKwfk :gdz3D?_Fmex{j_Jgxglg L~af3egfgkhwy{zYoal~gmlYk{ja|k3@{dn{layw DL +- L~af3kwekmf}YkwfkYfme+DN3<AFHjg3Bgegd~wja3kwfkYk{ja|Yda}~l3~{dn{Yf{m{Yxdwyc3Dg~al :{f}wda3Eqwfewj Kwf}we Rwo}qa3<jgaz K{ja| Alwday3Jgxglg :gdz Alwday3Fwfme?gl~ay3Kgfq Egxad{ M< ?gl~ay J{}mdwj3?{gj}aw :gdz Alwday3kwekmf}YkwfkYfme+Dn3qmfgkYl~af3kwekmf}Yf{gYfme+LYygfz3Fglg Kwfk Eqwfewj MA :gdz3d}k{ja|3>RQgm@{aYJY?:)0(+(3Dg~al Hmfbwxa3xwkc{jnadd{3kwekmf}YkwfkYfme,Ln3kwekmf}YkwfkYl~af3D? =egba39fbwdaF{oDaha3Kwekmf}KwfkFmeY,L L~af3Kwekmf}Cgj{wfY:gdz3eama{pYda}~l3Fglg Kwfk Cwffwzw3Jgxglg Fgjewd Alwday3?{gj}aw Alwday3kwfkYk{ja|Ye{zame3Kewjl Rwo}qa3Jgxglg ;gfz{fk{z Alwday3Fglg Kwfk Cwffwzw MA :gdz3<>H Ky Kwfk @{m{+(_)(+3D?_Fmex{j_Jgxglg :gdz3Hwzwmc :ggc3pYkklYygfz{fk{z3Kmfk~af{YMy~{f3Jgxglg :dwyc Alwday3Jaf}g ;gdgj =egba3<{nwfw}wja GLK3Kewjl Rwo}qa Hjg3>RDwfLaf}@{aYEY?:C39fzjgaz;dgycYDwj}{ J{}mdwj3hjghgjlagfwddqYkhwy{zYoal~gmlYk{ja|k3;mlan{ Egfg3lae{k3D? Kewjl_@ l{kl :gdz3<AFHjgYDa}~l3kwfkYk{ja|Yxdwyc3Dg~al <{nwfw}wja3hjghgjlagfwddqYkhwy{zYoal~Yk{ja|k3kwekmf}YkwfkYfme+D3EQgmf} HJ; E{zame3<>?gl~ayHO-Y:A?-@CYKGFQ3~wfkYkwfkYe{zame3KKL @{wnq3D?Y>RR~mfQmwfYE(*YN*Z*3EqwfewjMF{o J{}mdwj3Fglg Fwkc~ 9jwxay :gdz3Kwekmf}?mbwjwl~aJ{}mdwj3|wflwkq3~{dn{Yf{m{Yda}~l3@{dn{layw F{m{ GLK :gdz3fglgYkwfkYybcYxgdz3kwekmf}YkwfkYfme+J3Dafzk{q Kwekmf}3kwekmf}YkwfkYfme+L3Kyj{{fK{ja|Egfg3=Ljmeh Eqwfewj_RO3~{dn{Yf{m{Yl~af{pl{fz{z3Fglg Fwkc~ 9jwxay3D?_?mbwjwla3Kewjl_Egfgkhwy{z3Lwead Kwf}we EF3D? =egba Fgf9E=3Jgxglg ;gfz{fk{z Da}~l Alwday3}e_baf}cwa3>RDwfLaf}Cwf@{a_?:)0(+(3d}ljwn{d3hwdwlafg3?{gj}aw :gdz3<jgaz Kwfk3D?_Hmfbwxa3Kewjl?gl~ay :gdz3Kwekmf} Kwfk L~af3KKL ;gfz{fk{z :gdz3;geayk_Fwjjgo3ygmja{j3Gjaqw Kwf}we EF3~{dn{Yf{m{Yda}~l{pl{fz{z3>RDwfLaf}@{aYJY?:)0(+(39J ;jqklwd~{a@CK;K <:3k{ja|3JLOKQm{Jgmz?g?(n)YJ{}mdwj3EawgOm_hj{n3>RQ)C3D?_Fmex{j_Jgxglg J{}mdwj39fzjgaz;dgyc3KgE9 J{}mdwj3@QIa@{aY,(K Da}~lp3d}YkwfkYk{ja|3<wfyaf} Kyjahl :gdz3z{|wmdl3k{yYjgxglgYda}~l3;gdgjGKMAYJ{}mdwj3l{kl J{}mdwj3Lwead Kwf}we EF :gdz3>RQaf}:aPaf}K~mYK).3JgxglgFme+D Da}~l3egfgkhwy{zYoal~Yk{ja|k3kwekmf}YkwfkYfme+-3;ggd bwrr3Kwekmf}F{gFmeY+D3KLPaf}cwa3Kyj{{fKwfkEgfg3<>HOwOwO-Y?:3Kwekmf}KwfkFmeY+D Da}~l3:wf}dw Kwf}we EF3?mjemc~a Kwf}we EF3K=;JgxglgDa}~l3~q|gfpjwaf3EQaf}@{a?:)0(+(;Y:gdz3kwekmf}YkwfkYda}~l3@{dn{layw DL .- E{zame3<jgaz Kwfk >wddxwyc3Jgxglg L{kl) :gdz3Fglg Kwfk Eqwfewj :gdz3kwfkYk{ja|Yygfz{fk{zYymklge3Kwekmf}F{gFmeY+L3Kwekmf} Kwfk Fme+-3egfgkhwy{3LD Eg~wflq E{zame3~{dn{Yf{m{Ye{zame3DL@QKRC3Jgxglg ;gfz{fk{z ymklge{ :gdz3Eqwfewj+3<jgaz Kwfk <{nwfw}wja3K~wgFn_hj{n3kwekmf}Yf{gYfme+D3>RDwfLaf}@{aY=DY?:C3qmfgk3kwekmf}Yf{gYfme+L3Lae{k F{o Jgewf3~{dn{Yf{m{Yxgdz3fglgYkwfkYybcYj{}mdwj3Fglg Kwfk ?mjemc~a MA :gdz3<AFHjgYxdwyc3>RDwfLaf}@{aY=DY?:)0(+(3KKL Na{lfwe{k{ E{zame3Jgxglg ;gfz{fk{z Da}~l3KKL Na{lfwe{k{ :gdz39J <BYCC3<jgaz Kwfk K=E;3Fglg Kwfk Eqwfewj MA3;geaf} Kggf3EQmhhq HJ; E{zame3Jgk{ewjq3Dg~al ?mbwjwla3Jgxglg ;gfz{fk{z ymklge :gdz3>RDwfLaf}@{aKYJY?:3@{dn{layw F{m{ GLK3Cwala_hj{n3JgxglgY:a};dgyc3>RQ:CKBO3@wfzk{l ;gfz{fk{z :gdz3Kwekmf}?{gj}awf3<wfyaf} Kyjahl3kwfkYk{ja|Yygfz{fk{z3~wfkYkwfkYl~af3Kwekmf}KwfkFmeY,Ln L~af3Dg~al Gzaw3:~wk~alw;gehd{pKwfk",
    "fonts",
    "battery",
    "t:tn}z:p~~pyrp}",
    "m",
    "[\\\\\\\"\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u0600-\\u0604\\u070f\\u17b4\\u17b5\\u200c-\\u200f\\u2028-\\u202f\\u2060-\\u206f\\ufeff\\ufff0-\\uffff]",
    " height=6 width=1 type=application/x-shockwave-flash src=",
    "javascript:",
    "setRequestHeader",
    "Msxml2.ServerXMLHTTP.6.0",
    "___ts___",
    "onabort",
    "Z8XHJJY.bmF0aXZlRmlVyUHJ()",
    "DispatchEvent",
    "send",
    "matchMedia",
    "ARRAY_BUFFER",
    "pushNotification",
    "post",
    "VERTEX_SHADER",
    "([0-9]{1,3}(\\.[0-9]{1,3}){3}| (([0-9a-f]{1,4}:){7,7}[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,7}:|([0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}|([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}|([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}|([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:((:[0-9a-f]{1,4}){1,6})|:((:[0-9a-f]{1,4}){1,7}|:)|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])) )",
    "errorCode",
    "transferChannel",
    "fillText",
    "true",
    "nodeValue",
    "}ygdftkxgt",
    "external",
    "preload",
    "{             \"iceServers\" : [                 {\"url\" : \"stun:stun01.sipphone.com\"}, {\"url\" : \"stun:stun.ekiga.net\"},                 {\"url\" : \"stun:stun.fwdnet.net\"}, {\"url\" : \"stun:stun.ideasip.com\"},                 {\"url\" : \"stun:stun.iptel.org\"}, {\"url\" : \"stun:stun.rixtelecom.se\"},                 {\"url\" : \"stun:stun.schlund.de\"}, {\"url\" : \"stun:stun.l.google.com:19302\"},                 {\"url\" : \"stun:stun1.l.google.com:19302\"}, {\"url\" : \"stun:stun2.l.google.com:19302\"},                 {\"url\" : \"stun:stun3.l.google.com:19302\"}, {\"url\" : \"stun:stun4.l.google.com:19302\"}             ]         }",
    "result",
    "vlaue",
    "constructor",
    "Entity",
    "alert",
    "XMLHttpRequestEventTarget",
    "replaceChild",
    "self",
    "offsetY",
    "\r\n",
    "default",
    "else",
    "encoding",
    "t.n}z=13O=13",
    "setClientData",
    "appVersion",
    "Count",
    "bcduhbdlnshnm",
    "mediaDevices",
    "objectStoreNames",
    "RTCPeerConnection",
    "yield",
    "substring",
    "abort",
    "host",
    "eio?na~ajpe{ho",
    "getFrameLocation",
    "TK_STRING",
    "item",
    "break",
    "enum",
    "getServerDataInCookie",
    "arity",
    "bQd~kOk~xdq-Qd~kOk~xdq[sl( @bshudW Bnmsqnk [21,ahs(",
    "$b_onBridgeReady",
    "this",
    "Msxml.XMLHTTP",
    "@debugger",
    "itsgonnafail",
    "nvkcvez~vagr}",
    "$bmF0aXZlRmlVyUHJ",
    "textBaseline",
    "delete",
    "Number",
    "i",
    "responseXML",
    "mozConnection",
    "AddSearchProvider",
    "connection",
    "forEach",
    "*",
    "http",
    "long",
    "candidate",
    "touchend",
    "<meta\\s+http-equiv=[\"']?refresh[\"']?\\s",
    "volatile",
    "fileName",
    "include",
    "offsetWidth",
    "video/ogg; codecs=\"theora\"|video/mp4; codecs=\"avc1.42E01E\"|video/webm; codecs=\"vp8, vorbis\"|video/mp4; codecs=\"mp4v.20.8, mp4a.40.2\"|video/mp4; codecs=\"mp4v.20.240, mp4a.40.2\"|video/x-matroska; codecs=\"theora, vorbis\"",
    "cookieEnabled",
    "s~y{ofP@qmx>xmgq~ 5T 1{zb~{xPS",
    "unescape",
    "month",
    "Msxml2.ServerXMLHTTP.5.0",
    "data",
    "while",
    "opener",
    "itemSize",
    "getParameter",
    "y",
    "parent",
    "stack",
    "left",
    "Name expected",
    "TRIANGLE_STRIP",
    "radio",
    "Z8XHj",
    "attributes",
    "llxu~|ik|h|u|a|inv{tczx",
    "kyn}j<kbbiwhyyd",
    "readwrite",
    "^(\\[object|function) Location\\b",
    "video",
    "ontouchstart",
    "level",
    "firstChild",
    "cygJ+",
    "children",
    "content",
    "vdFm",
    "Unexpected character: ",
    "e__jecdpi{na",
    "$_ff",
    "languages",
    "POST",
    "touchstart",
    "year",
    "Math",
    "extends",
    "executeSql",
    "$_JQnh",
    "$_ts",
    "openDatabase",
    "protected",
    "scroll",
    "s1t~{yq\\QJ\\pMK",
    "return",
    "jbscheme://",
    "rqrevpr|avr{cncv|{",
    "HTMLElement",
    "text/xml",
    "capture",
    "keydown",
    "numberingSystem",
    "hasOwnProperty",
    "rgba(240,110,53,0.4)",
    "(any-hover",
    "onloadstart",
    "_DIV",
    "Microsoft.XMLHTTP.1.0",
    "qb}}d",
    "bindBuffer",
    "webkitRTCPeerConnection",
    "MEDIUM_FLOAT",
    "createOffer",
    "; SameSite=None",
    "continue",
    "b",
    "oldPrompt",
    "stringify",
    "client error",
    "INSERT OR REPLACE INTO EkcP_t (name, value) VALUES(?, ?)",
    "attrVertex",
    "safari",
    "CallSite",
    "password",
    "Keyboard",
    "documentElement",
    "Ajax response body CRC failure - ",
    "DOMParser",
    "wlzq~mzKm~it}i|m",
    "appName",
    "parsererror",
    "\u0000",
    "$_fpn1",
    "outerHTML",
    "performance",
    "Function",
    "</$1",
    "link",
    "statusText",
    "parentElement",
    "return new a(",
    "error",
    "shenjian",
    "mimeTypes",
    "cancelBubble",
    "Illegal newline after @throw",
    "standalone",
    "enable_",
    "Open",
    "http:\\\\",
    "try{return __dirname;}catch(e){}",
    "^(\\[object) Location|Object|DOMPrototype]",
    "Storage",
    "lutwudn",
    "mouseleave",
    "offsetHeight",
    "responseBody",
    "vertexPosArray",
    "selected",
    "jJbpgzY;zkzxk~fe",
    "$b_callHandler",
    "experimental-webgl",
    "responseURL",
    "Call",
    "callback",
    "match",
    "enumerateDevices",
    "function fetch() { [native code] }",
    "unload",
    "lineno",
    "cv",
    "applicationCache",
    "execScript",
    "cPc}jNj}wcp",
    "Request",
    "PointerEvent",
    "var submit=function(){for(var t=cur_ele;t!==document&&(!t.tagName||\"form\"!==t.tagName.toLowerCase());)t=t.parentElement;t!==document&&t.submit()};",
    "}4(*F4fh[vtn",
    "instanceof",
    "+",
    "hU}ngzmbhgUV toxk x 6 g|p =xm|UV4 {|yn~~|k4 k|mnkg g|p =xm|UV Z x 7 *))4vUVV",
    "parseFromString",
    "indexedDB",
    "getBoundingClientRect",
    "finally",
    "$_f1",
    "Uint8Array",
    "u?o9yl2svv2y|w@yyvL?yqya9}o",
    "jyfcg}~eWyfcg}~e~e{fWyfcg}~edzkv",
    "float",
    "deviceId",
    "[native code]",
    "(any-pointer",
    "offsetX",
    "setLocalDescription",
    "^(?:\\d{1,3}(?:\\.|$)){4}",
    "tests",
    "TK_REG_EX",
    "vertexAttribPointer",
    "static",
    "data:",
    "frame",
    "internal",
    "msCrypto",
    "|_8hohqlxp_.)*_7hfrughuE_vhohqlxpEfdoo8hohqlxp",
    "productSub",
    "GetNextReqID",
    "createObjectStore",
    "filename",
    "$_fh1",
    "Please enable cookie in your browser before you continue.",
    "synchronized",
    "short",
    "Infinity",
    "random",
    "Unexpected token: ",
    "Msxml.DOMDocument",
    "offsetUniform",
    "parseFloat",
    "suffixes",
    "try{return (window instanceof Window);}catch(e){}",
    "443",
    "precision",
    "checked",
    ":\\d+",
    "fontFamily",
    "_blank",
    "gamma",
    "hover|on-demand|none|any",
    "$_f0",
    "dispatchEvent",
    "nfcz_ybb|vuS~bm4az~rgzbaFgregGz~vS~bm<auvkvu75S~bmEvdhvfg4az~rgzba9er~v",
    "c#r*^p#H#rklrkmrkDrkorkErkxrktrkhrkWrkJrkirkHrkurltrSD",
    "ownerDocument",
    "jIzvcM~yzfYIzvcM~yzfSkdT 8xk~mzO :fekifc S*)Xw~kT",
    "write",
    "fetch",
    "[object Array]",
    "ethernet",
    "abstract",
    "isFinite",
    "export",
    "[null] is not an object",
    "MSPointerEvent",
    "qo~~Cqo|3zwqyPo~~Cqo|6}qec?edPo~~Cqo|;si4}g|Po~~Cqo|;siE~Po~~Cqo|Cs|rBs~zoqs{s|dPo~~Cqo|?|BsoriCdods3vo|usBs~zoqs{s|dPo~~Cqo|<}or8o|rzsbPo~~Cqo|Csd@ous<}orsr",
    "defaultPrevented",
    "~:fc;0/ph0th_81,48(_",
    "wimax",
    "chargingTime",
    " host ",
    "right",
    "mozRTCPeerConnection",
    "Ajax response body replay - ",
    "mouseenter",
    "trim",
    "cookie disabled",
    "oldAlert",
    "font",
    ", expected ",
    "oscpu",
    "r[#Egx.W|JcArAzpvpS1x1Qs4s!s%s)s?s;VZV]KqKtK^K>UUUFUQU9UbULUjUXR?R:F0FCF6F5FdF@F*F=QcQlQmQEwNw-wCwg8/8;8{8|GfG9f>f?f:f{PBPSOsOYOKOROMOwOIOP9Z9~bEbtbhbibAb1bVbKv~v@v$v^v)v/L<L;NDNJjFjIjXju727n707g7%7=7>zUXBXnX0XyBoBxBhBJBABKBFBwBaBTB$B^@G@P@~@@%s%R%F%f%2%B^i^A(3(F(M(8(f(O(-(a(S(u)?+D=D=E=^===;<q<r<D<o<A>4>5.3.Q.I.O.>.[?-?X/}:c:k:t;.;/;;{m{o{J[u]q]U]R#P#rmPrmXrm6rm@rLKrL3rj[r-MrSarSTmLUmLbmL$mL}mNamN6mN:mjcmjSmjum-im-pm-Ym-3m7Lm7zmz mXrE1CE1^E1]EskEsjEs7",
    "fine|coarse|none|any",
    "transaction",
    "OPEN",
    "r",
    "cOsgaiRgkc,OsgaiRgkc",
    "<!--[if gt IE ",
    "enctype",
    "ontimeout",
    "charging",
    "case",
    "n~bm;zuuva",
    "elements",
    "function clearInterval() { [native code] }",
    "SetRequestHeader",
    "$_config__.detail__ += 1",
    "contains",
    "webkitIndexedDB",
    "charAt",
    "attachEvent",
    "Msxml2.XMLHTTP.5.0",
    "async",
    "(near '... null[0]...')",
    "getTime",
    "$_cDro",
    "cpuClass",
    "Ajax response body decryption failed - ",
    "Mouse",
    "GetVariable",
    "cellular",
    "msMaxTouchPoints",
    "meta",
    "substr"
]

var _$Gx = Array

_$Sd = String.fromCharCode

function _$Oq(_$z8) {
    var _$HU = _$z8.length;
    var _$CJ, _$4O = new _$Gx(_$HU - 1), _$9z = _$z8.charCodeAt(0) - 97;
    for (var _$Bl = 0, _$Ub = 1; _$Ub < _$HU; ++_$Ub) {
        _$CJ = _$z8.charCodeAt(_$Ub);
        if (_$CJ >= 40 && _$CJ < 92) {
            _$CJ += _$9z;
            if (_$CJ >= 92)
                _$CJ = _$CJ - 52;
        } else if (_$CJ >= 97 && _$CJ < 127) {
            _$CJ += _$9z;
            if (_$CJ >= 127)
                _$CJ = _$CJ - 30;
        }
        _$4O[_$Bl++] = _$CJ;
    }
    return _$Sd.apply(null, _$4O);
}


traverse(ast, {
    MemberExpression(path) {
        if (
            path.node.object &&
            path.node.object.name &&
            path.node.object.name == "_$QL"
        ) {
            path.replaceInline(types.valueToNode(_$QL[path.node.property.value]))
        }else {

        }
    },
})

traverse(ast, {
    CallExpression(path) {
        if (
            path.node.callee &&
            path.node.callee.name &&
            path.node.callee.name == "_$Oq" &&
            path.node.arguments &&
            path.node.arguments.length == 1 &&
            path.node.arguments[0].value
        ){
            path.replaceInline(types.valueToNode(_$Oq(path.node.arguments[0].value)))
        }else {

        }
    },
})

let { code } = generator(ast, opts = { jsescOption: { "minimal": true } });
// 将js代码保存到文件
fs.writeFile(decode_file, code, (err) => { });
