package androidx.constraintlayout.widget;

import android.os.Build;
import androidx.constraintlayout.widget.ConstraintLayout;
import com.bytedance.covode.number.Covode;
import java.util.Arrays;
import p003X.C146241ezj;

/* loaded from: classes19.dex */
public class b$a {
    public boolean LIZ;
    public int LIZIZ;
    public int LIZJ;
    public int LIZLLL;

    /* renamed from: LJ */
    public int f20241LJ;
    public int LJFF;
    public float LJI;
    public int LJII;
    public int LJIIIIZZ;
    public int LJIIIZ;
    public int LJIIJ;
    public int LJIIJJI;
    public int LJIIL;
    public int LJIILIIL;
    public int LJIILJJIL;
    public int LJIILL;
    public int LJIILLIIL;
    public int LJIIZILJ;
    public int LJIJ;
    public int LJIJI;
    public float LJIJJ;
    public float LJIJJLI;
    public String LJIL;
    public int LJJ;
    public int LJJI;
    public float LJJIFFI;
    public int LJJII;
    public int LJJIII;
    public int LJJIIJ;
    public int LJJIIJZLJL;
    public int LJJIIZ;
    public int LJJIIZI;
    public int LJJIJ;
    public int LJJIJIIJI;
    public int LJJIJIIJIL;
    public int LJJIJIL;
    public int LJJIJL;
    public int LJJIJLIJ;
    public int LJJIL;
    public int LJJIZ;
    public int LJJJ;
    public int LJJJI;
    public float LJJJIL;
    public float LJJJJ;
    public int LJJJJI;
    public int LJJJJIZL;
    public float LJJJJJ;
    public boolean LJJJJJL;
    public float LJJJJL;
    public float LJJJJLI;
    public float LJJJJLL;
    public float LJJJJZ;
    public float LJJJJZI;
    public float LJJJLIIL;
    public float LJJJLL;
    public float LJJJLZIJ;
    public float LJJJZ;
    public float LJJL;
    public float LJJLI;
    public boolean LJJLIIIIJ;
    public boolean LJJLIIIJ;
    public int LJJLIIIJILLIZJL;
    public int LJJLIIIJJI;
    public int LJJLIIIJJIZ;
    public int LJJLIIIJL;
    public int LJJLIIIJLJLI;
    public int LJJLIIIJLLLLLLLZ;
    public float LJJLIIJ;
    public float LJJLIL;
    public boolean LJJLJ;
    public int LJJLJLI;
    public int LJJLL;
    public int[] LJJZ;
    public String LJJZZI;

    static {
        Covode.recordClassIndex(855);
    }

    public b$a() {
        this.f20241LJ = -1;
        this.LJFF = -1;
        this.LJI = -1.0f;
        this.LJII = -1;
        this.LJIIIIZZ = -1;
        this.LJIIIZ = -1;
        this.LJIIJ = -1;
        this.LJIIJJI = -1;
        this.LJIIL = -1;
        this.LJIILIIL = -1;
        this.LJIILJJIL = -1;
        this.LJIILL = -1;
        this.LJIILLIIL = -1;
        this.LJIIZILJ = -1;
        this.LJIJ = -1;
        this.LJIJI = -1;
        this.LJIJJ = 0.5f;
        this.LJIJJLI = 0.5f;
        this.LJJ = -1;
        this.LJJII = -1;
        this.LJJIII = -1;
        this.LJJIIJ = -1;
        this.LJJIIJZLJL = -1;
        this.LJJIIZ = -1;
        this.LJJIIZI = -1;
        this.LJJIJ = -1;
        this.LJJIJIIJI = -1;
        this.LJJIJIIJIL = -1;
        this.LJJIJL = -1;
        this.LJJIJLIJ = -1;
        this.LJJIL = -1;
        this.LJJIZ = -1;
        this.LJJJ = -1;
        this.LJJJI = -1;
        this.LJJJJJ = 1.0f;
        this.LJJJJZI = 1.0f;
        this.LJJJLIIL = 1.0f;
        this.LJJJLL = Float.NaN;
        this.LJJJLZIJ = Float.NaN;
        this.LJJLIIIJJIZ = -1;
        this.LJJLIIIJL = -1;
        this.LJJLIIIJLJLI = -1;
        this.LJJLIIIJLLLLLLLZ = -1;
        this.LJJLIIJ = 1.0f;
        this.LJJLIL = 1.0f;
        this.LJJLJLI = -1;
        this.LJJLL = -1;
    }

    public final /* synthetic */ Object clone() {
        b$a b_a = new b$a();
        b_a.LIZ = this.LIZ;
        b_a.LIZIZ = this.LIZIZ;
        b_a.LIZJ = this.LIZJ;
        b_a.f20241LJ = this.f20241LJ;
        b_a.LJFF = this.LJFF;
        b_a.LJI = this.LJI;
        b_a.LJII = this.LJII;
        b_a.LJIIIIZZ = this.LJIIIIZZ;
        b_a.LJIIIZ = this.LJIIIZ;
        b_a.LJIIJ = this.LJIIJ;
        b_a.LJIIJJI = this.LJIIJJI;
        b_a.LJIIL = this.LJIIL;
        b_a.LJIILIIL = this.LJIILIIL;
        b_a.LJIILJJIL = this.LJIILJJIL;
        b_a.LJIILL = this.LJIILL;
        b_a.LJIILLIIL = this.LJIILLIIL;
        b_a.LJIIZILJ = this.LJIIZILJ;
        b_a.LJIJ = this.LJIJ;
        b_a.LJIJI = this.LJIJI;
        b_a.LJIJJ = this.LJIJJ;
        b_a.LJIJJLI = this.LJIJJLI;
        b_a.LJIL = this.LJIL;
        b_a.LJJII = this.LJJII;
        b_a.LJJIII = this.LJJIII;
        b_a.LJIJJ = this.LJIJJ;
        b_a.LJIJJ = this.LJIJJ;
        b_a.LJIJJ = this.LJIJJ;
        b_a.LJIJJ = this.LJIJJ;
        b_a.LJIJJ = this.LJIJJ;
        b_a.LJJIIJ = this.LJJIIJ;
        b_a.LJJIIJZLJL = this.LJJIIJZLJL;
        b_a.LJJIIZ = this.LJJIIZ;
        b_a.LJJIIZI = this.LJJIIZI;
        b_a.LJJIJ = this.LJJIJ;
        b_a.LJJIJIIJI = this.LJJIJIIJI;
        b_a.LJJIJIIJIL = this.LJJIJIIJIL;
        b_a.LJJIJIL = this.LJJIJIL;
        b_a.LJJIJL = this.LJJIJL;
        b_a.LJJIJLIJ = this.LJJIJLIJ;
        b_a.LJJIL = this.LJJIL;
        b_a.LJJIZ = this.LJJIZ;
        b_a.LJJJ = this.LJJJ;
        b_a.LJJJI = this.LJJJI;
        b_a.LJJJIL = this.LJJJIL;
        b_a.LJJJJ = this.LJJJJ;
        b_a.LJJJJI = this.LJJJJI;
        b_a.LJJJJIZL = this.LJJJJIZL;
        b_a.LJJJJJ = this.LJJJJJ;
        b_a.LJJJJJL = this.LJJJJJL;
        b_a.LJJJJL = this.LJJJJL;
        b_a.LJJJJLI = this.LJJJJLI;
        b_a.LJJJJLL = this.LJJJJLL;
        b_a.LJJJJZ = this.LJJJJZ;
        b_a.LJJJJZI = this.LJJJJZI;
        b_a.LJJJLIIL = this.LJJJLIIL;
        b_a.LJJJLL = this.LJJJLL;
        b_a.LJJJLZIJ = this.LJJJLZIJ;
        b_a.LJJJZ = this.LJJJZ;
        b_a.LJJL = this.LJJL;
        b_a.LJJLI = this.LJJLI;
        b_a.LJJLIIIIJ = this.LJJLIIIIJ;
        b_a.LJJLIIIJ = this.LJJLIIIJ;
        b_a.LJJLIIIJILLIZJL = this.LJJLIIIJILLIZJL;
        b_a.LJJLIIIJJI = this.LJJLIIIJJI;
        b_a.LJJLIIIJJIZ = this.LJJLIIIJJIZ;
        b_a.LJJLIIIJL = this.LJJLIIIJL;
        b_a.LJJLIIIJLJLI = this.LJJLIIIJLJLI;
        b_a.LJJLIIIJLLLLLLLZ = this.LJJLIIIJLLLLLLLZ;
        b_a.LJJLIIJ = this.LJJLIIJ;
        b_a.LJJLIL = this.LJJLIL;
        b_a.LJJLJLI = this.LJJLJLI;
        b_a.LJJLL = this.LJJLL;
        int[] iArr = this.LJJZ;
        if (iArr != null) {
            b_a.LJJZ = Arrays.copyOf(iArr, iArr.length);
        }
        b_a.LJJ = this.LJJ;
        b_a.LJJI = this.LJJI;
        b_a.LJJIFFI = this.LJJIFFI;
        b_a.LJJLJ = this.LJJLJ;
        return b_a;
    }

    public /* synthetic */ b$a(byte b) {
        this();
    }

    public final void LIZ(ConstraintLayout.LayoutParams layoutParams) {
        layoutParams.leftToLeft = this.LJII;
        layoutParams.leftToRight = this.LJIIIIZZ;
        layoutParams.rightToLeft = this.LJIIIZ;
        layoutParams.rightToRight = this.LJIIJ;
        layoutParams.topToTop = this.LJIIJJI;
        layoutParams.topToBottom = this.LJIIL;
        layoutParams.bottomToTop = this.LJIILIIL;
        layoutParams.bottomToBottom = this.LJIILJJIL;
        layoutParams.baselineToBaseline = this.LJIILL;
        layoutParams.startToEnd = this.LJIILLIIL;
        layoutParams.startToStart = this.LJIIZILJ;
        layoutParams.endToStart = this.LJIJ;
        layoutParams.endToEnd = this.LJIJI;
        layoutParams.leftMargin = this.LJJIIJZLJL;
        layoutParams.rightMargin = this.LJJIIZ;
        layoutParams.topMargin = this.LJJIIZI;
        layoutParams.bottomMargin = this.LJJIJ;
        layoutParams.goneStartMargin = this.LJJJI;
        layoutParams.goneEndMargin = this.LJJJ;
        layoutParams.horizontalBias = this.LJIJJ;
        layoutParams.verticalBias = this.LJIJJLI;
        layoutParams.circleConstraint = this.LJJ;
        layoutParams.circleRadius = this.LJJI;
        layoutParams.circleAngle = this.LJJIFFI;
        layoutParams.dimensionRatio = this.LJIL;
        layoutParams.editorAbsoluteX = this.LJJII;
        layoutParams.editorAbsoluteY = this.LJJIII;
        layoutParams.verticalWeight = this.LJJJIL;
        layoutParams.horizontalWeight = this.LJJJJ;
        layoutParams.verticalChainStyle = this.LJJJJIZL;
        layoutParams.horizontalChainStyle = this.LJJJJI;
        layoutParams.constrainedWidth = this.LJJLIIIIJ;
        layoutParams.constrainedHeight = this.LJJLIIIJ;
        layoutParams.matchConstraintDefaultWidth = this.LJJLIIIJILLIZJL;
        layoutParams.matchConstraintDefaultHeight = this.LJJLIIIJJI;
        layoutParams.matchConstraintMaxWidth = this.LJJLIIIJJIZ;
        layoutParams.matchConstraintMaxHeight = this.LJJLIIIJL;
        layoutParams.matchConstraintMinWidth = this.LJJLIIIJLJLI;
        layoutParams.matchConstraintMinHeight = this.LJJLIIIJLLLLLLLZ;
        layoutParams.matchConstraintPercentWidth = this.LJJLIIJ;
        layoutParams.matchConstraintPercentHeight = this.LJJLIL;
        layoutParams.orientation = this.LJJIIJ;
        layoutParams.guidePercent = this.LJI;
        layoutParams.guideBegin = this.f20241LJ;
        layoutParams.guideEnd = this.LJFF;
        layoutParams.width = this.LIZIZ;
        layoutParams.height = this.LIZJ;
        int i = Build.VERSION.SDK_INT;
        layoutParams.setMarginStart(this.LJJIJIIJIL);
        layoutParams.setMarginEnd(this.LJJIJIIJI);
        layoutParams.validate();
    }

    public final void LIZ(int i, C146241ezj c146241ezj) {
        LIZ(i, (ConstraintLayout.LayoutParams) c146241ezj);
        this.LJJJJJ = c146241ezj.LIZ;
        this.LJJJJLI = c146241ezj.LIZLLL;
        this.LJJJJLL = c146241ezj.f19510LJ;
        this.LJJJJZ = c146241ezj.LJFF;
        this.LJJJJZI = c146241ezj.LJI;
        this.LJJJLIIL = c146241ezj.LJII;
        this.LJJJLL = c146241ezj.LJIIIIZZ;
        this.LJJJLZIJ = c146241ezj.LJIIIZ;
        this.LJJJZ = c146241ezj.LJIIJ;
        this.LJJL = c146241ezj.LJIIJJI;
        this.LJJLI = c146241ezj.LJIIL;
        this.LJJJJL = c146241ezj.LIZJ;
        this.LJJJJJL = c146241ezj.LIZIZ;
    }

    public final void LIZ(int i, ConstraintLayout.LayoutParams layoutParams) {
        this.LIZLLL = i;
        this.LJII = layoutParams.leftToLeft;
        this.LJIIIIZZ = layoutParams.leftToRight;
        this.LJIIIZ = layoutParams.rightToLeft;
        this.LJIIJ = layoutParams.rightToRight;
        this.LJIIJJI = layoutParams.topToTop;
        this.LJIIL = layoutParams.topToBottom;
        this.LJIILIIL = layoutParams.bottomToTop;
        this.LJIILJJIL = layoutParams.bottomToBottom;
        this.LJIILL = layoutParams.baselineToBaseline;
        this.LJIILLIIL = layoutParams.startToEnd;
        this.LJIIZILJ = layoutParams.startToStart;
        this.LJIJ = layoutParams.endToStart;
        this.LJIJI = layoutParams.endToEnd;
        this.LJIJJ = layoutParams.horizontalBias;
        this.LJIJJLI = layoutParams.verticalBias;
        this.LJIL = layoutParams.dimensionRatio;
        this.LJJ = layoutParams.circleConstraint;
        this.LJJI = layoutParams.circleRadius;
        this.LJJIFFI = layoutParams.circleAngle;
        this.LJJII = layoutParams.editorAbsoluteX;
        this.LJJIII = layoutParams.editorAbsoluteY;
        this.LJJIIJ = layoutParams.orientation;
        this.LJI = layoutParams.guidePercent;
        this.f20241LJ = layoutParams.guideBegin;
        this.LJFF = layoutParams.guideEnd;
        this.LIZIZ = layoutParams.width;
        this.LIZJ = layoutParams.height;
        this.LJJIIJZLJL = layoutParams.leftMargin;
        this.LJJIIZ = layoutParams.rightMargin;
        this.LJJIIZI = layoutParams.topMargin;
        this.LJJIJ = layoutParams.bottomMargin;
        this.LJJJIL = layoutParams.verticalWeight;
        this.LJJJJ = layoutParams.horizontalWeight;
        this.LJJJJIZL = layoutParams.verticalChainStyle;
        this.LJJJJI = layoutParams.horizontalChainStyle;
        this.LJJLIIIIJ = layoutParams.constrainedWidth;
        this.LJJLIIIJ = layoutParams.constrainedHeight;
        this.LJJLIIIJILLIZJL = layoutParams.matchConstraintDefaultWidth;
        this.LJJLIIIJJI = layoutParams.matchConstraintDefaultHeight;
        this.LJJLIIIIJ = layoutParams.constrainedWidth;
        this.LJJLIIIJJIZ = layoutParams.matchConstraintMaxWidth;
        this.LJJLIIIJL = layoutParams.matchConstraintMaxHeight;
        this.LJJLIIIJLJLI = layoutParams.matchConstraintMinWidth;
        this.LJJLIIIJLLLLLLLZ = layoutParams.matchConstraintMinHeight;
        this.LJJLIIJ = layoutParams.matchConstraintPercentWidth;
        this.LJJLIL = layoutParams.matchConstraintPercentHeight;
        int i2 = Build.VERSION.SDK_INT;
        this.LJJIJIIJI = layoutParams.getMarginEnd();
        this.LJJIJIIJIL = layoutParams.getMarginStart();
    }
}
