package com.bytedance.android.live.base.model.proto;

import com.bytedance.android.live.base.model.Appointment;
import com.bytedance.android.live.base.model.C2806b;
import com.bytedance.android.live.base.model.C2810c;
import com.bytedance.android.live.base.model.C2834h;
import com.bytedance.android.live.base.model.C2835i;
import com.bytedance.android.live.base.model.C2836j;
import com.bytedance.android.live.base.model.C2837k;
import com.bytedance.android.live.base.model.C2840l;
import com.bytedance.android.live.base.model.FansClubMember;
import com.bytedance.android.live.base.model.FlexImageModel;
import com.bytedance.android.live.base.model.FlexImageStruct;
import com.bytedance.android.live.base.model.ImageModel;
import com.bytedance.android.live.base.model._Appointment_LiveFragments_ProtoDecoder;
import com.bytedance.android.live.base.model._Appointment_ProtoDecoder;
import com.bytedance.android.live.base.model._CateCell_ProtoDecoder;
import com.bytedance.android.live.base.model._Category_ProtoDecoder;
import com.bytedance.android.live.base.model._FansClubMember_ProtoDecoder;
import com.bytedance.android.live.base.model._FlexImageModel_ProtoDecoder;
import com.bytedance.android.live.base.model._FlexImageStruct_ProtoDecoder;
import com.bytedance.android.live.base.model._ImageModel_Content_ProtoDecoder;
import com.bytedance.android.live.base.model._ImageModel_ProtoDecoder;
import com.bytedance.android.live.base.model._ShortTouchArea_ProtoDecoder;
import com.bytedance.android.live.base.model._ShortTouchBigCard_ProtoDecoder;
import com.bytedance.android.live.base.model._ShortTouchBubble_ProtoDecoder;
import com.bytedance.android.live.base.model._ShortTouchInfo_ProtoDecoder;
import com.bytedance.android.live.base.model._ShortTouchInfo_ShortTouchImageLayers_Layer_ProtoDecoder;
import com.bytedance.android.live.base.model._ShortTouchInfo_ShortTouchImageLayers_ProtoDecoder;
import com.bytedance.android.live.base.model._TextViewModel_ProtoDecoder;
import com.bytedance.android.live.base.model.banner.C2807a;
import com.bytedance.android.live.base.model.banner.C2808b;
import com.bytedance.android.live.base.model.banner.C2809c;
import com.bytedance.android.live.base.model.banner._FeedBannerContainer_ProtoDecoder;
import com.bytedance.android.live.base.model.banner._FeedBanner_ProtoDecoder;
import com.bytedance.android.live.base.model.banner._RankRoundBanner_ProtoDecoder;
import com.bytedance.android.live.base.model.dynamic.C2817b;
import com.bytedance.android.live.base.model.dynamic.C2818c;
import com.bytedance.android.live.base.model.dynamic.C2820e;
import com.bytedance.android.live.base.model.dynamic.C2821f;
import com.bytedance.android.live.base.model.dynamic.C2823h;
import com.bytedance.android.live.base.model.dynamic._DynamicDetails_ProtoDecoder;
import com.bytedance.android.live.base.model.dynamic._DynamicHistory_ProtoDecoder;
import com.bytedance.android.live.base.model.dynamic._FoldHistoryData_ProtoDecoder;
import com.bytedance.android.live.base.model.dynamic._NoticeDetail_ProtoDecoder;
import com.bytedance.android.live.base.model.dynamic._VideoItem_ProtoDecoder;
import com.bytedance.android.live.base.model.feed.C2827a;
import com.bytedance.android.live.base.model.feed.FeedItem;
import com.bytedance.android.live.base.model.feed._FeedExtra_LogPb_ProtoDecoder;
import com.bytedance.android.live.base.model.feed._FeedExtra_ProtoDecoder;
import com.bytedance.android.live.base.model.feed._FeedItem_ProtoDecoder;
import com.bytedance.android.live.base.model.follow.PlaceHolder;
import com.bytedance.android.live.base.model.follow.ScheduledLive;
import com.bytedance.android.live.base.model.follow.ScheduledLiveItem;
import com.bytedance.android.live.base.model.follow._PlaceHolder_ProtoDecoder;
import com.bytedance.android.live.base.model.follow._ScheduledLiveItem_ProtoDecoder;
import com.bytedance.android.live.base.model.follow._ScheduledLive_ProtoDecoder;
import com.bytedance.android.live.base.model.gift.C2830b;
import com.bytedance.android.live.base.model.gift.C2831c;
import com.bytedance.android.live.base.model.gift.C2832f;
import com.bytedance.android.live.base.model.gift.C2833g;
import com.bytedance.android.live.base.model.gift._ExhibitionGiftItem_ProtoDecoder;
import com.bytedance.android.live.base.model.gift._ExhibitionGiftStruct_ProtoDecoder;
import com.bytedance.android.live.base.model.gift._ExhibitionUser_ProtoDecoder;
import com.bytedance.android.live.base.model.gift._GiftExhibitionHomeResponse_ProtoDecoder;
import com.bytedance.android.live.base.model.live.C2842c;
import com.bytedance.android.live.base.model.live.C2843d;
import com.bytedance.android.live.base.model.live.RoomStats;
import com.bytedance.android.live.base.model.live._RankUser_ProtoDecoder;
import com.bytedance.android.live.base.model.live._Ranking_ProtoDecoder;
import com.bytedance.android.live.base.model.live._RoomStats_ProtoDecoder;
import com.bytedance.android.live.base.model.live._RoomStats_UserComposition_ProtoDecoder;
import com.bytedance.android.live.base.model.tab.C2847a;
import com.bytedance.android.live.base.model.tab._TabItem_ProtoDecoder;
import com.bytedance.android.live.base.model.user.AccountStats;
import com.bytedance.android.live.base.model.user.AccountTypeInfo;
import com.bytedance.android.live.base.model.user.ActionConfig;
import com.bytedance.android.live.base.model.user.ActionConfigs;
import com.bytedance.android.live.base.model.user.ActivityBadges;
import com.bytedance.android.live.base.model.user.ActivityRewardInfo;
import com.bytedance.android.live.base.model.user.AdminInfo;
import com.bytedance.android.live.base.model.user.AnchorInfo;
import com.bytedance.android.live.base.model.user.AnchorLevel;
import com.bytedance.android.live.base.model.user.AuthenticationInfo;
import com.bytedance.android.live.base.model.user.Author;
import com.bytedance.android.live.base.model.user.AuthorReputation;
import com.bytedance.android.live.base.model.user.BaseProfileInfo;
import com.bytedance.android.live.base.model.user.BorderInfo;
import com.bytedance.android.live.base.model.user.BroadcastConfig;
import com.bytedance.android.live.base.model.user.Contributor;
import com.bytedance.android.live.base.model.user.EcomInfo;
import com.bytedance.android.live.base.model.user.FansClubData;
import com.bytedance.android.live.base.model.user.FansGroupInfo;
import com.bytedance.android.live.base.model.user.FollowInfo;
import com.bytedance.android.live.base.model.user.FraternityInfo;
import com.bytedance.android.live.base.model.user.GiftExhibitionHomeStats;
import com.bytedance.android.live.base.model.user.GradeBuffInfo;
import com.bytedance.android.live.base.model.user.GradeIcon;
import com.bytedance.android.live.base.model.user.HonorWallUi;
import com.bytedance.android.live.base.model.user.IndustryCertification;
import com.bytedance.android.live.base.model.user.IndustryCertificationProfile;
import com.bytedance.android.live.base.model.user.IndustryCertificationRoom;
import com.bytedance.android.live.base.model.user.MutualFollowUser;
import com.bytedance.android.live.base.model.user.NewAuthenticationInfo;
import com.bytedance.android.live.base.model.user.NewProfileUser;
import com.bytedance.android.live.base.model.user.NobleLevelInfo;
import com.bytedance.android.live.base.model.user.PoiInfo;
import com.bytedance.android.live.base.model.user.ProfileCustomSkin;
import com.bytedance.android.live.base.model.user.ProfileFansClub;
import com.bytedance.android.live.base.model.user.ProfileFansClubData;
import com.bytedance.android.live.base.model.user.ProfileFollowInfo;
import com.bytedance.android.live.base.model.user.ProfileOwnRoom;
import com.bytedance.android.live.base.model.user.ProfilePoiInfo;
import com.bytedance.android.live.base.model.user.ProfileSetting;
import com.bytedance.android.live.base.model.user.ProfileSkin;
import com.bytedance.android.live.base.model.user.ProfileStyleParams;
import com.bytedance.android.live.base.model.user.ProfileStyleTemplate;
import com.bytedance.android.live.base.model.user.RoomOwner;
import com.bytedance.android.live.base.model.user.ShopEntrance;
import com.bytedance.android.live.base.model.user.ShopHeaderIcon;
import com.bytedance.android.live.base.model.user.ShopHeaderInfo;
import com.bytedance.android.live.base.model.user.SubscribeInfo;
import com.bytedance.android.live.base.model.user.User;
import com.bytedance.android.live.base.model.user.UserAttr;
import com.bytedance.android.live.base.model.user.UserHonor;
import com.bytedance.android.live.base.model.user.UserProfileDataResp;
import com.bytedance.android.live.base.model.user.WindowHeaderInfo;
import com.bytedance.android.live.base.model.user.XiguaUserParams;
import com.bytedance.android.live.base.model.user._AccountStats_ProtoDecoder;
import com.bytedance.android.live.base.model.user._AccountTypeInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ActionConfig_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ActionConfigs_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ActivityBadges_GradientColor_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ActivityBadges_NewProfileBadge_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ActivityBadges_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ActivityRewardInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._AdminInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._AnchorInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._AnchorLevel_ProtoDecoder;
import com.bytedance.android.live.base.model.user._AuthenticationInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._AuthorReputation_ProtoDecoder;
import com.bytedance.android.live.base.model.user._Author_ProtoDecoder;
import com.bytedance.android.live.base.model.user._BaseProfileInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._BorderInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._BroadcastConfig_ProtoDecoder;
import com.bytedance.android.live.base.model.user._Contributor_ProtoDecoder;
import com.bytedance.android.live.base.model.user._EcomInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._FansClubData_ProtoDecoder;
import com.bytedance.android.live.base.model.user._FansClubData_UserBadge_ProtoDecoder;
import com.bytedance.android.live.base.model.user._FansGroupInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._FollowInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._FraternityInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._GiftExhibitionHomeStats_ProtoDecoder;
import com.bytedance.android.live.base.model.user._GradeBuffInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._GradeIcon_ProtoDecoder;
import com.bytedance.android.live.base.model.user._HonorWallUi_HonorWallBg_ProtoDecoder;
import com.bytedance.android.live.base.model.user._HonorWallUi_ProtoDecoder;
import com.bytedance.android.live.base.model.user._IndustryCertificationProfile_ProtoDecoder;
import com.bytedance.android.live.base.model.user._IndustryCertificationRoom_ProtoDecoder;
import com.bytedance.android.live.base.model.user._IndustryCertification_ProtoDecoder;
import com.bytedance.android.live.base.model.user._MutualFollowUser_ProtoDecoder;
import com.bytedance.android.live.base.model.user._NewAuthenticationInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._NewProfileUser_ProtoDecoder;
import com.bytedance.android.live.base.model.user._NobleLevelInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._PoiInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileCustomSkin_BgUI_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileCustomSkin_GradientColor_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileCustomSkin_HonorWallUI_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileCustomSkin_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileCustomSkin_SecondaryButtonUI_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileCustomSkin_TagUI_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileFansClubData_ProfileUserBadge_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileFansClubData_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileFansClub_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileFollowInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileOwnRoom_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfilePoiInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileSetting_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileSkin_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileStyleParams_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ProfileStyleTemplate_ProtoDecoder;
import com.bytedance.android.live.base.model.user._RoomOwner_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ShopEntrance_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ShopHeaderIcon_ProtoDecoder;
import com.bytedance.android.live.base.model.user._ShopHeaderInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._SubscribeInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._UserAttr_ProtoDecoder;
import com.bytedance.android.live.base.model.user._UserHonor_ProtoDecoder;
import com.bytedance.android.live.base.model.user._UserProfileDataResp_ProtoDecoder;
import com.bytedance.android.live.base.model.user._UserProfileDataResp_UserProfileExtra_ProtoDecoder;
import com.bytedance.android.live.base.model.user._User_OwnRoom_ProtoDecoder;
import com.bytedance.android.live.base.model.user._User_ProtoDecoder;
import com.bytedance.android.live.base.model.user._WindowHeaderInfo_ProtoDecoder;
import com.bytedance.android.live.base.model.user._XiguaUserParams_ProtoDecoder;
import com.bytedance.android.live.base.model.user._XiguaUserParams_RocketSchema_ProtoDecoder;
import com.bytedance.android.live.base.model.user._XiguaUserParams_UserExtendInfo_ProtoDecoder;
import com.bytedance.android.live.core.resources.AssetsModel;
import com.bytedance.android.live.core.resources.C4086b;
import com.bytedance.android.live.core.resources.ResourceH265Model;
import com.bytedance.android.live.core.resources.ResourceH265SuperModel;
import com.bytedance.android.live.core.resources._AssetsModel_ProtoDecoder;
import com.bytedance.android.live.core.resources._ResourceH265Model_ProtoDecoder;
import com.bytedance.android.live.core.resources._ResourceH265SuperModel_ProtoDecoder;
import com.bytedance.android.live.core.resources._ResourceModel_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model.AnchorLinkUser;
import com.bytedance.android.live.liveinteract.multianchor.model.C4534a;
import com.bytedance.android.live.liveinteract.multianchor.model.LinkmicPositionItem;
import com.bytedance.android.live.liveinteract.multianchor.model.ListUserContent;
import com.bytedance.android.live.liveinteract.multianchor.model.ListUserLinkmicAudienceContent;
import com.bytedance.android.live.liveinteract.multianchor.model.ListUserLinkmicContent;
import com.bytedance.android.live.liveinteract.multianchor.model.ListUserPKContent;
import com.bytedance.android.live.liveinteract.multianchor.model.MicDress;
import com.bytedance.android.live.liveinteract.multianchor.model._AnchorLinkUser_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._LinkmicPositionItem_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._ListUserContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._ListUserExtra_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._ListUserLinkmicAudienceContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._ListUserLinkmicContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._ListUserPKContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._MicDress_ProtoDecoder;
import com.bytedance.android.live.liveinteract.multianchor.model._MicDress_VoiceWave_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model.C4816k;
import com.bytedance.android.live.liveinteract.plantform.model.ListTag;
import com.bytedance.android.live.liveinteract.plantform.model.RoomLinkerContent;
import com.bytedance.android.live.liveinteract.plantform.model.TeamFightJoinTeamInfo;
import com.bytedance.android.live.liveinteract.plantform.model._LinkMicQuickInteract_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._ListTag_ListTagFansClubContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._ListTag_ListTagFansContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._ListTag_ListTagFriendContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._ListTag_ListTagHonorLevelContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._ListTag_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._RoomLinkerContent_ProtoDecoder;
import com.bytedance.android.live.liveinteract.plantform.model._TeamFightJoinTeamInfo_ProtoDecoder;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model.C4929c;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model.InteractEmojiAnim;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model.TalkRoomDigitAvatarEmoji;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model.TalkRoomEmojiPermission;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model.TalkRoomInteractEmoji;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model._InteractEmojiAnim_ProtoDecoder;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model._TalkRoomDigitAvatarEmoji_ProtoDecoder;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model._TalkRoomDynamicEmoji_ProtoDecoder;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model._TalkRoomEmojiPermission_ProtoDecoder;
import com.bytedance.android.live.liveinteract.videotalk.emoji.model._TalkRoomInteractEmoji_ProtoDecoder;
import com.bytedance.android.live.profit.privilege.model.ScreenChatTabResponse;
import com.bytedance.android.live.profit.privilege.model._ScreenChatTabResponse_ProtoDecoder;
import com.bytedance.android.live.profit.privilege.model._ScreenChatTabResponse_TabItem_ProtoDecoder;
import com.bytedance.android.livesdk.announce.AnnouncementInfo;
import com.bytedance.android.livesdk.announce.SimpleAnnouncementInfo;
import com.bytedance.android.livesdk.announce._AnnouncementInfo_ProtoDecoder;
import com.bytedance.android.livesdk.announce._SimpleAnnouncementInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.C6140f;
import com.bytedance.android.livesdk.chatroom.model.C6141g;
import com.bytedance.android.livesdk.chatroom.model.ChatResult;
import com.bytedance.android.livesdk.chatroom.model._BannerCollapseInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model._BannerInRoomCollection_BannerInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model._BannerInRoomCollection_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model._ChatResult_LandscapeAreaCommon_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model._ChatResult_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact.C6166j;
import com.bytedance.android.livesdk.chatroom.model.interact.KTVLiveCoreInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.MultiAnchorLinkmicLiveCoreInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.MultiAnchorLinkmicRtcInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.MultiLiveCoreInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.MultiRtcInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.SingingChallengeLiveCoreInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.SingingChallengeRtcInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.VideoDuoBattleLiveCoreInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.VideoEqualRoomLiveCoreInfo;
import com.bytedance.android.livesdk.chatroom.model.interact.VideoEqualRoomRtcInfo;
import com.bytedance.android.livesdk.chatroom.model.interact._GuestBattleInfo_BattleResult_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._GuestBattleInfo_GuestBattleContributors_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._GuestBattleInfo_GuestBattleGradeItem_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._GuestBattleInfo_GuestBattleUserGradeInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._GuestBattleInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._KTVLiveCoreInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._MultiAnchorLinkmicLiveCoreInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._MultiAnchorLinkmicRtcInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._MultiLiveCoreInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._MultiRtcInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._SingingChallengeLiveCoreInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._SingingChallengeRtcInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._VideoDuoBattleLiveCoreInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._VideoEqualRoomLiveCoreInfo_ProtoDecoder;
import com.bytedance.android.livesdk.chatroom.model.interact._VideoEqualRoomRtcInfo_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model.C7185ae;
import com.bytedance.android.livesdk.gift.model.C7199p;
import com.bytedance.android.livesdk.gift.model.C7203u;
import com.bytedance.android.livesdk.gift.model.C7204w;
import com.bytedance.android.livesdk.gift.model.C7205x;
import com.bytedance.android.livesdk.gift.model.C7206y;
import com.bytedance.android.livesdk.gift.model.C7207z;
import com.bytedance.android.livesdk.gift.model.DoodleTemplate;
import com.bytedance.android.livesdk.gift.model.GiftOperation;
import com.bytedance.android.livesdk.gift.model.GiftPage;
import com.bytedance.android.livesdk.gift.model.Portal;
import com.bytedance.android.livesdk.gift.model.Prop;
import com.bytedance.android.livesdk.gift.model._DoodleTemplate_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GiftOperation_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GiftPage_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GiftStructFansClubInfo_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GiftTrayInfo_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._Gift_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GroupShowInfo_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GroupShowUserItem_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._GroupShowUsersResponse_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._Portal_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._Prop_ProtoDecoder;
import com.bytedance.android.livesdk.gift.model._ShowStatusLabel_ProtoDecoder;
import com.bytedance.android.livesdk.gift.platform.business.effect.assets.C7395b;
import com.bytedance.android.livesdk.gift.platform.business.effect.assets._AssetsListResult_ProtoDecoder;
import com.bytedance.android.livesdk.message.model.AudioInfo;
import com.bytedance.android.livesdk.message.model.C8981jo;
import com.bytedance.android.livesdk.message.model.InteractiveSongUserInfo;
import com.bytedance.android.livesdk.message.model.KtvMusic;
import com.bytedance.android.livesdk.message.model.OrderInfo;
import com.bytedance.android.livesdk.message.model._AudioInfo_ProtoDecoder;
import com.bytedance.android.livesdk.message.model._InteractiveSongUserInfo_ProtoDecoder;
import com.bytedance.android.livesdk.message.model._KtvMusic_MusicInterval_ProtoDecoder;
import com.bytedance.android.livesdk.message.model._KtvMusic_ProtoDecoder;
import com.bytedance.android.livesdk.message.model._OrderInfo_ProtoDecoder;
import com.bytedance.android.livesdk.message.model._TextEffect_Detail_ProtoDecoder;
import com.bytedance.android.livesdk.message.model._TextEffect_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.C9472x8ee8d6ea;
import com.bytedance.android.livesdkapi.depend.model.C9481c;
import com.bytedance.android.livesdkapi.depend.model.ChargeDeal;
import com.bytedance.android.livesdkapi.depend.model.FirstChargeCheck;
import com.bytedance.android.livesdkapi.depend.model._ChargeDeal_CurrencyPrice_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._ChargeDeal_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._FirstChargeCheck_FirstChargeCheckExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._FirstChargeCheck_FirstChargePackageItem_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._FirstChargeCheck_FirstChargePackage_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._FirstChargeCheck_FlexImageStruct_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._FirstChargeCheck_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model._ShortTouchResponseData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.backtrace.C9479a;
import com.bytedance.android.livesdkapi.depend.model.backtrace._AnchorBackRecordData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.ActivityRoomSkinInfo;
import com.bytedance.android.livesdkapi.depend.model.live.AdminRecordAdminInfo;
import com.bytedance.android.livesdkapi.depend.model.live.AnchorTabLabel;
import com.bytedance.android.livesdkapi.depend.model.live.BattleOperationalPlay;
import com.bytedance.android.livesdkapi.depend.model.live.BattlePrecisionMatcher;
import com.bytedance.android.livesdkapi.depend.model.live.BattleRivalTag;
import com.bytedance.android.livesdkapi.depend.model.live.BattleUserInfo;
import com.bytedance.android.livesdkapi.depend.model.live.BurstInfo;
import com.bytedance.android.livesdkapi.depend.model.live.C9488ab;
import com.bytedance.android.livesdkapi.depend.model.live.C9490ac;
import com.bytedance.android.livesdkapi.depend.model.live.C9491ad;
import com.bytedance.android.livesdkapi.depend.model.live.C9492ae;
import com.bytedance.android.livesdkapi.depend.model.live.C9501d;
import com.bytedance.android.livesdkapi.depend.model.live.C9502e;
import com.bytedance.android.livesdkapi.depend.model.live.C9508f;
import com.bytedance.android.livesdkapi.depend.model.live.C9509g;
import com.bytedance.android.livesdkapi.depend.model.live.C9510h;
import com.bytedance.android.livesdkapi.depend.model.live.C9511i;
import com.bytedance.android.livesdkapi.depend.model.live.C9512j;
import com.bytedance.android.livesdkapi.depend.model.live.C9514k;
import com.bytedance.android.livesdkapi.depend.model.live.C9515l;
import com.bytedance.android.livesdkapi.depend.model.live.C9554m;
import com.bytedance.android.livesdkapi.depend.model.live.C9555n;
import com.bytedance.android.livesdkapi.depend.model.live.C9557p;
import com.bytedance.android.livesdkapi.depend.model.live.C9558q;
import com.bytedance.android.livesdkapi.depend.model.live.C9559r;
import com.bytedance.android.livesdkapi.depend.model.live.C9560s;
import com.bytedance.android.livesdkapi.depend.model.live.C9561t;
import com.bytedance.android.livesdkapi.depend.model.live.C9564y;
import com.bytedance.android.livesdkapi.depend.model.live.C9565z;
import com.bytedance.android.livesdkapi.depend.model.live.CommentConfig;
import com.bytedance.android.livesdkapi.depend.model.live.CommentPinContent;
import com.bytedance.android.livesdkapi.depend.model.live.CommentPinPosition;
import com.bytedance.android.livesdkapi.depend.model.live.CornerMarkReach;
import com.bytedance.android.livesdkapi.depend.model.live.EpisodePreviewImage;
import com.bytedance.android.livesdkapi.depend.model.live.FilterWordToutiao;
import com.bytedance.android.livesdkapi.depend.model.live.GameExtraInfo;
import com.bytedance.android.livesdkapi.depend.model.live.HotRoomInfo;
import com.bytedance.android.livesdkapi.depend.model.live.InteractOpenExtra;
import com.bytedance.android.livesdkapi.depend.model.live.LinkMicBattleScore;
import com.bytedance.android.livesdkapi.depend.model.live.LinkMicBattleSetting;
import com.bytedance.android.livesdkapi.depend.model.live.LinkMicChannelInfo;
import com.bytedance.android.livesdkapi.depend.model.live.LinkerDetail;
import com.bytedance.android.livesdkapi.depend.model.live.LinkerUsers;
import com.bytedance.android.livesdkapi.depend.model.live.LiveCoreSDKData;
import com.bytedance.android.livesdkapi.depend.model.live.LiveNearbyTVInfo;
import com.bytedance.android.livesdkapi.depend.model.live.LivePlayTagInfo;
import com.bytedance.android.livesdkapi.depend.model.live.MatchInfo;
import com.bytedance.android.livesdkapi.depend.model.live.OfficialChannelExtraInfo;
import com.bytedance.android.livesdkapi.depend.model.live.OfficialChannelInfo;
import com.bytedance.android.livesdkapi.depend.model.live.OfficialRoomInfo;
import com.bytedance.android.livesdkapi.depend.model.live.PKIconBubble;
import com.bytedance.android.livesdkapi.depend.model.live.PreviewSwitch;
import com.bytedance.android.livesdkapi.depend.model.live.PublishItemTextExtraInfo;
import com.bytedance.android.livesdkapi.depend.model.live.QuizExtra;
import com.bytedance.android.livesdkapi.depend.model.live.ReplayInfo;
import com.bytedance.android.livesdkapi.depend.model.live.Reservation;
import com.bytedance.android.livesdkapi.depend.model.live.Room;
import com.bytedance.android.livesdkapi.depend.model.live.RoomAppearance;
import com.bytedance.android.livesdkapi.depend.model.live.RoomAuthStatus;
import com.bytedance.android.livesdkapi.depend.model.live.RoomBorderInfo;
import com.bytedance.android.livesdkapi.depend.model.live.RoomCart;
import com.bytedance.android.livesdkapi.depend.model.live.RoomDecoration;
import com.bytedance.android.livesdkapi.depend.model.live.RoomIMInfo;
import com.bytedance.android.livesdkapi.depend.model.live.RoomLinkInfo;
import com.bytedance.android.livesdkapi.depend.model.live.RoomLinkerUsers;
import com.bytedance.android.livesdkapi.depend.model.live.RoomTab;
import com.bytedance.android.livesdkapi.depend.model.live.RoomUserAttr;
import com.bytedance.android.livesdkapi.depend.model.live.ShortTermIndicatorConfig;
import com.bytedance.android.livesdkapi.depend.model.live.ShortTouchAuth;
import com.bytedance.android.livesdkapi.depend.model.live.StreamUrl;
import com.bytedance.android.livesdkapi.depend.model.live.StreamUrlExtra;
import com.bytedance.android.livesdkapi.depend.model.live.TeamTask;
import com.bytedance.android.livesdkapi.depend.model.live.TeamTaskItemCardInfo;
import com.bytedance.android.livesdkapi.depend.model.live.TopFanTicket;
import com.bytedance.android.livesdkapi.depend.model.live.UserHealthScoreInfo;
import com.bytedance.android.livesdkapi.depend.model.live.VipData;
import com.bytedance.android.livesdkapi.depend.model.live.WelfareProjectInfo;
import com.bytedance.android.livesdkapi.depend.model.live._ActivityRoomSkinInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._AdminRecordAdminInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._AnchorTabLabel_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BannerInRoom_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BaseUserInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleActivityPKConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleActivityUser_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleAnchorContributors_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleConsecutiveRecordInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleMode_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleMode_StealTowerData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleMultipleMatches3_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleMultipleMatchesUserInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleOperationalPlay_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattlePrecisionMatch_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattlePrecisionMatcher_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleRankUser_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleRivalTag_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleStarActivityGradeChange_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleStarActivityGrade_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleTask_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleTitleConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BattleUserInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._BurstInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._ChannelInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._CommentConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._CommentPinContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._CommentPinPosition_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._CornerMarkReach_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._EpisodePreviewImage_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._FilterWordToutiao_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._GameExtraInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._HotRoomInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._InteractOpenExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LinkMicBattleScore_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LinkMicBattleSetting_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LinkMicChannelInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LinkerDetail_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LinkerUsers_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_Clip_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_Extension_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_Options_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_PlayInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_PullData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_PushData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_Quality_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveCoreSDKData_ResolutionParams_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LiveNearbyTVInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._LivePlayTagInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._MatchInfo_FollowBtnSkin_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._MatchInfo_MatchSkinInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._MatchInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._OfficialChannelExtraInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._OfficialChannelInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._OfficialRoomInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._PKIconBubble_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._PkActivePushMatcher_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._PkActivePush_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._PreviewSwitch_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._PublishItemTextExtraInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._QuizExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._ReplayInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._Reservation_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomAppearance_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomAuthStatus_OffReason_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomAuthStatus_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomAuthStatus_RoomAuthSpecialStyle_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomAuthStatus_Style_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomBorderInfo_DynamicBorderInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomBorderInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomBorderInfo_StaticBorderInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomCart_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomCart_RoomCartIcons_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomCart_RoomCartStateHorizontal_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomCart_RoomCartStateVertical_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomDecoration_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomDecoration_TextComposeOption_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomIMInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomLinkInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomLinkerUsers_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomTab_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._RoomUserAttr_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._Room_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._ShortTermIndicatorConfig_Element_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._ShortTermIndicatorConfig_ForbiddenType_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._ShortTermIndicatorConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._ShortTouchAuth_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._StreamUrlExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._StreamUrlExtra_SrConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._StreamUrl_PlaySetting_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._StreamUrl_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TeamTaskConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TeamTaskInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TeamTaskItemCardInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TeamTaskPeriodConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TeamTaskReward_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TeamTask_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._TopFanTicket_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._UserHealthScoreInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._VipData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live._WelfareProjectInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.audio.AudioSpeakingImageList;
import com.bytedance.android.livesdkapi.depend.model.live.audio.SpeakingImage;
import com.bytedance.android.livesdkapi.depend.model.live.audio.VoiceLiveTheme;
import com.bytedance.android.livesdkapi.depend.model.live.audio._AudioSpeakingImageList_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.audio._SpeakingImage_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.audio._VoiceLiveTheme_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.circleinfo.CircleInfo;
import com.bytedance.android.livesdkapi.depend.model.live.circleinfo._CircleInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.easteregg.EasterEggData;
import com.bytedance.android.livesdkapi.depend.model.live.easteregg._EasterEggData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode.AlbumItem;
import com.bytedance.android.livesdkapi.depend.model.live.episode.C9503b;
import com.bytedance.android.livesdkapi.depend.model.live.episode.C9505d;
import com.bytedance.android.livesdkapi.depend.model.live.episode.C9507f;
import com.bytedance.android.livesdkapi.depend.model.live.episode.CommentColor;
import com.bytedance.android.livesdkapi.depend.model.live.episode.CommentMedal;
import com.bytedance.android.livesdkapi.depend.model.live.episode.CommentRole;
import com.bytedance.android.livesdkapi.depend.model.live.episode.CommentSpecialEffectData;
import com.bytedance.android.livesdkapi.depend.model.live.episode.DefinitionInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.Episode;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeCorrelationSeasonInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeExtraInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeHighLight;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeMod;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeOnlyTaInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeOnlyTaSegmentScope;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeOnlyTaSegments;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodePaidInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodePremierePlay;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodePreviewBottom;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeShare;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeStartHighLight;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeStatistics;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeUserStatistics;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeVideo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeVideoModelContainer;
import com.bytedance.android.livesdkapi.depend.model.live.episode.EpisodeWatchInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.ItemComment;
import com.bytedance.android.livesdkapi.depend.model.live.episode.ItemDetail;
import com.bytedance.android.livesdkapi.depend.model.live.episode.MarkDetail;
import com.bytedance.android.livesdkapi.depend.model.live.episode.MoreEntry;
import com.bytedance.android.livesdkapi.depend.model.live.episode.MoreHighLightList;
import com.bytedance.android.livesdkapi.depend.model.live.episode.MoreSpectacular;
import com.bytedance.android.livesdkapi.depend.model.live.episode.PriceInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.ReplayStreamUrl;
import com.bytedance.android.livesdkapi.depend.model.live.episode.SeasonAlbumTab;
import com.bytedance.android.livesdkapi.depend.model.live.episode.SegmentFlowTime;
import com.bytedance.android.livesdkapi.depend.model.live.episode.ShowCenterShowInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.ToolbarBackgroundConfig;
import com.bytedance.android.livesdkapi.depend.model.live.episode.TopicToast;
import com.bytedance.android.livesdkapi.depend.model.live.episode.VSBar;
import com.bytedance.android.livesdkapi.depend.model.live.episode.VSCameraInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode.VSFreeViewRange;
import com.bytedance.android.livesdkapi.depend.model.live.episode.VSToolbarConfigData;
import com.bytedance.android.livesdkapi.depend.model.live.episode.VsTopicInfo;
import com.bytedance.android.livesdkapi.depend.model.live.episode._AlbumItem_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._CommentColor_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._CommentMedal_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._CommentRole_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._CommentSpecialEffectData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._CommentSpecialEffectData_TimeRange_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._DefinitionInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EnterVideoResult_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeCorrelationSeasonInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeExtraInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeHighLight_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeMod_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeOnlyTaInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeOnlyTaSegmentScope_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeOnlyTaSegments_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodePaidInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodePremierePlay_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodePreviewBottom_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeShare_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeStartHighLight_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeStatistics_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeUserStatistics_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeVideoModelContainer_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeVideo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeVideo_StartLocation_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._EpisodeWatchInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._Episode_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._ItemComment_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._ItemDetail_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._LivePingExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._MarkDetail_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._MoreEntry_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._MoreHighLightList_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._MoreSpectacular_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._PriceInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._PriceInfo_StandardMoney_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._ReplayStreamUrl_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._ReplayStreamUrl_StreamAddr_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._SeasonAlbumTab_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._SegmentFlowTime_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._ShowCenterShowInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._ToolbarBackgroundConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._TopicToast_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VSBar_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VSCameraInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VSFreeViewRange_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VSRoomIDData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VSToolbarConfigData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VsTopicInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.episode._VsTopicInfo_TimePoint_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9516aa;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9517ab;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9518ac;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9519ad;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9520ae;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9521af;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9522ag;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9523ai;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9524aj;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9525ak;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9526al;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9527am;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9528an;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9529ao;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9530ap;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9531aq;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9532b;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9533c;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9535d;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9536f;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9537g;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9538i;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9542o;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9543p;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9544q;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9545r;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9546s;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9547t;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9548u;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9549v;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9550w;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9551x;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9552y;
import com.bytedance.android.livesdkapi.depend.model.live.linker.C9553z;
import com.bytedance.android.livesdkapi.depend.model.live.linker.LinkerUpdateLinkTypeApplyContent;
import com.bytedance.android.livesdkapi.depend.model.live.linker.LinkerUpdateLinkTypeReplyContent;
import com.bytedance.android.livesdkapi.depend.model.live.linker.RoomLinkMicSyncData;
import com.bytedance.android.livesdkapi.depend.model.live.linker._BanUser_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._BattleLinkerInviteMessageExtra_GameInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._BattleLinkerInviteMessageExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._BattleStarActivityGradeMedal_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._CityEffect_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._InviterRivalExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkMicAudienceEnterMessageExtra_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkMicAudienceEnterMessageExtra_UserInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerAvatarAuditContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerBanContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerBattleConnectContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerCancelContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerClickScreenContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerCreateContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerCrossRoomUpdateContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerEnterContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerFollowStrongGuideContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerGuestExitCastScreenContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerGuestInviteContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerInviteContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerInvitePrepareContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerItemContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerKickOutContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerLeaveContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerLinkedListChangeContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerLowBalanceForPaidLinkmicContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerReplyContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerResumeAudienceContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerSetting_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerShareVideoImContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerSysKickOutContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerUpdateLinkTypeApplyContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerUpdateLinkTypeReplyContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerUpdateUserContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerViolationReminderContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkerWaitingListChangeContent_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._LinkmicInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._MatchEffect_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.linker._RoomLinkMicSyncData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.p773im.ConsultInfo;
import com.bytedance.android.livesdkapi.depend.model.live.p773im.IMIndustryServiceInfo;
import com.bytedance.android.livesdkapi.depend.model.live.p773im._ConsultInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.p773im._IMIndustryServiceInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.p774vs.ShowEmojiInfo;
import com.bytedance.android.livesdkapi.depend.model.live.p774vs.ShowEmojiListResponse;
import com.bytedance.android.livesdkapi.depend.model.live.p774vs._ShowEmojiInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.p774vs._ShowEmojiListResponse_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.pay.PaidLiveData;
import com.bytedance.android.livesdkapi.depend.model.live.pay.TicketBriefData;
import com.bytedance.android.livesdkapi.depend.model.live.pay.TicketData;
import com.bytedance.android.livesdkapi.depend.model.live.pay.TicketPriceInfo;
import com.bytedance.android.livesdkapi.depend.model.live.pay._PaidLiveData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.pay._TicketBriefData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.pay._TicketData_PaidLivePriceInfoV2_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.pay._TicketData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.pay._TicketPriceInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.roomchannel.RoomChannelData;
import com.bytedance.android.livesdkapi.depend.model.live.roomchannel.RoomChannelInfo;
import com.bytedance.android.livesdkapi.depend.model.live.roomchannel._RoomChannelData_ProtoDecoder;
import com.bytedance.android.livesdkapi.depend.model.live.roomchannel._RoomChannelInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.message.C9592b;
import com.bytedance.android.livesdkapi.message.C9593c;
import com.bytedance.android.livesdkapi.message.C9594d;
import com.bytedance.android.livesdkapi.message.C9595e;
import com.bytedance.android.livesdkapi.message.C9596f;
import com.bytedance.android.livesdkapi.message.C9598i;
import com.bytedance.android.livesdkapi.message.C9599k;
import com.bytedance.android.livesdkapi.message.C9600l;
import com.bytedance.android.livesdkapi.message.C9601m;
import com.bytedance.android.livesdkapi.message.C9603n;
import com.bytedance.android.livesdkapi.message.C9604o;
import com.bytedance.android.livesdkapi.message.C9605p;
import com.bytedance.android.livesdkapi.message.C9606q;
import com.bytedance.android.livesdkapi.message.C9607r;
import com.bytedance.android.livesdkapi.message.C9608s;
import com.bytedance.android.livesdkapi.message.C9609t;
import com.bytedance.android.livesdkapi.message.C9610u;
import com.bytedance.android.livesdkapi.message.C9611v;
import com.bytedance.android.livesdkapi.message.C9612w;
import com.bytedance.android.livesdkapi.message.CommentRoleConfig;
import com.bytedance.android.livesdkapi.message.LandscapeAreaCommon;
import com.bytedance.android.livesdkapi.message.TextPieceImage;
import com.bytedance.android.livesdkapi.message._CombinedText_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._ComboInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._CommentRoleConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._CommonBubbleConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._CommonMessageData_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._DisplayItem_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._ImagesItem_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._LandscapeAreaCommon_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._OfficialCommentConfig_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._PatternRef_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._ProtoMessageFetchResult_BaseProtoMessage_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._ProtoMessageFetchResult_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._PublicAreaCommon_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._SchemaInfo_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextFormat_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextItem_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextPieceGift_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextPieceHeart_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextPieceImage_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextPiecePatternRef_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextPieceUser_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._TextPiece_ProtoDecoder;
import com.bytedance.android.livesdkapi.message._Text_ProtoDecoder;
import com.bytedance.android.tools.p859a.p860a.AbstractC10531b;
import com.bytedance.covode.number.Covode;
import com.bytedance.hotfix.PatchProxy;
import com.bytedance.hotfix.base.ChangeQuickRedirect;
import java.util.HashMap;
import java.util.Map;

/* loaded from: classes11.dex */
public final class _ProtoDecoders_LIVEBASE {
    public static final Map<Class, AbstractC10531b> DECODER_MAP = new HashMap();
    public static ChangeQuickRedirect changeQuickRedirect;

    public final void inject(Map<Class, AbstractC10531b> map) {
        if (PatchProxy.proxy(new Object[]{map}, this, changeQuickRedirect, false, 1).isSupported) {
            return;
        }
        map.put(Appointment.class, new _Appointment_ProtoDecoder());
        map.put(Appointment.LiveFragments.class, new _Appointment_LiveFragments_ProtoDecoder());
        map.put(C2806b.class, new _CateCell_ProtoDecoder());
        map.put(C2810c.class, new _Category_ProtoDecoder());
        map.put(FansClubMember.class, new _FansClubMember_ProtoDecoder());
        map.put(FlexImageModel.class, new _FlexImageModel_ProtoDecoder());
        map.put(FlexImageStruct.class, new _FlexImageStruct_ProtoDecoder());
        map.put(ImageModel.class, new _ImageModel_ProtoDecoder());
        map.put(ImageModel.Content.class, new _ImageModel_Content_ProtoDecoder());
        map.put(C2834h.class, new _ShortTouchArea_ProtoDecoder());
        map.put(C2835i.class, new _ShortTouchBigCard_ProtoDecoder());
        map.put(C2836j.class, new _ShortTouchBubble_ProtoDecoder());
        map.put(C2837k.class, new _ShortTouchInfo_ProtoDecoder());
        map.put(C2837k.C2838a.class, new _ShortTouchInfo_ShortTouchImageLayers_ProtoDecoder());
        map.put(C2837k.C2838a.C2839a.class, new _ShortTouchInfo_ShortTouchImageLayers_Layer_ProtoDecoder());
        map.put(C2840l.class, new _TextViewModel_ProtoDecoder());
        map.put(C2807a.class, new _FeedBanner_ProtoDecoder());
        map.put(C2808b.class, new _FeedBannerContainer_ProtoDecoder());
        map.put(C2809c.class, new _RankRoundBanner_ProtoDecoder());
        map.put(C2817b.class, new _DynamicDetails_ProtoDecoder());
        map.put(C2818c.class, new _DynamicHistory_ProtoDecoder());
        map.put(C2820e.class, new _FoldHistoryData_ProtoDecoder());
        map.put(C2821f.class, new _NoticeDetail_ProtoDecoder());
        map.put(C2823h.class, new _VideoItem_ProtoDecoder());
        map.put(C2827a.class, new _FeedExtra_ProtoDecoder());
        map.put(C2827a.C2828a.class, new _FeedExtra_LogPb_ProtoDecoder());
        map.put(FeedItem.class, new _FeedItem_ProtoDecoder());
        map.put(PlaceHolder.class, new _PlaceHolder_ProtoDecoder());
        map.put(ScheduledLive.class, new _ScheduledLive_ProtoDecoder());
        map.put(ScheduledLiveItem.class, new _ScheduledLiveItem_ProtoDecoder());
        map.put(C2830b.class, new _ExhibitionGiftItem_ProtoDecoder());
        map.put(C2831c.class, new _ExhibitionGiftStruct_ProtoDecoder());
        map.put(C2832f.class, new _ExhibitionUser_ProtoDecoder());
        map.put(C2833g.class, new _GiftExhibitionHomeResponse_ProtoDecoder());
        map.put(C2842c.class, new _RankUser_ProtoDecoder());
        map.put(C2843d.class, new _Ranking_ProtoDecoder());
        map.put(RoomStats.class, new _RoomStats_ProtoDecoder());
        map.put(RoomStats.UserComposition.class, new _RoomStats_UserComposition_ProtoDecoder());
        map.put(C2847a.class, new _TabItem_ProtoDecoder());
        map.put(AccountStats.class, new _AccountStats_ProtoDecoder());
        map.put(AccountTypeInfo.class, new _AccountTypeInfo_ProtoDecoder());
        map.put(ActionConfig.class, new _ActionConfig_ProtoDecoder());
        map.put(ActionConfigs.class, new _ActionConfigs_ProtoDecoder());
        map.put(ActivityBadges.class, new _ActivityBadges_ProtoDecoder());
        map.put(ActivityBadges.GradientColor.class, new _ActivityBadges_GradientColor_ProtoDecoder());
        map.put(ActivityBadges.NewProfileBadge.class, new _ActivityBadges_NewProfileBadge_ProtoDecoder());
        map.put(ActivityRewardInfo.class, new _ActivityRewardInfo_ProtoDecoder());
        map.put(AdminInfo.class, new _AdminInfo_ProtoDecoder());
        map.put(AnchorInfo.class, new _AnchorInfo_ProtoDecoder());
        map.put(AnchorLevel.class, new _AnchorLevel_ProtoDecoder());
        map.put(AuthenticationInfo.class, new _AuthenticationInfo_ProtoDecoder());
        map.put(Author.class, new _Author_ProtoDecoder());
        map.put(AuthorReputation.class, new _AuthorReputation_ProtoDecoder());
        map.put(BaseProfileInfo.class, new _BaseProfileInfo_ProtoDecoder());
        map.put(BorderInfo.class, new _BorderInfo_ProtoDecoder());
        map.put(BroadcastConfig.class, new _BroadcastConfig_ProtoDecoder());
        map.put(Contributor.class, new _Contributor_ProtoDecoder());
        map.put(EcomInfo.class, new _EcomInfo_ProtoDecoder());
        map.put(FansClubData.class, new _FansClubData_ProtoDecoder());
        map.put(FansClubData.UserBadge.class, new _FansClubData_UserBadge_ProtoDecoder());
        map.put(FansGroupInfo.class, new _FansGroupInfo_ProtoDecoder());
        map.put(FollowInfo.class, new _FollowInfo_ProtoDecoder());
        map.put(FraternityInfo.class, new _FraternityInfo_ProtoDecoder());
        map.put(GiftExhibitionHomeStats.class, new _GiftExhibitionHomeStats_ProtoDecoder());
        map.put(GradeBuffInfo.class, new _GradeBuffInfo_ProtoDecoder());
        map.put(GradeIcon.class, new _GradeIcon_ProtoDecoder());
        map.put(HonorWallUi.class, new _HonorWallUi_ProtoDecoder());
        map.put(HonorWallUi.HonorWallBg.class, new _HonorWallUi_HonorWallBg_ProtoDecoder());
        map.put(IndustryCertification.class, new _IndustryCertification_ProtoDecoder());
        map.put(IndustryCertificationProfile.class, new _IndustryCertificationProfile_ProtoDecoder());
        map.put(IndustryCertificationRoom.class, new _IndustryCertificationRoom_ProtoDecoder());
        map.put(MutualFollowUser.class, new _MutualFollowUser_ProtoDecoder());
        map.put(NewAuthenticationInfo.class, new _NewAuthenticationInfo_ProtoDecoder());
        map.put(NewProfileUser.class, new _NewProfileUser_ProtoDecoder());
        map.put(NobleLevelInfo.class, new _NobleLevelInfo_ProtoDecoder());
        map.put(PoiInfo.class, new _PoiInfo_ProtoDecoder());
        map.put(ProfileCustomSkin.class, new _ProfileCustomSkin_ProtoDecoder());
        map.put(ProfileCustomSkin.GradientColor.class, new _ProfileCustomSkin_GradientColor_ProtoDecoder());
        map.put(ProfileCustomSkin.BgUI.class, new _ProfileCustomSkin_BgUI_ProtoDecoder());
        map.put(ProfileCustomSkin.SecondaryButtonUI.class, new _ProfileCustomSkin_SecondaryButtonUI_ProtoDecoder());
        map.put(ProfileCustomSkin.TagUI.class, new _ProfileCustomSkin_TagUI_ProtoDecoder());
        map.put(ProfileCustomSkin.HonorWallUI.class, new _ProfileCustomSkin_HonorWallUI_ProtoDecoder());
        map.put(ProfileFansClub.class, new _ProfileFansClub_ProtoDecoder());
        map.put(ProfileFansClubData.class, new _ProfileFansClubData_ProtoDecoder());
        map.put(ProfileFansClubData.ProfileUserBadge.class, new _ProfileFansClubData_ProfileUserBadge_ProtoDecoder());
        map.put(ProfileFollowInfo.class, new _ProfileFollowInfo_ProtoDecoder());
        map.put(ProfileOwnRoom.class, new _ProfileOwnRoom_ProtoDecoder());
        map.put(ProfilePoiInfo.class, new _ProfilePoiInfo_ProtoDecoder());
        map.put(ProfileSetting.class, new _ProfileSetting_ProtoDecoder());
        map.put(ProfileSkin.class, new _ProfileSkin_ProtoDecoder());
        map.put(ProfileStyleParams.class, new _ProfileStyleParams_ProtoDecoder());
        map.put(ProfileStyleTemplate.class, new _ProfileStyleTemplate_ProtoDecoder());
        map.put(RoomOwner.class, new _RoomOwner_ProtoDecoder());
        map.put(ShopEntrance.class, new _ShopEntrance_ProtoDecoder());
        map.put(ShopHeaderIcon.class, new _ShopHeaderIcon_ProtoDecoder());
        map.put(ShopHeaderInfo.class, new _ShopHeaderInfo_ProtoDecoder());
        map.put(SubscribeInfo.class, new _SubscribeInfo_ProtoDecoder());
        map.put(User.class, new _User_ProtoDecoder());
        map.put(User.OwnRoom.class, new _User_OwnRoom_ProtoDecoder());
        map.put(UserAttr.class, new _UserAttr_ProtoDecoder());
        map.put(UserHonor.class, new _UserHonor_ProtoDecoder());
        map.put(UserProfileDataResp.class, new _UserProfileDataResp_ProtoDecoder());
        map.put(UserProfileDataResp.UserProfileExtra.class, new _UserProfileDataResp_UserProfileExtra_ProtoDecoder());
        map.put(WindowHeaderInfo.class, new _WindowHeaderInfo_ProtoDecoder());
        map.put(XiguaUserParams.class, new _XiguaUserParams_ProtoDecoder());
        map.put(XiguaUserParams.UserExtendInfo.class, new _XiguaUserParams_UserExtendInfo_ProtoDecoder());
        map.put(XiguaUserParams.RocketSchema.class, new _XiguaUserParams_RocketSchema_ProtoDecoder());
        map.put(AssetsModel.class, new _AssetsModel_ProtoDecoder());
        map.put(ResourceH265Model.class, new _ResourceH265Model_ProtoDecoder());
        map.put(ResourceH265SuperModel.class, new _ResourceH265SuperModel_ProtoDecoder());
        map.put(C4086b.class, new _ResourceModel_ProtoDecoder());
        map.put(AnchorLinkUser.class, new _AnchorLinkUser_ProtoDecoder());
        map.put(LinkmicPositionItem.class, new _LinkmicPositionItem_ProtoDecoder());
        map.put(ListUserContent.class, new _ListUserContent_ProtoDecoder());
        map.put(C4534a.class, new _ListUserExtra_ProtoDecoder());
        map.put(ListUserLinkmicAudienceContent.class, new _ListUserLinkmicAudienceContent_ProtoDecoder());
        map.put(ListUserLinkmicContent.class, new _ListUserLinkmicContent_ProtoDecoder());
        map.put(ListUserPKContent.class, new _ListUserPKContent_ProtoDecoder());
        map.put(MicDress.class, new _MicDress_ProtoDecoder());
        map.put(MicDress.VoiceWave.class, new _MicDress_VoiceWave_ProtoDecoder());
        map.put(C4816k.class, new _LinkMicQuickInteract_ProtoDecoder());
        map.put(ListTag.class, new _ListTag_ProtoDecoder());
        map.put(ListTag.ListTagFansClubContent.class, new _ListTag_ListTagFansClubContent_ProtoDecoder());
        map.put(ListTag.ListTagHonorLevelContent.class, new _ListTag_ListTagHonorLevelContent_ProtoDecoder());
        map.put(ListTag.ListTagFriendContent.class, new _ListTag_ListTagFriendContent_ProtoDecoder());
        map.put(ListTag.ListTagFansContent.class, new _ListTag_ListTagFansContent_ProtoDecoder());
        map.put(RoomLinkerContent.class, new _RoomLinkerContent_ProtoDecoder());
        map.put(TeamFightJoinTeamInfo.class, new _TeamFightJoinTeamInfo_ProtoDecoder());
        map.put(InteractEmojiAnim.class, new _InteractEmojiAnim_ProtoDecoder());
        map.put(TalkRoomDigitAvatarEmoji.class, new _TalkRoomDigitAvatarEmoji_ProtoDecoder());
        map.put(C4929c.class, new _TalkRoomDynamicEmoji_ProtoDecoder());
        map.put(TalkRoomEmojiPermission.class, new _TalkRoomEmojiPermission_ProtoDecoder());
        map.put(TalkRoomInteractEmoji.class, new _TalkRoomInteractEmoji_ProtoDecoder());
        map.put(ScreenChatTabResponse.class, new _ScreenChatTabResponse_ProtoDecoder());
        map.put(ScreenChatTabResponse.TabItem.class, new _ScreenChatTabResponse_TabItem_ProtoDecoder());
        map.put(AnnouncementInfo.class, new _AnnouncementInfo_ProtoDecoder());
        map.put(SimpleAnnouncementInfo.class, new _SimpleAnnouncementInfo_ProtoDecoder());
        map.put(C6140f.class, new _BannerCollapseInfo_ProtoDecoder());
        map.put(C6141g.class, new _BannerInRoomCollection_ProtoDecoder());
        map.put(C6141g.C6142a.class, new _BannerInRoomCollection_BannerInfo_ProtoDecoder());
        map.put(ChatResult.class, new _ChatResult_ProtoDecoder());
        map.put(ChatResult.LandscapeAreaCommon.class, new _ChatResult_LandscapeAreaCommon_ProtoDecoder());
        map.put(C6166j.class, new _GuestBattleInfo_ProtoDecoder());
        map.put(C6166j.C6167a.class, new _GuestBattleInfo_BattleResult_ProtoDecoder());
        map.put(C6166j.C6169c.class, new _GuestBattleInfo_GuestBattleGradeItem_ProtoDecoder());
        map.put(C6166j.C6170d.class, new _GuestBattleInfo_GuestBattleUserGradeInfo_ProtoDecoder());
        map.put(C6166j.C6168b.class, new _GuestBattleInfo_GuestBattleContributors_ProtoDecoder());
        map.put(KTVLiveCoreInfo.class, new _KTVLiveCoreInfo_ProtoDecoder());
        map.put(MultiAnchorLinkmicLiveCoreInfo.class, new _MultiAnchorLinkmicLiveCoreInfo_ProtoDecoder());
        map.put(MultiAnchorLinkmicRtcInfo.class, new _MultiAnchorLinkmicRtcInfo_ProtoDecoder());
        map.put(MultiLiveCoreInfo.class, new _MultiLiveCoreInfo_ProtoDecoder());
        map.put(MultiRtcInfo.class, new _MultiRtcInfo_ProtoDecoder());
        map.put(SingingChallengeLiveCoreInfo.class, new _SingingChallengeLiveCoreInfo_ProtoDecoder());
        map.put(SingingChallengeRtcInfo.class, new _SingingChallengeRtcInfo_ProtoDecoder());
        map.put(VideoDuoBattleLiveCoreInfo.class, new _VideoDuoBattleLiveCoreInfo_ProtoDecoder());
        map.put(VideoEqualRoomLiveCoreInfo.class, new _VideoEqualRoomLiveCoreInfo_ProtoDecoder());
        map.put(VideoEqualRoomRtcInfo.class, new _VideoEqualRoomRtcInfo_ProtoDecoder());
        map.put(DoodleTemplate.class, new _DoodleTemplate_ProtoDecoder());
        map.put(C7199p.class, new _Gift_ProtoDecoder());
        map.put(GiftOperation.class, new _GiftOperation_ProtoDecoder());
        map.put(GiftPage.class, new _GiftPage_ProtoDecoder());
        map.put(C7203u.class, new _GiftStructFansClubInfo_ProtoDecoder());
        map.put(C7204w.class, new _GiftTrayInfo_ProtoDecoder());
        map.put(C7205x.class, new _GroupShowInfo_ProtoDecoder());
        map.put(C7206y.class, new _GroupShowUserItem_ProtoDecoder());
        map.put(C7207z.class, new _GroupShowUsersResponse_ProtoDecoder());
        map.put(Portal.class, new _Portal_ProtoDecoder());
        map.put(Prop.class, new _Prop_ProtoDecoder());
        map.put(C7185ae.class, new _ShowStatusLabel_ProtoDecoder());
        map.put(C7395b.class, new _AssetsListResult_ProtoDecoder());
        map.put(AudioInfo.class, new _AudioInfo_ProtoDecoder());
        map.put(InteractiveSongUserInfo.class, new _InteractiveSongUserInfo_ProtoDecoder());
        map.put(KtvMusic.class, new _KtvMusic_ProtoDecoder());
        map.put(KtvMusic.MusicInterval.class, new _KtvMusic_MusicInterval_ProtoDecoder());
        map.put(OrderInfo.class, new _OrderInfo_ProtoDecoder());
        map.put(C8981jo.class, new _TextEffect_ProtoDecoder());
        map.put(C8981jo.C8982a.class, new _TextEffect_Detail_ProtoDecoder());
        map.put(ChargeDeal.class, new _ChargeDeal_ProtoDecoder());
        map.put(ChargeDeal.CurrencyPrice.class, new _ChargeDeal_CurrencyPrice_ProtoDecoder());
        map.put(FirstChargeCheck.class, new _FirstChargeCheck_ProtoDecoder());
        map.put(FirstChargeCheck.FirstChargeCheckExtra.class, new _FirstChargeCheck_FirstChargeCheckExtra_ProtoDecoder());
        map.put(FirstChargeCheck.FirstChargeCheckExtra.RichTextModel.class, new C9472x8ee8d6ea());
        map.put(FirstChargeCheck.FirstChargePackage.class, new _FirstChargeCheck_FirstChargePackage_ProtoDecoder());
        map.put(FirstChargeCheck.FirstChargePackageItem.class, new _FirstChargeCheck_FirstChargePackageItem_ProtoDecoder());
        map.put(FirstChargeCheck.FlexImageStruct.class, new _FirstChargeCheck_FlexImageStruct_ProtoDecoder());
        map.put(C9481c.class, new _ShortTouchResponseData_ProtoDecoder());
        map.put(C9479a.class, new _AnchorBackRecordData_ProtoDecoder());
        map.put(ActivityRoomSkinInfo.class, new _ActivityRoomSkinInfo_ProtoDecoder());
        map.put(AdminRecordAdminInfo.class, new _AdminRecordAdminInfo_ProtoDecoder());
        map.put(AnchorTabLabel.class, new _AnchorTabLabel_ProtoDecoder());
        map.put(C9501d.class, new _BannerInRoom_ProtoDecoder());
        map.put(C9502e.class, new _BaseUserInfo_ProtoDecoder());
        map.put(C9508f.class, new _BattleActivityPKConfig_ProtoDecoder());
        map.put(C9509g.class, new _BattleActivityUser_ProtoDecoder());
        map.put(C9510h.class, new _BattleAnchorContributors_ProtoDecoder());
        map.put(C9511i.class, new _BattleConsecutiveRecordInfo_ProtoDecoder());
        map.put(C9512j.class, new _BattleMode_ProtoDecoder());
        map.put(C9512j.C9513a.class, new _BattleMode_StealTowerData_ProtoDecoder());
        map.put(C9514k.class, new _BattleMultipleMatches3_ProtoDecoder());
        map.put(C9515l.class, new _BattleMultipleMatchesUserInfo_ProtoDecoder());
        map.put(BattleOperationalPlay.class, new _BattleOperationalPlay_ProtoDecoder());
        map.put(C9554m.class, new _BattlePrecisionMatch_ProtoDecoder());
        map.put(BattlePrecisionMatcher.class, new _BattlePrecisionMatcher_ProtoDecoder());
        map.put(C9555n.class, new _BattleRankUser_ProtoDecoder());
        map.put(BattleRivalTag.class, new _BattleRivalTag_ProtoDecoder());
        map.put(C9557p.class, new _BattleStarActivityGrade_ProtoDecoder());
        map.put(C9558q.class, new _BattleStarActivityGradeChange_ProtoDecoder());
        map.put(C9559r.class, new _BattleTask_ProtoDecoder());
        map.put(C9560s.class, new _BattleTitleConfig_ProtoDecoder());
        map.put(BattleUserInfo.class, new _BattleUserInfo_ProtoDecoder());
        map.put(BurstInfo.class, new _BurstInfo_ProtoDecoder());
        map.put(C9561t.class, new _ChannelInfo_ProtoDecoder());
        map.put(CommentConfig.class, new _CommentConfig_ProtoDecoder());
        map.put(CommentPinContent.class, new _CommentPinContent_ProtoDecoder());
        map.put(CommentPinPosition.class, new _CommentPinPosition_ProtoDecoder());
        map.put(CornerMarkReach.class, new _CornerMarkReach_ProtoDecoder());
        map.put(EpisodePreviewImage.class, new _EpisodePreviewImage_ProtoDecoder());
        map.put(FilterWordToutiao.class, new _FilterWordToutiao_ProtoDecoder());
        map.put(GameExtraInfo.class, new _GameExtraInfo_ProtoDecoder());
        map.put(HotRoomInfo.class, new _HotRoomInfo_ProtoDecoder());
        map.put(InteractOpenExtra.class, new _InteractOpenExtra_ProtoDecoder());
        map.put(LinkMicBattleScore.class, new _LinkMicBattleScore_ProtoDecoder());
        map.put(LinkMicBattleSetting.class, new _LinkMicBattleSetting_ProtoDecoder());
        map.put(LinkMicChannelInfo.class, new _LinkMicChannelInfo_ProtoDecoder());
        map.put(LinkerDetail.class, new _LinkerDetail_ProtoDecoder());
        map.put(LinkerUsers.class, new _LinkerUsers_ProtoDecoder());
        map.put(LiveCoreSDKData.class, new _LiveCoreSDKData_ProtoDecoder());
        map.put(LiveCoreSDKData.PullData.class, new _LiveCoreSDKData_PullData_ProtoDecoder());
        map.put(LiveCoreSDKData.PlayInfo.class, new _LiveCoreSDKData_PlayInfo_ProtoDecoder());
        map.put(LiveCoreSDKData.Clip.class, new _LiveCoreSDKData_Clip_ProtoDecoder());
        map.put(LiveCoreSDKData.Extension.class, new _LiveCoreSDKData_Extension_ProtoDecoder());
        map.put(LiveCoreSDKData.PushData.class, new _LiveCoreSDKData_PushData_ProtoDecoder());
        map.put(LiveCoreSDKData.Options.class, new _LiveCoreSDKData_Options_ProtoDecoder());
        map.put(LiveCoreSDKData.Quality.class, new _LiveCoreSDKData_Quality_ProtoDecoder());
        map.put(LiveCoreSDKData.ResolutionParams.class, new _LiveCoreSDKData_ResolutionParams_ProtoDecoder());
        map.put(LiveNearbyTVInfo.class, new _LiveNearbyTVInfo_ProtoDecoder());
        map.put(LivePlayTagInfo.class, new _LivePlayTagInfo_ProtoDecoder());
        map.put(MatchInfo.class, new _MatchInfo_ProtoDecoder());
        map.put(MatchInfo.MatchSkinInfo.class, new _MatchInfo_MatchSkinInfo_ProtoDecoder());
        map.put(MatchInfo.FollowBtnSkin.class, new _MatchInfo_FollowBtnSkin_ProtoDecoder());
        map.put(OfficialChannelExtraInfo.class, new _OfficialChannelExtraInfo_ProtoDecoder());
        map.put(OfficialChannelInfo.class, new _OfficialChannelInfo_ProtoDecoder());
        map.put(OfficialRoomInfo.class, new _OfficialRoomInfo_ProtoDecoder());
        map.put(PKIconBubble.class, new _PKIconBubble_ProtoDecoder());
        map.put(C9564y.class, new _PkActivePush_ProtoDecoder());
        map.put(C9565z.class, new _PkActivePushMatcher_ProtoDecoder());
        map.put(PreviewSwitch.class, new _PreviewSwitch_ProtoDecoder());
        map.put(PublishItemTextExtraInfo.class, new _PublishItemTextExtraInfo_ProtoDecoder());
        map.put(QuizExtra.class, new _QuizExtra_ProtoDecoder());
        map.put(ReplayInfo.class, new _ReplayInfo_ProtoDecoder());
        map.put(Reservation.class, new _Reservation_ProtoDecoder());
        map.put(Room.class, new _Room_ProtoDecoder());
        map.put(RoomAppearance.class, new _RoomAppearance_ProtoDecoder());
        map.put(RoomAuthStatus.class, new _RoomAuthStatus_ProtoDecoder());
        map.put(RoomAuthStatus.OffReason.class, new _RoomAuthStatus_OffReason_ProtoDecoder());
        map.put(RoomAuthStatus.RoomAuthSpecialStyle.class, new _RoomAuthStatus_RoomAuthSpecialStyle_ProtoDecoder());
        map.put(RoomAuthStatus.Style.class, new _RoomAuthStatus_Style_ProtoDecoder());
        map.put(RoomBorderInfo.class, new _RoomBorderInfo_ProtoDecoder());
        map.put(RoomBorderInfo.StaticBorderInfo.class, new _RoomBorderInfo_StaticBorderInfo_ProtoDecoder());
        map.put(RoomBorderInfo.DynamicBorderInfo.class, new _RoomBorderInfo_DynamicBorderInfo_ProtoDecoder());
        map.put(RoomCart.class, new _RoomCart_ProtoDecoder());
        map.put(RoomCart.RoomCartStateVertical.class, new _RoomCart_RoomCartStateVertical_ProtoDecoder());
        map.put(RoomCart.RoomCartStateHorizontal.class, new _RoomCart_RoomCartStateHorizontal_ProtoDecoder());
        map.put(RoomCart.RoomCartIcons.class, new _RoomCart_RoomCartIcons_ProtoDecoder());
        map.put(RoomDecoration.class, new _RoomDecoration_ProtoDecoder());
        map.put(RoomDecoration.TextComposeOption.class, new _RoomDecoration_TextComposeOption_ProtoDecoder());
        map.put(RoomIMInfo.class, new _RoomIMInfo_ProtoDecoder());
        map.put(RoomLinkInfo.class, new _RoomLinkInfo_ProtoDecoder());
        map.put(RoomLinkerUsers.class, new _RoomLinkerUsers_ProtoDecoder());
        map.put(RoomTab.class, new _RoomTab_ProtoDecoder());
        map.put(RoomUserAttr.class, new _RoomUserAttr_ProtoDecoder());
        map.put(ShortTermIndicatorConfig.class, new _ShortTermIndicatorConfig_ProtoDecoder());
        map.put(ShortTermIndicatorConfig.Element.class, new _ShortTermIndicatorConfig_Element_ProtoDecoder());
        map.put(ShortTermIndicatorConfig.ForbiddenType.class, new _ShortTermIndicatorConfig_ForbiddenType_ProtoDecoder());
        map.put(ShortTouchAuth.class, new _ShortTouchAuth_ProtoDecoder());
        map.put(com.bytedance.android.livesdkapi.depend.model.live.SimpleAnnouncementInfo.class, new com.bytedance.android.livesdkapi.depend.model.live._SimpleAnnouncementInfo_ProtoDecoder());
        map.put(StreamUrl.class, new _StreamUrl_ProtoDecoder());
        map.put(StreamUrl.PlaySetting.class, new _StreamUrl_PlaySetting_ProtoDecoder());
        map.put(StreamUrlExtra.class, new _StreamUrlExtra_ProtoDecoder());
        map.put(StreamUrlExtra.SrConfig.class, new _StreamUrlExtra_SrConfig_ProtoDecoder());
        map.put(TeamTask.class, new _TeamTask_ProtoDecoder());
        map.put(C9488ab.class, new _TeamTaskConfig_ProtoDecoder());
        map.put(C9490ac.class, new _TeamTaskInfo_ProtoDecoder());
        map.put(TeamTaskItemCardInfo.class, new _TeamTaskItemCardInfo_ProtoDecoder());
        map.put(C9491ad.class, new _TeamTaskPeriodConfig_ProtoDecoder());
        map.put(C9492ae.class, new _TeamTaskReward_ProtoDecoder());
        map.put(TopFanTicket.class, new _TopFanTicket_ProtoDecoder());
        map.put(UserHealthScoreInfo.class, new _UserHealthScoreInfo_ProtoDecoder());
        map.put(VipData.class, new _VipData_ProtoDecoder());
        map.put(WelfareProjectInfo.class, new _WelfareProjectInfo_ProtoDecoder());
        map.put(AudioSpeakingImageList.class, new _AudioSpeakingImageList_ProtoDecoder());
        map.put(SpeakingImage.class, new _SpeakingImage_ProtoDecoder());
        map.put(VoiceLiveTheme.class, new _VoiceLiveTheme_ProtoDecoder());
        map.put(CircleInfo.class, new _CircleInfo_ProtoDecoder());
        map.put(EasterEggData.class, new _EasterEggData_ProtoDecoder());
        map.put(AlbumItem.class, new _AlbumItem_ProtoDecoder());
        map.put(CommentColor.class, new _CommentColor_ProtoDecoder());
        map.put(com.bytedance.android.livesdkapi.depend.model.live.episode.CommentConfig.class, new com.bytedance.android.livesdkapi.depend.model.live.episode._CommentConfig_ProtoDecoder());
        map.put(CommentMedal.class, new _CommentMedal_ProtoDecoder());
        map.put(CommentRole.class, new _CommentRole_ProtoDecoder());
        map.put(CommentSpecialEffectData.class, new _CommentSpecialEffectData_ProtoDecoder());
        map.put(CommentSpecialEffectData.TimeRange.class, new _CommentSpecialEffectData_TimeRange_ProtoDecoder());
        map.put(DefinitionInfo.class, new _DefinitionInfo_ProtoDecoder());
        map.put(C9503b.class, new _EnterVideoResult_ProtoDecoder());
        map.put(Episode.class, new _Episode_ProtoDecoder());
        map.put(EpisodeCorrelationSeasonInfo.class, new _EpisodeCorrelationSeasonInfo_ProtoDecoder());
        map.put(EpisodeExtraInfo.class, new _EpisodeExtraInfo_ProtoDecoder());
        map.put(EpisodeHighLight.class, new _EpisodeHighLight_ProtoDecoder());
        map.put(EpisodeMod.class, new _EpisodeMod_ProtoDecoder());
        map.put(EpisodeOnlyTaInfo.class, new _EpisodeOnlyTaInfo_ProtoDecoder());
        map.put(EpisodeOnlyTaSegmentScope.class, new _EpisodeOnlyTaSegmentScope_ProtoDecoder());
        map.put(EpisodeOnlyTaSegments.class, new _EpisodeOnlyTaSegments_ProtoDecoder());
        map.put(EpisodePaidInfo.class, new _EpisodePaidInfo_ProtoDecoder());
        map.put(EpisodePremierePlay.class, new _EpisodePremierePlay_ProtoDecoder());
        map.put(EpisodePreviewBottom.class, new _EpisodePreviewBottom_ProtoDecoder());
        map.put(EpisodeShare.class, new _EpisodeShare_ProtoDecoder());
        map.put(EpisodeStartHighLight.class, new _EpisodeStartHighLight_ProtoDecoder());
        map.put(EpisodeStatistics.class, new _EpisodeStatistics_ProtoDecoder());
        map.put(EpisodeUserStatistics.class, new _EpisodeUserStatistics_ProtoDecoder());
        map.put(EpisodeVideo.class, new _EpisodeVideo_ProtoDecoder());
        map.put(EpisodeVideo.StartLocation.class, new _EpisodeVideo_StartLocation_ProtoDecoder());
        map.put(EpisodeVideoModelContainer.class, new _EpisodeVideoModelContainer_ProtoDecoder());
        map.put(EpisodeWatchInfo.class, new _EpisodeWatchInfo_ProtoDecoder());
        map.put(ItemComment.class, new _ItemComment_ProtoDecoder());
        map.put(ItemDetail.class, new _ItemDetail_ProtoDecoder());
        map.put(C9505d.class, new _LivePingExtra_ProtoDecoder());
        map.put(MarkDetail.class, new _MarkDetail_ProtoDecoder());
        map.put(MoreEntry.class, new _MoreEntry_ProtoDecoder());
        map.put(MoreHighLightList.class, new _MoreHighLightList_ProtoDecoder());
        map.put(MoreSpectacular.class, new _MoreSpectacular_ProtoDecoder());
        map.put(PriceInfo.class, new _PriceInfo_ProtoDecoder());
        map.put(PriceInfo.StandardMoney.class, new _PriceInfo_StandardMoney_ProtoDecoder());
        map.put(ReplayStreamUrl.class, new _ReplayStreamUrl_ProtoDecoder());
        map.put(ReplayStreamUrl.StreamAddr.class, new _ReplayStreamUrl_StreamAddr_ProtoDecoder());
        map.put(SeasonAlbumTab.class, new _SeasonAlbumTab_ProtoDecoder());
        map.put(SegmentFlowTime.class, new _SegmentFlowTime_ProtoDecoder());
        map.put(ShowCenterShowInfo.class, new _ShowCenterShowInfo_ProtoDecoder());
        map.put(ToolbarBackgroundConfig.class, new _ToolbarBackgroundConfig_ProtoDecoder());
        map.put(TopicToast.class, new _TopicToast_ProtoDecoder());
        map.put(VSBar.class, new _VSBar_ProtoDecoder());
        map.put(VSCameraInfo.class, new _VSCameraInfo_ProtoDecoder());
        map.put(VSFreeViewRange.class, new _VSFreeViewRange_ProtoDecoder());
        map.put(C9507f.class, new _VSRoomIDData_ProtoDecoder());
        map.put(VSToolbarConfigData.class, new _VSToolbarConfigData_ProtoDecoder());
        map.put(VsTopicInfo.class, new _VsTopicInfo_ProtoDecoder());
        map.put(VsTopicInfo.TimePoint.class, new _VsTopicInfo_TimePoint_ProtoDecoder());
        map.put(ConsultInfo.class, new _ConsultInfo_ProtoDecoder());
        map.put(IMIndustryServiceInfo.class, new _IMIndustryServiceInfo_ProtoDecoder());
        map.put(C9532b.class, new _BanUser_ProtoDecoder());
        map.put(C9533c.class, new _BattleLinkerInviteMessageExtra_ProtoDecoder());
        map.put(C9533c.C9534a.class, new _BattleLinkerInviteMessageExtra_GameInfo_ProtoDecoder());
        map.put(C9535d.class, new _BattleStarActivityGradeMedal_ProtoDecoder());
        map.put(C9536f.class, new _CityEffect_ProtoDecoder());
        map.put(C9537g.class, new _InviterRivalExtra_ProtoDecoder());
        map.put(C9538i.class, new _LinkMicAudienceEnterMessageExtra_ProtoDecoder());
        map.put(C9538i.C9539a.class, new _LinkMicAudienceEnterMessageExtra_UserInfo_ProtoDecoder());
        map.put(C9542o.class, new _LinkerAvatarAuditContent_ProtoDecoder());
        map.put(C9543p.class, new _LinkerBanContent_ProtoDecoder());
        map.put(C9544q.class, new _LinkerBattleConnectContent_ProtoDecoder());
        map.put(C9545r.class, new _LinkerCancelContent_ProtoDecoder());
        map.put(C9546s.class, new _LinkerClickScreenContent_ProtoDecoder());
        map.put(C9547t.class, new _LinkerCreateContent_ProtoDecoder());
        map.put(C9548u.class, new _LinkerCrossRoomUpdateContent_ProtoDecoder());
        map.put(C9549v.class, new _LinkerEnterContent_ProtoDecoder());
        map.put(C9550w.class, new _LinkerFollowStrongGuideContent_ProtoDecoder());
        map.put(C9551x.class, new _LinkerGuestExitCastScreenContent_ProtoDecoder());
        map.put(C9552y.class, new _LinkerGuestInviteContent_ProtoDecoder());
        map.put(C9553z.class, new _LinkerInviteContent_ProtoDecoder());
        map.put(C9516aa.class, new _LinkerInvitePrepareContent_ProtoDecoder());
        map.put(C9517ab.class, new _LinkerItemContent_ProtoDecoder());
        map.put(C9518ac.class, new _LinkerKickOutContent_ProtoDecoder());
        map.put(C9519ad.class, new _LinkerLeaveContent_ProtoDecoder());
        map.put(C9520ae.class, new _LinkerLinkedListChangeContent_ProtoDecoder());
        map.put(C9521af.class, new _LinkerLowBalanceForPaidLinkmicContent_ProtoDecoder());
        map.put(C9522ag.class, new _LinkerReplyContent_ProtoDecoder());
        map.put(C9523ai.class, new _LinkerResumeAudienceContent_ProtoDecoder());
        map.put(C9524aj.class, new _LinkerSetting_ProtoDecoder());
        map.put(C9525ak.class, new _LinkerShareVideoImContent_ProtoDecoder());
        map.put(C9526al.class, new _LinkerSysKickOutContent_ProtoDecoder());
        map.put(LinkerUpdateLinkTypeApplyContent.class, new _LinkerUpdateLinkTypeApplyContent_ProtoDecoder());
        map.put(LinkerUpdateLinkTypeReplyContent.class, new _LinkerUpdateLinkTypeReplyContent_ProtoDecoder());
        map.put(C9527am.class, new _LinkerUpdateUserContent_ProtoDecoder());
        map.put(C9528an.class, new _LinkerViolationReminderContent_ProtoDecoder());
        map.put(C9529ao.class, new _LinkerWaitingListChangeContent_ProtoDecoder());
        map.put(C9530ap.class, new _LinkmicInfo_ProtoDecoder());
        map.put(C9531aq.class, new _MatchEffect_ProtoDecoder());
        map.put(RoomLinkMicSyncData.class, new _RoomLinkMicSyncData_ProtoDecoder());
        map.put(PaidLiveData.class, new _PaidLiveData_ProtoDecoder());
        map.put(TicketBriefData.class, new _TicketBriefData_ProtoDecoder());
        map.put(TicketData.class, new _TicketData_ProtoDecoder());
        map.put(TicketData.PaidLivePriceInfoV2.class, new _TicketData_PaidLivePriceInfoV2_ProtoDecoder());
        map.put(TicketPriceInfo.class, new _TicketPriceInfo_ProtoDecoder());
        map.put(RoomChannelData.class, new _RoomChannelData_ProtoDecoder());
        map.put(RoomChannelInfo.class, new _RoomChannelInfo_ProtoDecoder());
        map.put(ShowEmojiInfo.class, new _ShowEmojiInfo_ProtoDecoder());
        map.put(ShowEmojiListResponse.class, new _ShowEmojiListResponse_ProtoDecoder());
        map.put(C9592b.class, new _CombinedText_ProtoDecoder());
        map.put(C9593c.class, new _ComboInfo_ProtoDecoder());
        map.put(CommentRoleConfig.class, new _CommentRoleConfig_ProtoDecoder());
        map.put(C9594d.class, new _CommonBubbleConfig_ProtoDecoder());
        map.put(C9595e.class, new _CommonMessageData_ProtoDecoder());
        map.put(C9596f.class, new _DisplayItem_ProtoDecoder());
        map.put(C9598i.class, new _ImagesItem_ProtoDecoder());
        map.put(LandscapeAreaCommon.class, new _LandscapeAreaCommon_ProtoDecoder());
        map.put(C9599k.class, new _OfficialCommentConfig_ProtoDecoder());
        map.put(C9600l.class, new _PatternRef_ProtoDecoder());
        map.put(C9601m.class, new _ProtoMessageFetchResult_ProtoDecoder());
        map.put(C9601m.C9602a.class, new _ProtoMessageFetchResult_BaseProtoMessage_ProtoDecoder());
        map.put(C9603n.class, new _PublicAreaCommon_ProtoDecoder());
        map.put(C9604o.class, new _SchemaInfo_ProtoDecoder());
        map.put(C9605p.class, new _Text_ProtoDecoder());
        map.put(C9606q.class, new _TextFormat_ProtoDecoder());
        map.put(C9607r.class, new _TextItem_ProtoDecoder());
        map.put(C9608s.class, new _TextPiece_ProtoDecoder());
        map.put(C9609t.class, new _TextPieceGift_ProtoDecoder());
        map.put(C9610u.class, new _TextPieceHeart_ProtoDecoder());
        map.put(TextPieceImage.class, new _TextPieceImage_ProtoDecoder());
        map.put(C9611v.class, new _TextPiecePatternRef_ProtoDecoder());
        map.put(C9612w.class, new _TextPieceUser_ProtoDecoder());
    }

    static {
        Covode.recordClassIndex(14099);
    }
}
